# Generated by Django 5.1.15 on 2026-04-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KPITrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        choices=[
                            ("funnel", "Funnel"),
                            ("revenue", "Revenue trend"),
                            ("state_rto", "State RTO"),
                            ("product_perf", "Product performance"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("d", models.CharField(blank=True, default="", max_length=40)),
                ("stage", models.CharField(blank=True, default="", max_length=40)),
                ("state", models.CharField(blank=True, default="", max_length=60)),
                ("product", models.CharField(blank=True, default="", max_length=80)),
                ("value", models.IntegerField(blank=True, null=True)),
                ("revenue", models.IntegerField(blank=True, null=True)),
                ("profit", models.IntegerField(blank=True, null=True)),
                ("leads", models.IntegerField(blank=True, null=True)),
                ("orders", models.IntegerField(blank=True, null=True)),
                ("delivered", models.IntegerField(blank=True, null=True)),
                ("rto", models.IntegerField(blank=True, null=True)),
                ("rto_pct", models.FloatField(blank=True, null=True)),
                ("net_profit", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ("series", "sort_order"),
            },
        ),
    ]
