from __future__ import annotations

from django.urls import path

from .views import (
    AiProviderRoutingView,
    ControlledRuntimeReadinessView,
    CurrentOrganizationView,
    DataCoverageView,
    FeatureFlagsView,
    MyOrganizationsView,
    OrgScopeReadinessView,
    ProviderExecutionAttemptArchiveView,
    ProviderExecutionAttemptDetailView,
    ProviderExecutionAttemptPrepareView,
    ProviderExecutionAttemptRollbackView,
    ProviderExecutionAttemptsListView,
    ProviderTestPlanApproveView,
    ProviderTestPlanArchiveView,
    ProviderTestPlanDetailView,
    ProviderTestPlanPrepareView,
    ProviderTestPlanRejectView,
    ProviderTestPlanValidateView,
    ProviderTestPlansListView,
    RazorpayBusinessMutationSandboxPlanView,
    RazorpayBusinessMutationSandboxReadinessView,
    RazorpayPaymentDispatchPilotPlanDetailView,
    RazorpayPaymentDispatchPilotPlanPreviewView,
    RazorpayPaymentDispatchPilotPlanReadinessView,
    RazorpayPaymentDispatchPilotPlansListView,
    RazorpayControlledPilotExecutionAttemptDetailView,
    RazorpayControlledPilotExecutionAttemptsListView,
    RazorpayControlledPilotExecutionPreviewView,
    RazorpayControlledPilotExecutionReadinessView,
    RazorpayControlledPilotExecutionRollbacksView,
    RazorpayCourierReadinessDryRunsView,
    RazorpayCourierReadinessGateDetailView,
    RazorpayCourierReadinessGatesListView,
    RazorpayCourierReadinessPreviewView,
    RazorpayCourierReadinessReadinessView,
    RazorpayCourierExecutionAttemptDetailView,
    RazorpayCourierExecutionAttemptsListView,
    RazorpayCourierExecutionPreviewView,
    RazorpayCourierExecutionReadinessView,
    RazorpayCourierExecutionRollbacksView,
    RazorpayCourierExecutionEvidenceLockDetailView,
    RazorpayCourierExecutionEvidenceLockPreviewView,
    RazorpayCourierExecutionEvidenceLockReadinessView,
    RazorpayCourierExecutionEvidenceLocksListView,
    WhatsAppInternalSendAttemptDetailView,
    WhatsAppInternalSendAttemptsListView,
    WhatsAppInternalSendPreviewView,
    WhatsAppInternalSendReadinessView,
    Phase7IFinalAuditLockDetailView,
    Phase7IFinalAuditLockPreviewView,
    Phase7IFinalAuditLockReadinessView,
    Phase7IFinalAuditLocksListView,
    Phase8APaymentOrderMutationSandboxDryRunsView,
    Phase8APaymentOrderMutationSandboxGateDetailView,
    Phase8APaymentOrderMutationSandboxGatesListView,
    Phase8APaymentOrderMutationSandboxPreviewView,
    Phase8APaymentOrderMutationSandboxReadinessView,
    Phase8BPaymentOrderMutationReviewDryRunsView,
    Phase8BPaymentOrderMutationReviewGateDetailView,
    Phase8BPaymentOrderMutationReviewGatesListView,
    Phase8BPaymentOrderMutationReviewPreviewView,
    Phase8BPaymentOrderMutationReviewReadinessView,
    Phase8CPaymentOrderControlledMutationAttemptsView,
    Phase8CPaymentOrderControlledMutationGateDetailView,
    Phase8CPaymentOrderControlledMutationGatesListView,
    Phase8CPaymentOrderControlledMutationPreviewView,
    Phase8CPaymentOrderControlledMutationReadinessView,
    Phase8CPaymentOrderControlledMutationRollbacksView,
    Phase8DControlledMutationEvidenceLockDetailView,
    Phase8DControlledMutationEvidenceLockPreviewView,
    Phase8DControlledMutationEvidenceLockReadinessView,
    Phase8DControlledMutationEvidenceLocksListView,
    Phase8ERealCustomerPaymentOrderPilotCandidatesView,
    Phase8ERealCustomerPaymentOrderPilotDryRunsView,
    Phase8ERealCustomerPaymentOrderPilotGateDetailView,
    Phase8ERealCustomerPaymentOrderPilotGatesListView,
    Phase8ERealCustomerPaymentOrderPilotPreviewView,
    Phase8ERealCustomerPaymentOrderPilotReadinessView,
    RazorpayWhatsAppInternalNotificationDryRunsView,
    RazorpayWhatsAppInternalNotificationGateDetailView,
    RazorpayWhatsAppInternalNotificationGatesListView,
    RazorpayWhatsAppInternalNotificationPreviewView,
    RazorpayWhatsAppInternalNotificationReadinessView,
    RazorpayControlledPilotGateDetailView,
    RazorpayControlledPilotGateDryRunsView,
    RazorpayControlledPilotGatePreviewView,
    RazorpayControlledPilotGateReadinessView,
    RazorpayControlledPilotGateRollbackDryRunsView,
    RazorpayControlledPilotGatesListView,
    RazorpayPhase6FinalAuditLockDetailView,
    RazorpayPhase6FinalAuditLockPreviewView,
    RazorpayPhase6FinalAuditLockReadinessView,
    RazorpayPhase6FinalAuditLocksListView,
    RazorpayPaymentDispatchReadinessGateDetailView,
    RazorpayPaymentDispatchReadinessGatesListView,
    RazorpayPaymentDispatchReadinessPreviewView,
    RazorpayPaymentDispatchReadinessView,
    RazorpayPaymentOrderWorkflowGateDetailView,
    RazorpayPaymentOrderWorkflowGatePreviewView,
    RazorpayPaymentOrderWorkflowGateReadinessView,
    RazorpayPaymentOrderWorkflowGatesListView,
    RazorpaySandboxPaidStatusMutationAttemptDetailView,
    RazorpaySandboxPaidStatusMutationAttemptsListView,
    RazorpaySandboxPaidStatusMutationPreviewView,
    RazorpaySandboxPaidStatusMutationReadinessView,
    RazorpaySandboxStatusMappingReadinessView,
    RazorpaySandboxStatusReviewApproveView,
    RazorpaySandboxStatusReviewArchiveView,
    RazorpaySandboxStatusReviewDetailView,
    RazorpaySandboxStatusReviewPrepareView,
    RazorpaySandboxStatusReviewRejectView,
    RazorpaySandboxStatusReviewsListView,
    RazorpayExecutionAuditReviewView,
    RazorpayWebhookEventDetailView,
    RazorpayWebhookEventsListView,
    RazorpayWebhookHandlerReadinessView,
    RazorpayWebhookPlanView,
    RazorpayWebhookReadinessView,
    RazorpayWebhookSimulateView,
    RuntimeDryRunView,
    RuntimeLiveGateApproveView,
    RuntimeLiveGateKillSwitchView,
    RuntimeLiveGatePoliciesView,
    RuntimeLiveGatePreviewView,
    RuntimeLiveGateRejectView,
    RuntimeLiveGateSimulationApproveView,
    RuntimeLiveGateSimulationDetailView,
    RuntimeLiveGateSimulationPrepareView,
    RuntimeLiveGateSimulationRejectView,
    RuntimeLiveGateSimulationRequestApprovalView,
    RuntimeLiveGateSimulationRollbackView,
    RuntimeLiveGateSimulationRunView,
    RuntimeLiveGateSimulationsView,
    RuntimeLiveGateRequestsView,
    RuntimeLiveGateView,
    RuntimeRoutingReadinessView,
    SaasAdminOrganizationDetailView,
    SaasAdminOrganizationsView,
    SaasAdminOverviewView,
    SaasIntegrationReadinessView,
    SaasIntegrationSettingDetailView,
    SaasIntegrationSettingsView,
    WritePathReadinessView,
)


urlpatterns = [
    path(
        "current-organization/",
        CurrentOrganizationView.as_view(),
        name="saas-current-organization",
    ),
    path(
        "my-organizations/",
        MyOrganizationsView.as_view(),
        name="saas-my-organizations",
    ),
    path(
        "feature-flags/",
        FeatureFlagsView.as_view(),
        name="saas-feature-flags",
    ),
    path(
        "data-coverage/",
        DataCoverageView.as_view(),
        name="saas-data-coverage",
    ),
    path(
        "org-scope-readiness/",
        OrgScopeReadinessView.as_view(),
        name="saas-org-scope-readiness",
    ),
    path(
        "write-path-readiness/",
        WritePathReadinessView.as_view(),
        name="saas-write-path-readiness",
    ),
    path(
        "admin/overview/",
        SaasAdminOverviewView.as_view(),
        name="saas-admin-overview",
    ),
    path(
        "admin/organizations/",
        SaasAdminOrganizationsView.as_view(),
        name="saas-admin-organizations",
    ),
    path(
        "admin/organizations/<int:organization_id>/",
        SaasAdminOrganizationDetailView.as_view(),
        name="saas-admin-organization-detail",
    ),
    path(
        "admin/integration-settings/",
        SaasIntegrationSettingsView.as_view(),
        name="saas-admin-integration-settings",
    ),
    path(
        "admin/integration-settings/<int:setting_id>/",
        SaasIntegrationSettingDetailView.as_view(),
        name="saas-admin-integration-setting-detail",
    ),
    path(
        "admin/integration-readiness/",
        SaasIntegrationReadinessView.as_view(),
        name="saas-admin-integration-readiness",
    ),
    path(
        "runtime-routing-readiness/",
        RuntimeRoutingReadinessView.as_view(),
        name="saas-runtime-routing-readiness",
    ),
    path(
        "runtime-dry-run/",
        RuntimeDryRunView.as_view(),
        name="saas-runtime-dry-run",
    ),
    path(
        "ai-provider-routing/",
        AiProviderRoutingView.as_view(),
        name="saas-ai-provider-routing",
    ),
    path(
        "controlled-runtime-readiness/",
        ControlledRuntimeReadinessView.as_view(),
        name="saas-controlled-runtime-readiness",
    ),
    path(
        "runtime-live-gate/",
        RuntimeLiveGateView.as_view(),
        name="saas-runtime-live-gate",
    ),
    path(
        "runtime-live-gate/requests/",
        RuntimeLiveGateRequestsView.as_view(),
        name="saas-runtime-live-gate-requests",
    ),
    path(
        "runtime-live-gate/policies/",
        RuntimeLiveGatePoliciesView.as_view(),
        name="saas-runtime-live-gate-policies",
    ),
    path(
        "runtime-live-gate/kill-switch/",
        RuntimeLiveGateKillSwitchView.as_view(),
        name="saas-runtime-live-gate-kill-switch",
    ),
    path(
        "runtime-live-gate/preview/",
        RuntimeLiveGatePreviewView.as_view(),
        name="saas-runtime-live-gate-preview",
    ),
    path(
        "runtime-live-gate/requests/<int:request_id>/approve/",
        RuntimeLiveGateApproveView.as_view(),
        name="saas-runtime-live-gate-request-approve",
    ),
    path(
        "runtime-live-gate/requests/<int:request_id>/reject/",
        RuntimeLiveGateRejectView.as_view(),
        name="saas-runtime-live-gate-request-reject",
    ),
    path(
        "runtime-live-gate/simulations/",
        RuntimeLiveGateSimulationsView.as_view(),
        name="saas-runtime-live-gate-simulations",
    ),
    path(
        "runtime-live-gate/simulations/<int:simulation_id>/",
        RuntimeLiveGateSimulationDetailView.as_view(),
        name="saas-runtime-live-gate-simulation-detail",
    ),
    path(
        "runtime-live-gate/simulations/prepare/",
        RuntimeLiveGateSimulationPrepareView.as_view(),
        name="saas-runtime-live-gate-simulation-prepare",
    ),
    path(
        "runtime-live-gate/simulations/<int:simulation_id>/request-approval/",
        RuntimeLiveGateSimulationRequestApprovalView.as_view(),
        name="saas-runtime-live-gate-simulation-request-approval",
    ),
    path(
        "runtime-live-gate/simulations/<int:simulation_id>/approve/",
        RuntimeLiveGateSimulationApproveView.as_view(),
        name="saas-runtime-live-gate-simulation-approve",
    ),
    path(
        "runtime-live-gate/simulations/<int:simulation_id>/reject/",
        RuntimeLiveGateSimulationRejectView.as_view(),
        name="saas-runtime-live-gate-simulation-reject",
    ),
    path(
        "runtime-live-gate/simulations/<int:simulation_id>/run/",
        RuntimeLiveGateSimulationRunView.as_view(),
        name="saas-runtime-live-gate-simulation-run",
    ),
    path(
        "runtime-live-gate/simulations/<int:simulation_id>/rollback/",
        RuntimeLiveGateSimulationRollbackView.as_view(),
        name="saas-runtime-live-gate-simulation-rollback",
    ),
    # Phase 6J — Single Internal Provider Test Plan.
    path(
        "provider-test-plans/",
        ProviderTestPlansListView.as_view(),
        name="saas-provider-test-plans",
    ),
    path(
        "provider-test-plans/prepare/",
        ProviderTestPlanPrepareView.as_view(),
        name="saas-provider-test-plans-prepare",
    ),
    path(
        "provider-test-plans/<str:plan_id>/",
        ProviderTestPlanDetailView.as_view(),
        name="saas-provider-test-plan-detail",
    ),
    path(
        "provider-test-plans/<str:plan_id>/validate/",
        ProviderTestPlanValidateView.as_view(),
        name="saas-provider-test-plan-validate",
    ),
    path(
        "provider-test-plans/<str:plan_id>/approve/",
        ProviderTestPlanApproveView.as_view(),
        name="saas-provider-test-plan-approve",
    ),
    path(
        "provider-test-plans/<str:plan_id>/reject/",
        ProviderTestPlanRejectView.as_view(),
        name="saas-provider-test-plan-reject",
    ),
    path(
        "provider-test-plans/<str:plan_id>/archive/",
        ProviderTestPlanArchiveView.as_view(),
        name="saas-provider-test-plan-archive",
    ),
    # Phase 6K — Single Internal Razorpay Test-Mode Execution Gate.
    path(
        "provider-execution-attempts/",
        ProviderExecutionAttemptsListView.as_view(),
        name="saas-provider-execution-attempts",
    ),
    path(
        "provider-execution-attempts/prepare/",
        ProviderExecutionAttemptPrepareView.as_view(),
        name="saas-provider-execution-attempts-prepare",
    ),
    path(
        "provider-execution-attempts/<str:execution_id>/",
        ProviderExecutionAttemptDetailView.as_view(),
        name="saas-provider-execution-attempt-detail",
    ),
    path(
        "provider-execution-attempts/<str:execution_id>/rollback/",
        ProviderExecutionAttemptRollbackView.as_view(),
        name="saas-provider-execution-attempt-rollback",
    ),
    path(
        "provider-execution-attempts/<str:execution_id>/archive/",
        ProviderExecutionAttemptArchiveView.as_view(),
        name="saas-provider-execution-attempt-archive",
    ),
    # Phase 6L — Razorpay Test Execution Audit Review + Webhook Readiness Plan.
    path(
        "razorpay/execution-audit/",
        RazorpayExecutionAuditReviewView.as_view(),
        name="saas-razorpay-execution-audit",
    ),
    path(
        "razorpay/webhook-readiness/",
        RazorpayWebhookReadinessView.as_view(),
        name="saas-razorpay-webhook-readiness",
    ),
    path(
        "razorpay/webhook-plan/",
        RazorpayWebhookPlanView.as_view(),
        name="saas-razorpay-webhook-plan",
    ),
    # Phase 6M — test-mode handler readiness + event browser + simulator.
    path(
        "razorpay/webhook-handler-readiness/",
        RazorpayWebhookHandlerReadinessView.as_view(),
        name="saas-razorpay-webhook-handler-readiness",
    ),
    path(
        "razorpay/webhook-events/",
        RazorpayWebhookEventsListView.as_view(),
        name="saas-razorpay-webhook-events",
    ),
    path(
        "razorpay/webhook-events/simulate/",
        RazorpayWebhookSimulateView.as_view(),
        name="saas-razorpay-webhook-events-simulate",
    ),
    path(
        "razorpay/webhook-events/<int:event_id>/",
        RazorpayWebhookEventDetailView.as_view(),
        name="saas-razorpay-webhook-event-detail",
    ),
    # Phase 6N — Razorpay Business-Mutation Sandbox Plan (planning only).
    path(
        "razorpay/business-mutation-sandbox-plan/",
        RazorpayBusinessMutationSandboxPlanView.as_view(),
        name="saas-razorpay-business-mutation-sandbox-plan",
    ),
    path(
        "razorpay/business-mutation-sandbox-readiness/",
        RazorpayBusinessMutationSandboxReadinessView.as_view(),
        name="saas-razorpay-business-mutation-sandbox-readiness",
    ),
    # Phase 6O — Razorpay Sandbox Status Mapping + Manual Review.
    path(
        "razorpay/sandbox-status-mapping-readiness/",
        RazorpaySandboxStatusMappingReadinessView.as_view(),
        name="saas-razorpay-sandbox-status-mapping-readiness",
    ),
    path(
        "razorpay/sandbox-status-reviews/",
        RazorpaySandboxStatusReviewsListView.as_view(),
        name="saas-razorpay-sandbox-status-reviews",
    ),
    path(
        "razorpay/sandbox-status-reviews/prepare/",
        RazorpaySandboxStatusReviewPrepareView.as_view(),
        name="saas-razorpay-sandbox-status-review-prepare",
    ),
    path(
        "razorpay/sandbox-status-reviews/<int:pk>/",
        RazorpaySandboxStatusReviewDetailView.as_view(),
        name="saas-razorpay-sandbox-status-review-detail",
    ),
    path(
        "razorpay/sandbox-status-reviews/<int:pk>/approve/",
        RazorpaySandboxStatusReviewApproveView.as_view(),
        name="saas-razorpay-sandbox-status-review-approve",
    ),
    path(
        "razorpay/sandbox-status-reviews/<int:pk>/reject/",
        RazorpaySandboxStatusReviewRejectView.as_view(),
        name="saas-razorpay-sandbox-status-review-reject",
    ),
    path(
        "razorpay/sandbox-status-reviews/<int:pk>/archive/",
        RazorpaySandboxStatusReviewArchiveView.as_view(),
        name="saas-razorpay-sandbox-status-review-archive",
    ),
    # Phase 6P — Razorpay Sandbox Paid-Status Mutation Test (read-only API; CLI-only execution).
    path(
        "razorpay/sandbox-paid-status-mutation-readiness/",
        RazorpaySandboxPaidStatusMutationReadinessView.as_view(),
        name="saas-razorpay-sandbox-paid-status-mutation-readiness",
    ),
    path(
        "razorpay/sandbox-paid-status-mutation-attempts/",
        RazorpaySandboxPaidStatusMutationAttemptsListView.as_view(),
        name="saas-razorpay-sandbox-paid-status-mutation-attempts",
    ),
    path(
        "razorpay/sandbox-paid-status-mutation-attempts/<int:pk>/",
        RazorpaySandboxPaidStatusMutationAttemptDetailView.as_view(),
        name="saas-razorpay-sandbox-paid-status-mutation-attempt-detail",
    ),
    path(
        "razorpay/sandbox-paid-status-mutation-preview/",
        RazorpaySandboxPaidStatusMutationPreviewView.as_view(),
        name="saas-razorpay-sandbox-paid-status-mutation-preview",
    ),
    # Phase 6Q — Razorpay Payment → Order Workflow Safety Gate (read-only API).
    path(
        "razorpay/payment-order-workflow-gate-readiness/",
        RazorpayPaymentOrderWorkflowGateReadinessView.as_view(),
        name="saas-razorpay-payment-order-workflow-gate-readiness",
    ),
    path(
        "razorpay/payment-order-workflow-gates/",
        RazorpayPaymentOrderWorkflowGatesListView.as_view(),
        name="saas-razorpay-payment-order-workflow-gates",
    ),
    path(
        "razorpay/payment-order-workflow-gates/<int:pk>/",
        RazorpayPaymentOrderWorkflowGateDetailView.as_view(),
        name="saas-razorpay-payment-order-workflow-gate-detail",
    ),
    path(
        "razorpay/payment-order-workflow-gate-preview/",
        RazorpayPaymentOrderWorkflowGatePreviewView.as_view(),
        name="saas-razorpay-payment-order-workflow-gate-preview",
    ),
    # Phase 6R — Razorpay Payment → WhatsApp / Courier Dispatch Readiness (read-only API).
    path(
        "razorpay/payment-dispatch-readiness/",
        RazorpayPaymentDispatchReadinessView.as_view(),
        name="saas-razorpay-payment-dispatch-readiness",
    ),
    path(
        "razorpay/payment-dispatch-readiness-gates/",
        RazorpayPaymentDispatchReadinessGatesListView.as_view(),
        name="saas-razorpay-payment-dispatch-readiness-gates",
    ),
    path(
        "razorpay/payment-dispatch-readiness-gates/<int:pk>/",
        RazorpayPaymentDispatchReadinessGateDetailView.as_view(),
        name="saas-razorpay-payment-dispatch-readiness-gate-detail",
    ),
    path(
        "razorpay/payment-dispatch-readiness-preview/",
        RazorpayPaymentDispatchReadinessPreviewView.as_view(),
        name="saas-razorpay-payment-dispatch-readiness-preview",
    ),
    # Phase 6S — Razorpay Limited Internal Dispatch Pilot Plan (read-only API).
    path(
        "razorpay/payment-dispatch-pilot-plan-readiness/",
        RazorpayPaymentDispatchPilotPlanReadinessView.as_view(),
        name="saas-razorpay-payment-dispatch-pilot-plan-readiness",
    ),
    path(
        "razorpay/payment-dispatch-pilot-plans/",
        RazorpayPaymentDispatchPilotPlansListView.as_view(),
        name="saas-razorpay-payment-dispatch-pilot-plans",
    ),
    path(
        "razorpay/payment-dispatch-pilot-plans/<int:pk>/",
        RazorpayPaymentDispatchPilotPlanDetailView.as_view(),
        name="saas-razorpay-payment-dispatch-pilot-plan-detail",
    ),
    path(
        "razorpay/payment-dispatch-pilot-plan-preview/",
        RazorpayPaymentDispatchPilotPlanPreviewView.as_view(),
        name="saas-razorpay-payment-dispatch-pilot-plan-preview",
    ),
    # Phase 6T - final Phase 6 audit-lock / decision gate (read-only API).
    path(
        "razorpay/phase6-final-audit-lock-readiness/",
        RazorpayPhase6FinalAuditLockReadinessView.as_view(),
        name="saas-razorpay-phase6-final-audit-lock-readiness",
    ),
    path(
        "razorpay/phase6-final-audit-locks/",
        RazorpayPhase6FinalAuditLocksListView.as_view(),
        name="saas-razorpay-phase6-final-audit-locks",
    ),
    path(
        "razorpay/phase6-final-audit-locks/<int:pk>/",
        RazorpayPhase6FinalAuditLockDetailView.as_view(),
        name="saas-razorpay-phase6-final-audit-lock-detail",
    ),
    path(
        "razorpay/phase6-final-audit-lock-preview/",
        RazorpayPhase6FinalAuditLockPreviewView.as_view(),
        name="saas-razorpay-phase6-final-audit-lock-preview",
    ),
    # Phase 7B - Razorpay Controlled Pilot Execution Gate (read-only API).
    path(
        "razorpay/controlled-pilot-gate-readiness/",
        RazorpayControlledPilotGateReadinessView.as_view(),
        name="saas-razorpay-controlled-pilot-gate-readiness",
    ),
    path(
        "razorpay/controlled-pilot-gates/",
        RazorpayControlledPilotGatesListView.as_view(),
        name="saas-razorpay-controlled-pilot-gates",
    ),
    path(
        "razorpay/controlled-pilot-gates/<int:pk>/",
        RazorpayControlledPilotGateDetailView.as_view(),
        name="saas-razorpay-controlled-pilot-gate-detail",
    ),
    path(
        "razorpay/controlled-pilot-gate-preview/",
        RazorpayControlledPilotGatePreviewView.as_view(),
        name="saas-razorpay-controlled-pilot-gate-preview",
    ),
    path(
        "razorpay/controlled-pilot-gate-dry-runs/<int:gate_id>/",
        RazorpayControlledPilotGateDryRunsView.as_view(),
        name="saas-razorpay-controlled-pilot-gate-dry-runs",
    ),
    path(
        "razorpay/controlled-pilot-gate-rollback-dry-runs/<int:gate_id>/",
        RazorpayControlledPilotGateRollbackDryRunsView.as_view(),
        name="saas-razorpay-controlled-pilot-gate-rollback-dry-runs",
    ),
    # Phase 7D - Razorpay Controlled Pilot Execution (one-shot Razorpay
    # TEST execution; CLI-only review/execution; read-only API).
    path(
        "razorpay/controlled-pilot-execution-readiness/",
        RazorpayControlledPilotExecutionReadinessView.as_view(),
        name="saas-razorpay-controlled-pilot-execution-readiness",
    ),
    path(
        "razorpay/controlled-pilot-execution-attempts/",
        RazorpayControlledPilotExecutionAttemptsListView.as_view(),
        name="saas-razorpay-controlled-pilot-execution-attempts",
    ),
    path(
        "razorpay/controlled-pilot-execution-attempts/<int:pk>/",
        RazorpayControlledPilotExecutionAttemptDetailView.as_view(),
        name="saas-razorpay-controlled-pilot-execution-attempt-detail",
    ),
    path(
        "razorpay/controlled-pilot-execution-preview/",
        RazorpayControlledPilotExecutionPreviewView.as_view(),
        name="saas-razorpay-controlled-pilot-execution-preview",
    ),
    path(
        "razorpay/controlled-pilot-execution-rollbacks/<int:attempt_id>/",
        RazorpayControlledPilotExecutionRollbacksView.as_view(),
        name="saas-razorpay-controlled-pilot-execution-rollbacks",
    ),
    # Phase 7E - WhatsApp Internal Notification Readiness Gate (gate-only,
    # CLI-only review state changes; read-only API).
    path(
        "razorpay/whatsapp-internal-notification-readiness/",
        RazorpayWhatsAppInternalNotificationReadinessView.as_view(),
        name="saas-razorpay-whatsapp-internal-notification-readiness",
    ),
    path(
        "razorpay/whatsapp-internal-notification-gates/",
        RazorpayWhatsAppInternalNotificationGatesListView.as_view(),
        name="saas-razorpay-whatsapp-internal-notification-gates",
    ),
    path(
        "razorpay/whatsapp-internal-notification-gates/<int:pk>/",
        RazorpayWhatsAppInternalNotificationGateDetailView.as_view(),
        name="saas-razorpay-whatsapp-internal-notification-gate-detail",
    ),
    path(
        "razorpay/whatsapp-internal-notification-preview/",
        RazorpayWhatsAppInternalNotificationPreviewView.as_view(),
        name="saas-razorpay-whatsapp-internal-notification-preview",
    ),
    path(
        "razorpay/whatsapp-internal-notification-dry-runs/<int:gate_id>/",
        RazorpayWhatsAppInternalNotificationDryRunsView.as_view(),
        name="saas-razorpay-whatsapp-internal-notification-dry-runs",
    ),
    # Phase 7F - Delhivery / Courier Controlled Readiness Gate
    # (gate-only, CLI-only review state changes; read-only API).
    path(
        "delhivery/courier-readiness/",
        RazorpayCourierReadinessReadinessView.as_view(),
        name="saas-delhivery-courier-readiness",
    ),
    path(
        "delhivery/courier-readiness-gates/",
        RazorpayCourierReadinessGatesListView.as_view(),
        name="saas-delhivery-courier-readiness-gates",
    ),
    path(
        "delhivery/courier-readiness-gates/<int:pk>/",
        RazorpayCourierReadinessGateDetailView.as_view(),
        name="saas-delhivery-courier-readiness-gate-detail",
    ),
    path(
        "delhivery/courier-readiness-preview/",
        RazorpayCourierReadinessPreviewView.as_view(),
        name="saas-delhivery-courier-readiness-preview",
    ),
    path(
        "delhivery/courier-readiness-dry-runs/<int:gate_id>/",
        RazorpayCourierReadinessDryRunsView.as_view(),
        name="saas-delhivery-courier-readiness-dry-runs",
    ),
    # Phase 7G - One-shot Delhivery TEST/MOCK Courier Execution Gate
    # (CLI-only execute path; read-only API).
    path(
        "delhivery/courier-execution-readiness/",
        RazorpayCourierExecutionReadinessView.as_view(),
        name="saas-delhivery-courier-execution-readiness",
    ),
    path(
        "delhivery/courier-execution-attempts/",
        RazorpayCourierExecutionAttemptsListView.as_view(),
        name="saas-delhivery-courier-execution-attempts",
    ),
    path(
        "delhivery/courier-execution-attempts/<int:pk>/",
        RazorpayCourierExecutionAttemptDetailView.as_view(),
        name="saas-delhivery-courier-execution-attempt-detail",
    ),
    path(
        "delhivery/courier-execution-preview/",
        RazorpayCourierExecutionPreviewView.as_view(),
        name="saas-delhivery-courier-execution-preview",
    ),
    path(
        "delhivery/courier-execution-rollbacks/<int:attempt_id>/",
        RazorpayCourierExecutionRollbacksView.as_view(),
        name="saas-delhivery-courier-execution-rollbacks",
    ),
    # Phase 7H - Courier Execution Evidence Lock (lock-only;
    # read-only API; CLI-only state changes).
    path(
        "delhivery/courier-execution-evidence-lock-readiness/",
        RazorpayCourierExecutionEvidenceLockReadinessView.as_view(),
        name="saas-delhivery-courier-execution-evidence-lock-readiness",
    ),
    path(
        "delhivery/courier-execution-evidence-locks/",
        RazorpayCourierExecutionEvidenceLocksListView.as_view(),
        name="saas-delhivery-courier-execution-evidence-locks",
    ),
    path(
        "delhivery/courier-execution-evidence-locks/<int:pk>/",
        RazorpayCourierExecutionEvidenceLockDetailView.as_view(),
        name="saas-delhivery-courier-execution-evidence-lock-detail",
    ),
    path(
        "delhivery/courier-execution-evidence-lock-preview/",
        RazorpayCourierExecutionEvidenceLockPreviewView.as_view(),
        name="saas-delhivery-courier-execution-evidence-lock-preview",
    ),
    # Phase 7E-Live-A - Internal Allowed-list WhatsApp One-shot Send
    # Gate (CLI-only execute; read-only API; never sends to real
    # customer; never mutates business rows).
    path(
        "whatsapp/internal-send-readiness/",
        WhatsAppInternalSendReadinessView.as_view(),
        name="saas-whatsapp-internal-send-readiness",
    ),
    path(
        "whatsapp/internal-send-attempts/",
        WhatsAppInternalSendAttemptsListView.as_view(),
        name="saas-whatsapp-internal-send-attempts",
    ),
    path(
        "whatsapp/internal-send-attempts/<int:pk>/",
        WhatsAppInternalSendAttemptDetailView.as_view(),
        name="saas-whatsapp-internal-send-attempt-detail",
    ),
    path(
        "whatsapp/internal-send-preview/",
        WhatsAppInternalSendPreviewView.as_view(),
        name="saas-whatsapp-internal-send-preview",
    ),
    # Phase 7I - Final Phase 7 Payment + WhatsApp + Courier Audit
    # Lock (lock-only; read-only API; CLI-only state changes).
    path(
        "phase7/final-audit-lock-readiness/",
        Phase7IFinalAuditLockReadinessView.as_view(),
        name="saas-phase7i-final-audit-lock-readiness",
    ),
    path(
        "phase7/final-audit-locks/",
        Phase7IFinalAuditLocksListView.as_view(),
        name="saas-phase7i-final-audit-locks",
    ),
    path(
        "phase7/final-audit-locks/<int:pk>/",
        Phase7IFinalAuditLockDetailView.as_view(),
        name="saas-phase7i-final-audit-lock-detail",
    ),
    path(
        "phase7/final-audit-lock-preview/",
        Phase7IFinalAuditLockPreviewView.as_view(),
        name="saas-phase7i-final-audit-lock-preview",
    ),
    # Phase 8A - Payment -> Order Mutation Sandbox Gate (sandbox-only;
    # read-only API; CLI-only state changes; NEVER mutates real
    # Order / Payment / Shipment / Customer / Lead rows; NEVER calls
    # Razorpay / Meta Cloud / Delhivery / Vapi).
    path(
        "phase8/payment-order-mutation-sandbox-readiness/",
        Phase8APaymentOrderMutationSandboxReadinessView.as_view(),
        name="saas-phase8a-payment-order-mutation-sandbox-readiness",
    ),
    path(
        "phase8/payment-order-mutation-sandbox-gates/",
        Phase8APaymentOrderMutationSandboxGatesListView.as_view(),
        name="saas-phase8a-payment-order-mutation-sandbox-gates",
    ),
    path(
        "phase8/payment-order-mutation-sandbox-gates/<int:pk>/",
        Phase8APaymentOrderMutationSandboxGateDetailView.as_view(),
        name="saas-phase8a-payment-order-mutation-sandbox-gate-detail",
    ),
    path(
        "phase8/payment-order-mutation-sandbox-preview/",
        Phase8APaymentOrderMutationSandboxPreviewView.as_view(),
        name="saas-phase8a-payment-order-mutation-sandbox-preview",
    ),
    path(
        "phase8/payment-order-mutation-sandbox-dry-runs/<int:gate_id>/",
        Phase8APaymentOrderMutationSandboxDryRunsView.as_view(),
        name="saas-phase8a-payment-order-mutation-sandbox-dry-runs",
    ),
    # Phase 8B - Payment -> Order Mutation Review Gate (review /
    # dry-run only; read-only API; CLI-only state changes; NEVER
    # mutates real Order / Payment / Shipment / Customer / Lead
    # rows; NEVER calls Razorpay / Meta Cloud / Delhivery / Vapi).
    path(
        "phase8/payment-order-mutation-review-readiness/",
        Phase8BPaymentOrderMutationReviewReadinessView.as_view(),
        name="saas-phase8b-payment-order-mutation-review-readiness",
    ),
    path(
        "phase8/payment-order-mutation-review-gates/",
        Phase8BPaymentOrderMutationReviewGatesListView.as_view(),
        name="saas-phase8b-payment-order-mutation-review-gates",
    ),
    path(
        "phase8/payment-order-mutation-review-gates/<int:pk>/",
        Phase8BPaymentOrderMutationReviewGateDetailView.as_view(),
        name="saas-phase8b-payment-order-mutation-review-gate-detail",
    ),
    path(
        "phase8/payment-order-mutation-review-preview/",
        Phase8BPaymentOrderMutationReviewPreviewView.as_view(),
        name="saas-phase8b-payment-order-mutation-review-preview",
    ),
    path(
        "phase8/payment-order-mutation-review-dry-runs/<int:gate_id>/",
        Phase8BPaymentOrderMutationReviewDryRunsView.as_view(),
        name="saas-phase8b-payment-order-mutation-review-dry-runs",
    ),
    # Phase 8C - Controlled Real Payment -> Order Mutation
    # (CLI-only one-shot mutation; read-only API; NEVER calls
    # Razorpay / Meta Cloud / Delhivery / Vapi; NEVER sends
    # WhatsApp; NEVER mutates Customer / Lead / Shipment /
    # DiscountOfferLog rows).
    path(
        "phase8/payment-order-controlled-mutation-readiness/",
        Phase8CPaymentOrderControlledMutationReadinessView.as_view(),
        name="saas-phase8c-payment-order-controlled-mutation-readiness",
    ),
    path(
        "phase8/payment-order-controlled-mutation-gates/",
        Phase8CPaymentOrderControlledMutationGatesListView.as_view(),
        name="saas-phase8c-payment-order-controlled-mutation-gates",
    ),
    path(
        "phase8/payment-order-controlled-mutation-gates/<int:pk>/",
        Phase8CPaymentOrderControlledMutationGateDetailView.as_view(),
        name=(
            "saas-phase8c-payment-order-controlled-mutation-gate-detail"
        ),
    ),
    path(
        "phase8/payment-order-controlled-mutation-preview/",
        Phase8CPaymentOrderControlledMutationPreviewView.as_view(),
        name="saas-phase8c-payment-order-controlled-mutation-preview",
    ),
    path(
        "phase8/payment-order-controlled-mutation-attempts/<int:gate_id>/",
        Phase8CPaymentOrderControlledMutationAttemptsView.as_view(),
        name=(
            "saas-phase8c-payment-order-controlled-mutation-attempts"
        ),
    ),
    path(
        "phase8/payment-order-controlled-mutation-rollbacks/<int:attempt_id>/",
        Phase8CPaymentOrderControlledMutationRollbacksView.as_view(),
        name=(
            "saas-phase8c-payment-order-controlled-mutation-rollbacks"
        ),
    ),
    # Phase 8D - Phase 8C Controlled Mutation Evidence Lock
    # (lock-only meta-audit; read-only API; CLI-only state changes;
    # NEVER executes Phase 8C again; NEVER calls Razorpay / Meta
    # Cloud / Delhivery / Vapi; NEVER sends WhatsApp; NEVER mutates
    # business rows).
    path(
        "phase8/controlled-mutation-evidence-lock-readiness/",
        Phase8DControlledMutationEvidenceLockReadinessView.as_view(),
        name="saas-phase8d-controlled-mutation-evidence-lock-readiness",
    ),
    path(
        "phase8/controlled-mutation-evidence-locks/",
        Phase8DControlledMutationEvidenceLocksListView.as_view(),
        name="saas-phase8d-controlled-mutation-evidence-locks",
    ),
    path(
        "phase8/controlled-mutation-evidence-locks/<int:pk>/",
        Phase8DControlledMutationEvidenceLockDetailView.as_view(),
        name=(
            "saas-phase8d-controlled-mutation-evidence-lock-detail"
        ),
    ),
    path(
        "phase8/controlled-mutation-evidence-lock-preview/",
        Phase8DControlledMutationEvidenceLockPreviewView.as_view(),
        name=(
            "saas-phase8d-controlled-mutation-evidence-lock-preview"
        ),
    ),
    # Phase 8E - Real Customer Payment -> Order Mutation Pilot
    # Gate (review / dry-run only against ONE real customer Order
    # + Payment candidate; read-only API; CLI-only state changes;
    # NEVER mutates real Order / Payment / Customer / Lead /
    # Shipment / DiscountOfferLog / WhatsAppMessage rows; NEVER
    # calls Razorpay / Meta Cloud / Delhivery / Vapi).
    path(
        "phase8/real-customer-payment-order-pilot-readiness/",
        Phase8ERealCustomerPaymentOrderPilotReadinessView.as_view(),
        name="saas-phase8e-real-customer-payment-order-pilot-readiness",
    ),
    path(
        "phase8/real-customer-payment-order-pilot-gates/",
        Phase8ERealCustomerPaymentOrderPilotGatesListView.as_view(),
        name="saas-phase8e-real-customer-payment-order-pilot-gates",
    ),
    path(
        "phase8/real-customer-payment-order-pilot-gates/<int:pk>/",
        Phase8ERealCustomerPaymentOrderPilotGateDetailView.as_view(),
        name=(
            "saas-phase8e-real-customer-payment-order-pilot-gate-detail"
        ),
    ),
    path(
        "phase8/real-customer-payment-order-pilot-preview/",
        Phase8ERealCustomerPaymentOrderPilotPreviewView.as_view(),
        name=(
            "saas-phase8e-real-customer-payment-order-pilot-preview"
        ),
    ),
    path(
        "phase8/real-customer-payment-order-pilot-candidates/<int:gate_id>/",
        Phase8ERealCustomerPaymentOrderPilotCandidatesView.as_view(),
        name=(
            "saas-phase8e-real-customer-payment-order-pilot-candidates"
        ),
    ),
    path(
        "phase8/real-customer-payment-order-pilot-dry-runs/<int:gate_id>/",
        Phase8ERealCustomerPaymentOrderPilotDryRunsView.as_view(),
        name=(
            "saas-phase8e-real-customer-payment-order-pilot-dry-runs"
        ),
    ),
]
