from __future__ import annotations

from django.urls import path

from .views import (
    AiProviderRoutingView,
    ControlledRuntimeReadinessView,
    CurrentOrganizationView,
    DataCoverageView,
    FeatureFlagsView,
    MyOrganizationsView,
    OrgScopeReadinessView,
    ProviderExecutionAttemptArchiveView,
    ProviderExecutionAttemptDetailView,
    ProviderExecutionAttemptPrepareView,
    ProviderExecutionAttemptRollbackView,
    ProviderExecutionAttemptsListView,
    ProviderTestPlanApproveView,
    ProviderTestPlanArchiveView,
    ProviderTestPlanDetailView,
    ProviderTestPlanPrepareView,
    ProviderTestPlanRejectView,
    ProviderTestPlanValidateView,
    ProviderTestPlansListView,
    RazorpayBusinessMutationSandboxPlanView,
    RazorpayBusinessMutationSandboxReadinessView,
    RazorpayPaymentDispatchPilotPlanDetailView,
    RazorpayPaymentDispatchPilotPlanPreviewView,
    RazorpayPaymentDispatchPilotPlanReadinessView,
    RazorpayPaymentDispatchPilotPlansListView,
    RazorpayPhase6FinalAuditLockDetailView,
    RazorpayPhase6FinalAuditLockPreviewView,
    RazorpayPhase6FinalAuditLockReadinessView,
    RazorpayPhase6FinalAuditLocksListView,
    RazorpayPaymentDispatchReadinessGateDetailView,
    RazorpayPaymentDispatchReadinessGatesListView,
    RazorpayPaymentDispatchReadinessPreviewView,
    RazorpayPaymentDispatchReadinessView,
    RazorpayPaymentOrderWorkflowGateDetailView,
    RazorpayPaymentOrderWorkflowGatePreviewView,
    RazorpayPaymentOrderWorkflowGateReadinessView,
    RazorpayPaymentOrderWorkflowGatesListView,
    RazorpaySandboxPaidStatusMutationAttemptDetailView,
    RazorpaySandboxPaidStatusMutationAttemptsListView,
    RazorpaySandboxPaidStatusMutationPreviewView,
    RazorpaySandboxPaidStatusMutationReadinessView,
    RazorpaySandboxStatusMappingReadinessView,
    RazorpaySandboxStatusReviewApproveView,
    RazorpaySandboxStatusReviewArchiveView,
    RazorpaySandboxStatusReviewDetailView,
    RazorpaySandboxStatusReviewPrepareView,
    RazorpaySandboxStatusReviewRejectView,
    RazorpaySandboxStatusReviewsListView,
    RazorpayExecutionAuditReviewView,
    RazorpayWebhookEventDetailView,
    RazorpayWebhookEventsListView,
    RazorpayWebhookHandlerReadinessView,
    RazorpayWebhookPlanView,
    RazorpayWebhookReadinessView,
    RazorpayWebhookSimulateView,
    RuntimeDryRunView,
    RuntimeLiveGateApproveView,
    RuntimeLiveGateKillSwitchView,
    RuntimeLiveGatePoliciesView,
    RuntimeLiveGatePreviewView,
    RuntimeLiveGateRejectView,
    RuntimeLiveGateSimulationApproveView,
    RuntimeLiveGateSimulationDetailView,
    RuntimeLiveGateSimulationPrepareView,
    RuntimeLiveGateSimulationRejectView,
    RuntimeLiveGateSimulationRequestApprovalView,
    RuntimeLiveGateSimulationRollbackView,
    RuntimeLiveGateSimulationRunView,
    RuntimeLiveGateSimulationsView,
    RuntimeLiveGateRequestsView,
    RuntimeLiveGateView,
    RuntimeRoutingReadinessView,
    SaasAdminOrganizationDetailView,
    SaasAdminOrganizationsView,
    SaasAdminOverviewView,
    SaasIntegrationReadinessView,
    SaasIntegrationSettingDetailView,
    SaasIntegrationSettingsView,
    WritePathReadinessView,
)


urlpatterns = [
    path(
        "current-organization/",
        CurrentOrganizationView.as_view(),
        name="saas-current-organization",
    ),
    path(
        "my-organizations/",
        MyOrganizationsView.as_view(),
        name="saas-my-organizations",
    ),
    path(
        "feature-flags/",
        FeatureFlagsView.as_view(),
        name="saas-feature-flags",
    ),
    path(
        "data-coverage/",
        DataCoverageView.as_view(),
        name="saas-data-coverage",
    ),
    path(
        "org-scope-readiness/",
        OrgScopeReadinessView.as_view(),
        name="saas-org-scope-readiness",
    ),
    path(
        "write-path-readiness/",
        WritePathReadinessView.as_view(),
        name="saas-write-path-readiness",
    ),
    path(
        "admin/overview/",
        SaasAdminOverviewView.as_view(),
        name="saas-admin-overview",
    ),
    path(
        "admin/organizations/",
        SaasAdminOrganizationsView.as_view(),
        name="saas-admin-organizations",
    ),
    path(
        "admin/organizations/<int:organization_id>/",
        SaasAdminOrganizationDetailView.as_view(),
        name="saas-admin-organization-detail",
    ),
    path(
        "admin/integration-settings/",
        SaasIntegrationSettingsView.as_view(),
        name="saas-admin-integration-settings",
    ),
    path(
        "admin/integration-settings/<int:setting_id>/",
        SaasIntegrationSettingDetailView.as_view(),
        name="saas-admin-integration-setting-detail",
    ),
    path(
        "admin/integration-readiness/",
        SaasIntegrationReadinessView.as_view(),
        name="saas-admin-integration-readiness",
    ),
    path(
        "runtime-routing-readiness/",
        RuntimeRoutingReadinessView.as_view(),
        name="saas-runtime-routing-readiness",
    ),
    path(
        "runtime-dry-run/",
        RuntimeDryRunView.as_view(),
        name="saas-runtime-dry-run",
    ),
    path(
        "ai-provider-routing/",
        AiProviderRoutingView.as_view(),
        name="saas-ai-provider-routing",
    ),
    path(
        "controlled-runtime-readiness/",
        ControlledRuntimeReadinessView.as_view(),
        name="saas-controlled-runtime-readiness",
    ),
    path(
        "runtime-live-gate/",
        RuntimeLiveGateView.as_view(),
        name="saas-runtime-live-gate",
    ),
    path(
        "runtime-live-gate/requests/",
        RuntimeLiveGateRequestsView.as_view(),
        name="saas-runtime-live-gate-requests",
    ),
    path(
        "runtime-live-gate/policies/",
        RuntimeLiveGatePoliciesView.as_view(),
        name="saas-runtime-live-gate-policies",
    ),
    path(
        "runtime-live-gate/kill-switch/",
        RuntimeLiveGateKillSwitchView.as_view(),
        name="saas-runtime-live-gate-kill-switch",
    ),
    path(
        "runtime-live-gate/preview/",
        RuntimeLiveGatePreviewView.as_view(),
        name="saas-runtime-live-gate-preview",
    ),
    path(
        "runtime-live-gate/requests/<int:request_id>/approve/",
        RuntimeLiveGateApproveView.as_view(),
        name="saas-runtime-live-gate-request-approve",
    ),
    path(
        "runtime-live-gate/requests/<int:request_id>/reject/",
        RuntimeLiveGateRejectView.as_view(),
        name="saas-runtime-live-gate-request-reject",
    ),
    path(
        "runtime-live-gate/simulations/",
        RuntimeLiveGateSimulationsView.as_view(),
        name="saas-runtime-live-gate-simulations",
    ),
    path(
        "runtime-live-gate/simulations/<int:simulation_id>/",
        RuntimeLiveGateSimulationDetailView.as_view(),
        name="saas-runtime-live-gate-simulation-detail",
    ),
    path(
        "runtime-live-gate/simulations/prepare/",
        RuntimeLiveGateSimulationPrepareView.as_view(),
        name="saas-runtime-live-gate-simulation-prepare",
    ),
    path(
        "runtime-live-gate/simulations/<int:simulation_id>/request-approval/",
        RuntimeLiveGateSimulationRequestApprovalView.as_view(),
        name="saas-runtime-live-gate-simulation-request-approval",
    ),
    path(
        "runtime-live-gate/simulations/<int:simulation_id>/approve/",
        RuntimeLiveGateSimulationApproveView.as_view(),
        name="saas-runtime-live-gate-simulation-approve",
    ),
    path(
        "runtime-live-gate/simulations/<int:simulation_id>/reject/",
        RuntimeLiveGateSimulationRejectView.as_view(),
        name="saas-runtime-live-gate-simulation-reject",
    ),
    path(
        "runtime-live-gate/simulations/<int:simulation_id>/run/",
        RuntimeLiveGateSimulationRunView.as_view(),
        name="saas-runtime-live-gate-simulation-run",
    ),
    path(
        "runtime-live-gate/simulations/<int:simulation_id>/rollback/",
        RuntimeLiveGateSimulationRollbackView.as_view(),
        name="saas-runtime-live-gate-simulation-rollback",
    ),
    # Phase 6J — Single Internal Provider Test Plan.
    path(
        "provider-test-plans/",
        ProviderTestPlansListView.as_view(),
        name="saas-provider-test-plans",
    ),
    path(
        "provider-test-plans/prepare/",
        ProviderTestPlanPrepareView.as_view(),
        name="saas-provider-test-plans-prepare",
    ),
    path(
        "provider-test-plans/<str:plan_id>/",
        ProviderTestPlanDetailView.as_view(),
        name="saas-provider-test-plan-detail",
    ),
    path(
        "provider-test-plans/<str:plan_id>/validate/",
        ProviderTestPlanValidateView.as_view(),
        name="saas-provider-test-plan-validate",
    ),
    path(
        "provider-test-plans/<str:plan_id>/approve/",
        ProviderTestPlanApproveView.as_view(),
        name="saas-provider-test-plan-approve",
    ),
    path(
        "provider-test-plans/<str:plan_id>/reject/",
        ProviderTestPlanRejectView.as_view(),
        name="saas-provider-test-plan-reject",
    ),
    path(
        "provider-test-plans/<str:plan_id>/archive/",
        ProviderTestPlanArchiveView.as_view(),
        name="saas-provider-test-plan-archive",
    ),
    # Phase 6K — Single Internal Razorpay Test-Mode Execution Gate.
    path(
        "provider-execution-attempts/",
        ProviderExecutionAttemptsListView.as_view(),
        name="saas-provider-execution-attempts",
    ),
    path(
        "provider-execution-attempts/prepare/",
        ProviderExecutionAttemptPrepareView.as_view(),
        name="saas-provider-execution-attempts-prepare",
    ),
    path(
        "provider-execution-attempts/<str:execution_id>/",
        ProviderExecutionAttemptDetailView.as_view(),
        name="saas-provider-execution-attempt-detail",
    ),
    path(
        "provider-execution-attempts/<str:execution_id>/rollback/",
        ProviderExecutionAttemptRollbackView.as_view(),
        name="saas-provider-execution-attempt-rollback",
    ),
    path(
        "provider-execution-attempts/<str:execution_id>/archive/",
        ProviderExecutionAttemptArchiveView.as_view(),
        name="saas-provider-execution-attempt-archive",
    ),
    # Phase 6L — Razorpay Test Execution Audit Review + Webhook Readiness Plan.
    path(
        "razorpay/execution-audit/",
        RazorpayExecutionAuditReviewView.as_view(),
        name="saas-razorpay-execution-audit",
    ),
    path(
        "razorpay/webhook-readiness/",
        RazorpayWebhookReadinessView.as_view(),
        name="saas-razorpay-webhook-readiness",
    ),
    path(
        "razorpay/webhook-plan/",
        RazorpayWebhookPlanView.as_view(),
        name="saas-razorpay-webhook-plan",
    ),
    # Phase 6M — test-mode handler readiness + event browser + simulator.
    path(
        "razorpay/webhook-handler-readiness/",
        RazorpayWebhookHandlerReadinessView.as_view(),
        name="saas-razorpay-webhook-handler-readiness",
    ),
    path(
        "razorpay/webhook-events/",
        RazorpayWebhookEventsListView.as_view(),
        name="saas-razorpay-webhook-events",
    ),
    path(
        "razorpay/webhook-events/simulate/",
        RazorpayWebhookSimulateView.as_view(),
        name="saas-razorpay-webhook-events-simulate",
    ),
    path(
        "razorpay/webhook-events/<int:event_id>/",
        RazorpayWebhookEventDetailView.as_view(),
        name="saas-razorpay-webhook-event-detail",
    ),
    # Phase 6N — Razorpay Business-Mutation Sandbox Plan (planning only).
    path(
        "razorpay/business-mutation-sandbox-plan/",
        RazorpayBusinessMutationSandboxPlanView.as_view(),
        name="saas-razorpay-business-mutation-sandbox-plan",
    ),
    path(
        "razorpay/business-mutation-sandbox-readiness/",
        RazorpayBusinessMutationSandboxReadinessView.as_view(),
        name="saas-razorpay-business-mutation-sandbox-readiness",
    ),
    # Phase 6O — Razorpay Sandbox Status Mapping + Manual Review.
    path(
        "razorpay/sandbox-status-mapping-readiness/",
        RazorpaySandboxStatusMappingReadinessView.as_view(),
        name="saas-razorpay-sandbox-status-mapping-readiness",
    ),
    path(
        "razorpay/sandbox-status-reviews/",
        RazorpaySandboxStatusReviewsListView.as_view(),
        name="saas-razorpay-sandbox-status-reviews",
    ),
    path(
        "razorpay/sandbox-status-reviews/prepare/",
        RazorpaySandboxStatusReviewPrepareView.as_view(),
        name="saas-razorpay-sandbox-status-review-prepare",
    ),
    path(
        "razorpay/sandbox-status-reviews/<int:pk>/",
        RazorpaySandboxStatusReviewDetailView.as_view(),
        name="saas-razorpay-sandbox-status-review-detail",
    ),
    path(
        "razorpay/sandbox-status-reviews/<int:pk>/approve/",
        RazorpaySandboxStatusReviewApproveView.as_view(),
        name="saas-razorpay-sandbox-status-review-approve",
    ),
    path(
        "razorpay/sandbox-status-reviews/<int:pk>/reject/",
        RazorpaySandboxStatusReviewRejectView.as_view(),
        name="saas-razorpay-sandbox-status-review-reject",
    ),
    path(
        "razorpay/sandbox-status-reviews/<int:pk>/archive/",
        RazorpaySandboxStatusReviewArchiveView.as_view(),
        name="saas-razorpay-sandbox-status-review-archive",
    ),
    # Phase 6P — Razorpay Sandbox Paid-Status Mutation Test (read-only API; CLI-only execution).
    path(
        "razorpay/sandbox-paid-status-mutation-readiness/",
        RazorpaySandboxPaidStatusMutationReadinessView.as_view(),
        name="saas-razorpay-sandbox-paid-status-mutation-readiness",
    ),
    path(
        "razorpay/sandbox-paid-status-mutation-attempts/",
        RazorpaySandboxPaidStatusMutationAttemptsListView.as_view(),
        name="saas-razorpay-sandbox-paid-status-mutation-attempts",
    ),
    path(
        "razorpay/sandbox-paid-status-mutation-attempts/<int:pk>/",
        RazorpaySandboxPaidStatusMutationAttemptDetailView.as_view(),
        name="saas-razorpay-sandbox-paid-status-mutation-attempt-detail",
    ),
    path(
        "razorpay/sandbox-paid-status-mutation-preview/",
        RazorpaySandboxPaidStatusMutationPreviewView.as_view(),
        name="saas-razorpay-sandbox-paid-status-mutation-preview",
    ),
    # Phase 6Q — Razorpay Payment → Order Workflow Safety Gate (read-only API).
    path(
        "razorpay/payment-order-workflow-gate-readiness/",
        RazorpayPaymentOrderWorkflowGateReadinessView.as_view(),
        name="saas-razorpay-payment-order-workflow-gate-readiness",
    ),
    path(
        "razorpay/payment-order-workflow-gates/",
        RazorpayPaymentOrderWorkflowGatesListView.as_view(),
        name="saas-razorpay-payment-order-workflow-gates",
    ),
    path(
        "razorpay/payment-order-workflow-gates/<int:pk>/",
        RazorpayPaymentOrderWorkflowGateDetailView.as_view(),
        name="saas-razorpay-payment-order-workflow-gate-detail",
    ),
    path(
        "razorpay/payment-order-workflow-gate-preview/",
        RazorpayPaymentOrderWorkflowGatePreviewView.as_view(),
        name="saas-razorpay-payment-order-workflow-gate-preview",
    ),
    # Phase 6R — Razorpay Payment → WhatsApp / Courier Dispatch Readiness (read-only API).
    path(
        "razorpay/payment-dispatch-readiness/",
        RazorpayPaymentDispatchReadinessView.as_view(),
        name="saas-razorpay-payment-dispatch-readiness",
    ),
    path(
        "razorpay/payment-dispatch-readiness-gates/",
        RazorpayPaymentDispatchReadinessGatesListView.as_view(),
        name="saas-razorpay-payment-dispatch-readiness-gates",
    ),
    path(
        "razorpay/payment-dispatch-readiness-gates/<int:pk>/",
        RazorpayPaymentDispatchReadinessGateDetailView.as_view(),
        name="saas-razorpay-payment-dispatch-readiness-gate-detail",
    ),
    path(
        "razorpay/payment-dispatch-readiness-preview/",
        RazorpayPaymentDispatchReadinessPreviewView.as_view(),
        name="saas-razorpay-payment-dispatch-readiness-preview",
    ),
    # Phase 6S — Razorpay Limited Internal Dispatch Pilot Plan (read-only API).
    path(
        "razorpay/payment-dispatch-pilot-plan-readiness/",
        RazorpayPaymentDispatchPilotPlanReadinessView.as_view(),
        name="saas-razorpay-payment-dispatch-pilot-plan-readiness",
    ),
    path(
        "razorpay/payment-dispatch-pilot-plans/",
        RazorpayPaymentDispatchPilotPlansListView.as_view(),
        name="saas-razorpay-payment-dispatch-pilot-plans",
    ),
    path(
        "razorpay/payment-dispatch-pilot-plans/<int:pk>/",
        RazorpayPaymentDispatchPilotPlanDetailView.as_view(),
        name="saas-razorpay-payment-dispatch-pilot-plan-detail",
    ),
    path(
        "razorpay/payment-dispatch-pilot-plan-preview/",
        RazorpayPaymentDispatchPilotPlanPreviewView.as_view(),
        name="saas-razorpay-payment-dispatch-pilot-plan-preview",
    ),
    # Phase 6T - final Phase 6 audit-lock / decision gate (read-only API).
    path(
        "razorpay/phase6-final-audit-lock-readiness/",
        RazorpayPhase6FinalAuditLockReadinessView.as_view(),
        name="saas-razorpay-phase6-final-audit-lock-readiness",
    ),
    path(
        "razorpay/phase6-final-audit-locks/",
        RazorpayPhase6FinalAuditLocksListView.as_view(),
        name="saas-razorpay-phase6-final-audit-locks",
    ),
    path(
        "razorpay/phase6-final-audit-locks/<int:pk>/",
        RazorpayPhase6FinalAuditLockDetailView.as_view(),
        name="saas-razorpay-phase6-final-audit-lock-detail",
    ),
    path(
        "razorpay/phase6-final-audit-lock-preview/",
        RazorpayPhase6FinalAuditLockPreviewView.as_view(),
        name="saas-razorpay-phase6-final-audit-lock-preview",
    ),
]
