from __future__ import annotations

from django.urls import path

from .views import (
    AiProviderRoutingView,
    ControlledRuntimeReadinessView,
    CurrentOrganizationView,
    DataCoverageView,
    FeatureFlagsView,
    MyOrganizationsView,
    OrgScopeReadinessView,
    ProviderTestPlanApproveView,
    ProviderTestPlanArchiveView,
    ProviderTestPlanDetailView,
    ProviderTestPlanPrepareView,
    ProviderTestPlanRejectView,
    ProviderTestPlanValidateView,
    ProviderTestPlansListView,
    RuntimeDryRunView,
    RuntimeLiveGateApproveView,
    RuntimeLiveGateKillSwitchView,
    RuntimeLiveGatePoliciesView,
    RuntimeLiveGatePreviewView,
    RuntimeLiveGateRejectView,
    RuntimeLiveGateSimulationApproveView,
    RuntimeLiveGateSimulationDetailView,
    RuntimeLiveGateSimulationPrepareView,
    RuntimeLiveGateSimulationRejectView,
    RuntimeLiveGateSimulationRequestApprovalView,
    RuntimeLiveGateSimulationRollbackView,
    RuntimeLiveGateSimulationRunView,
    RuntimeLiveGateSimulationsView,
    RuntimeLiveGateRequestsView,
    RuntimeLiveGateView,
    RuntimeRoutingReadinessView,
    SaasAdminOrganizationDetailView,
    SaasAdminOrganizationsView,
    SaasAdminOverviewView,
    SaasIntegrationReadinessView,
    SaasIntegrationSettingDetailView,
    SaasIntegrationSettingsView,
    WritePathReadinessView,
)


urlpatterns = [
    path(
        "current-organization/",
        CurrentOrganizationView.as_view(),
        name="saas-current-organization",
    ),
    path(
        "my-organizations/",
        MyOrganizationsView.as_view(),
        name="saas-my-organizations",
    ),
    path(
        "feature-flags/",
        FeatureFlagsView.as_view(),
        name="saas-feature-flags",
    ),
    path(
        "data-coverage/",
        DataCoverageView.as_view(),
        name="saas-data-coverage",
    ),
    path(
        "org-scope-readiness/",
        OrgScopeReadinessView.as_view(),
        name="saas-org-scope-readiness",
    ),
    path(
        "write-path-readiness/",
        WritePathReadinessView.as_view(),
        name="saas-write-path-readiness",
    ),
    path(
        "admin/overview/",
        SaasAdminOverviewView.as_view(),
        name="saas-admin-overview",
    ),
    path(
        "admin/organizations/",
        SaasAdminOrganizationsView.as_view(),
        name="saas-admin-organizations",
    ),
    path(
        "admin/organizations/<int:organization_id>/",
        SaasAdminOrganizationDetailView.as_view(),
        name="saas-admin-organization-detail",
    ),
    path(
        "admin/integration-settings/",
        SaasIntegrationSettingsView.as_view(),
        name="saas-admin-integration-settings",
    ),
    path(
        "admin/integration-settings/<int:setting_id>/",
        SaasIntegrationSettingDetailView.as_view(),
        name="saas-admin-integration-setting-detail",
    ),
    path(
        "admin/integration-readiness/",
        SaasIntegrationReadinessView.as_view(),
        name="saas-admin-integration-readiness",
    ),
    path(
        "runtime-routing-readiness/",
        RuntimeRoutingReadinessView.as_view(),
        name="saas-runtime-routing-readiness",
    ),
    path(
        "runtime-dry-run/",
        RuntimeDryRunView.as_view(),
        name="saas-runtime-dry-run",
    ),
    path(
        "ai-provider-routing/",
        AiProviderRoutingView.as_view(),
        name="saas-ai-provider-routing",
    ),
    path(
        "controlled-runtime-readiness/",
        ControlledRuntimeReadinessView.as_view(),
        name="saas-controlled-runtime-readiness",
    ),
    path(
        "runtime-live-gate/",
        RuntimeLiveGateView.as_view(),
        name="saas-runtime-live-gate",
    ),
    path(
        "runtime-live-gate/requests/",
        RuntimeLiveGateRequestsView.as_view(),
        name="saas-runtime-live-gate-requests",
    ),
    path(
        "runtime-live-gate/policies/",
        RuntimeLiveGatePoliciesView.as_view(),
        name="saas-runtime-live-gate-policies",
    ),
    path(
        "runtime-live-gate/kill-switch/",
        RuntimeLiveGateKillSwitchView.as_view(),
        name="saas-runtime-live-gate-kill-switch",
    ),
    path(
        "runtime-live-gate/preview/",
        RuntimeLiveGatePreviewView.as_view(),
        name="saas-runtime-live-gate-preview",
    ),
    path(
        "runtime-live-gate/requests/<int:request_id>/approve/",
        RuntimeLiveGateApproveView.as_view(),
        name="saas-runtime-live-gate-request-approve",
    ),
    path(
        "runtime-live-gate/requests/<int:request_id>/reject/",
        RuntimeLiveGateRejectView.as_view(),
        name="saas-runtime-live-gate-request-reject",
    ),
    path(
        "runtime-live-gate/simulations/",
        RuntimeLiveGateSimulationsView.as_view(),
        name="saas-runtime-live-gate-simulations",
    ),
    path(
        "runtime-live-gate/simulations/<int:simulation_id>/",
        RuntimeLiveGateSimulationDetailView.as_view(),
        name="saas-runtime-live-gate-simulation-detail",
    ),
    path(
        "runtime-live-gate/simulations/prepare/",
        RuntimeLiveGateSimulationPrepareView.as_view(),
        name="saas-runtime-live-gate-simulation-prepare",
    ),
    path(
        "runtime-live-gate/simulations/<int:simulation_id>/request-approval/",
        RuntimeLiveGateSimulationRequestApprovalView.as_view(),
        name="saas-runtime-live-gate-simulation-request-approval",
    ),
    path(
        "runtime-live-gate/simulations/<int:simulation_id>/approve/",
        RuntimeLiveGateSimulationApproveView.as_view(),
        name="saas-runtime-live-gate-simulation-approve",
    ),
    path(
        "runtime-live-gate/simulations/<int:simulation_id>/reject/",
        RuntimeLiveGateSimulationRejectView.as_view(),
        name="saas-runtime-live-gate-simulation-reject",
    ),
    path(
        "runtime-live-gate/simulations/<int:simulation_id>/run/",
        RuntimeLiveGateSimulationRunView.as_view(),
        name="saas-runtime-live-gate-simulation-run",
    ),
    path(
        "runtime-live-gate/simulations/<int:simulation_id>/rollback/",
        RuntimeLiveGateSimulationRollbackView.as_view(),
        name="saas-runtime-live-gate-simulation-rollback",
    ),
    # Phase 6J — Single Internal Provider Test Plan.
    path(
        "provider-test-plans/",
        ProviderTestPlansListView.as_view(),
        name="saas-provider-test-plans",
    ),
    path(
        "provider-test-plans/prepare/",
        ProviderTestPlanPrepareView.as_view(),
        name="saas-provider-test-plans-prepare",
    ),
    path(
        "provider-test-plans/<str:plan_id>/",
        ProviderTestPlanDetailView.as_view(),
        name="saas-provider-test-plan-detail",
    ),
    path(
        "provider-test-plans/<str:plan_id>/validate/",
        ProviderTestPlanValidateView.as_view(),
        name="saas-provider-test-plan-validate",
    ),
    path(
        "provider-test-plans/<str:plan_id>/approve/",
        ProviderTestPlanApproveView.as_view(),
        name="saas-provider-test-plan-approve",
    ),
    path(
        "provider-test-plans/<str:plan_id>/reject/",
        ProviderTestPlanRejectView.as_view(),
        name="saas-provider-test-plan-reject",
    ),
    path(
        "provider-test-plans/<str:plan_id>/archive/",
        ProviderTestPlanArchiveView.as_view(),
        name="saas-provider-test-plan-archive",
    ),
]
