# Generated by Django 5.1.15 on 2026-04-28 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_governance", "0006_phase4d_approval_execution_log"),
        ("crm", "0002_phase2e_meta_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppConnection",
            fields=[
                (
                    "id",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("mock", "mock"),
                            ("meta_cloud", "meta_cloud"),
                            ("baileys_dev", "baileys_dev"),
                        ],
                        default="mock",
                        max_length=16,
                    ),
                ),
                ("display_name", models.CharField(default="", max_length=120)),
                (
                    "phone_number",
                    models.CharField(db_index=True, default="", max_length=24),
                ),
                (
                    "phone_number_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "business_account_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connected", "connected"),
                            ("disconnected", "disconnected"),
                            ("error", "error"),
                        ],
                        default="disconnected",
                        max_length=16,
                    ),
                ),
                ("last_connected_at", models.DateTimeField(blank=True, null=True)),
                ("last_health_check_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-updated_at",),
                "indexes": [
                    models.Index(
                        fields=["provider", "status"],
                        name="whatsapp_wh_provide_eaf7ec_idx",
                    ),
                    models.Index(
                        fields=["phone_number"], name="whatsapp_wh_phone_n_b941e2_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("phone_number_id", ""), _negated=True),
                        fields=("phone_number_id",),
                        name="uniq_whatsapp_connection_phone_number_id",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppConversation",
            fields=[
                (
                    "id",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("pending", "pending"),
                            ("resolved", "resolved"),
                            ("escalated_to_human", "escalated_to_human"),
                        ],
                        default="open",
                        max_length=24,
                    ),
                ),
                (
                    "ai_status",
                    models.CharField(
                        choices=[
                            ("disabled", "disabled"),
                            ("suggest", "suggest"),
                            ("pending_approval", "pending_approval"),
                            ("auto_after_approval", "auto_after_approval"),
                        ],
                        default="disabled",
                        max_length=24,
                    ),
                ),
                ("unread_count", models.IntegerField(default=0)),
                (
                    "last_message_text",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("last_inbound_at", models.DateTimeField(blank=True, null=True)),
                ("subject", models.CharField(blank=True, default="", max_length=240)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whatsapp_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversations",
                        to="whatsapp.whatsappconnection",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="whatsapp_conversations",
                        to="crm.customer",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                (
                    "id",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                (
                    "provider_message_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "inbound"), ("outbound", "outbound")],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("sent", "sent"),
                            ("delivered", "delivered"),
                            ("read", "read"),
                            ("failed", "failed"),
                        ],
                        default="queued",
                        max_length=12,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "text"),
                            ("template", "template"),
                            ("image", "image"),
                            ("document", "document"),
                            ("audio", "audio"),
                            ("location", "location"),
                            ("interactive", "interactive"),
                            ("system", "system"),
                        ],
                        default="template",
                        max_length=16,
                    ),
                ),
                ("body", models.TextField(blank=True, default="")),
                ("template_variables", models.JSONField(blank=True, default=dict)),
                ("media_url", models.URLField(blank=True, default="")),
                ("ai_generated", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, default="")),
                ("error_code", models.CharField(blank=True, default="", max_length=24)),
                ("attempt_count", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whatsapp_messages",
                        to="ai_governance.approvalrequest",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="whatsapp.whatsappconversation",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="whatsapp_messages",
                        to="crm.customer",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessageAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_url", models.URLField(blank=True, default="")),
                ("mime_type", models.CharField(blank=True, default="", max_length=80)),
                ("size_bytes", models.IntegerField(default=0)),
                ("media_id", models.CharField(blank=True, default="", max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="whatsapp.whatsappmessage",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessageStatusEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("sent", "sent"),
                            ("delivered", "delivered"),
                            ("read", "read"),
                            ("failed", "failed"),
                        ],
                        max_length=12,
                    ),
                ),
                ("event_at", models.DateTimeField()),
                ("provider_event_id", models.CharField(max_length=128, unique=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_events",
                        to="whatsapp.whatsappmessage",
                    ),
                ),
            ],
            options={
                "ordering": ("-received_at",),
            },
        ),
        migrations.CreateModel(
            name="WhatsAppSendLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt", models.IntegerField(default=1)),
                ("provider", models.CharField(max_length=16)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_status", models.IntegerField(default=0)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("latency_ms", models.IntegerField(default=0)),
                ("error_code", models.CharField(blank=True, default="", max_length=32)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="send_logs",
                        to="whatsapp.whatsappmessage",
                    ),
                ),
            ],
            options={
                "ordering": ("-completed_at",),
            },
        ),
        migrations.CreateModel(
            name="WhatsAppTemplate",
            fields=[
                (
                    "id",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=120)),
                ("language", models.CharField(default="hi", max_length=12)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("AUTHENTICATION", "AUTHENTICATION"),
                            ("MARKETING", "MARKETING"),
                            ("UTILITY", "UTILITY"),
                        ],
                        default="UTILITY",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("APPROVED", "APPROVED"),
                            ("REJECTED", "REJECTED"),
                            ("DISABLED", "DISABLED"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("body_components", models.JSONField(blank=True, default=list)),
                ("variables_schema", models.JSONField(blank=True, default=dict)),
                (
                    "action_key",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("claim_vault_required", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="whatsapp.whatsappconnection",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="messages",
                to="whatsapp.whatsapptemplate",
            ),
        ),
        migrations.CreateModel(
            name="WhatsAppWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="meta_cloud", max_length=16)),
                ("event_type", models.CharField(default="", max_length=64)),
                ("provider_event_id", models.CharField(max_length=160, unique=True)),
                (
                    "signature_header",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("signature_verified", models.BooleanField(default=False)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("received", "received"),
                            ("accepted", "accepted"),
                            ("duplicate", "duplicate"),
                            ("rejected", "rejected"),
                            ("error", "error"),
                        ],
                        default="received",
                        max_length=16,
                    ),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ("-received_at",),
                "indexes": [
                    models.Index(
                        fields=["processing_status", "-received_at"],
                        name="whatsapp_wh_process_e7dfb5_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consent_state",
                    models.CharField(
                        choices=[
                            ("unknown", "unknown"),
                            ("granted", "granted"),
                            ("revoked", "revoked"),
                            ("opted_out", "opted_out"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("granted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "opt_out_keyword",
                    models.CharField(blank=True, default="", max_length=24),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_inbound_at", models.DateTimeField(blank=True, null=True)),
                ("source", models.CharField(blank=True, default="", max_length=40)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_consent",
                        to="crm.customer",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
                "indexes": [
                    models.Index(
                        fields=["consent_state"], name="whatsapp_wh_consent_38edfb_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="whatsappconversation",
            index=models.Index(
                fields=["customer", "status", "-updated_at"],
                name="whatsapp_wh_custome_414337_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappconversation",
            index=models.Index(
                fields=["assigned_to", "status", "-updated_at"],
                name="whatsapp_wh_assigne_d465c7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappconversation",
            index=models.Index(
                fields=["status", "-last_message_at"],
                name="whatsapp_wh_status_06bb71_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappmessagestatusevent",
            index=models.Index(
                fields=["message", "-event_at"], name="whatsapp_wh_message_9a3cec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappsendlog",
            index=models.Index(
                fields=["message", "attempt"], name="whatsapp_wh_message_35799d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsapptemplate",
            index=models.Index(
                fields=["status", "is_active"], name="whatsapp_wh_status_41db20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsapptemplate",
            index=models.Index(
                fields=["action_key"], name="whatsapp_wh_action__b3de24_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="whatsapptemplate",
            constraint=models.UniqueConstraint(
                fields=("connection", "name", "language"),
                name="uniq_whatsapp_template_per_connection",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(
                fields=["conversation", "-created_at"],
                name="whatsapp_wh_convers_1b668c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(
                fields=["status", "-created_at"], name="whatsapp_wh_status_1dc3bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(
                fields=["direction", "-created_at"],
                name="whatsapp_wh_directi_c100a3_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="whatsappmessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_message_id", ""), _negated=True),
                fields=("provider_message_id",),
                name="uniq_whatsapp_message_provider_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="whatsappmessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("idempotency_key",),
                name="uniq_whatsapp_message_idempotency_key",
            ),
        ),
    ]
