# Generated by Django 5.1.15 on 2026-04-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0003_phase5d_handoff_lifecycle"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="whatsapphandofftocall",
            new_name="whatsapp_wh_convers_ae1708_idx",
            old_name="whatsapp_wh_convers_h0_idx",
        ),
        migrations.RenameIndex(
            model_name="whatsapphandofftocall",
            new_name="whatsapp_wh_status_38882e_idx",
            old_name="whatsapp_wh_status_h0_idx",
        ),
        migrations.RenameIndex(
            model_name="whatsapplifecycleevent",
            new_name="whatsapp_wh_object__aa4059_idx",
            old_name="whatsapp_wh_object_l0_idx",
        ),
        migrations.RenameIndex(
            model_name="whatsapplifecycleevent",
            new_name="whatsapp_wh_status_36692e_idx",
            old_name="whatsapp_wh_lstatus_l0_idx",
        ),
        migrations.RenameIndex(
            model_name="whatsapplifecycleevent",
            new_name="whatsapp_wh_action__62494b_idx",
            old_name="whatsapp_wh_action_l0_idx",
        ),
    ]
