# Generated by Django 5.1.15 on 2026-05-01 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_phase2e_meta_fields"),
        (
            "whatsapp",
            "0004_rename_whatsapp_wh_convers_h0_idx_whatsapp_wh_convers_ae1708_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppPilotCohortMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_masked",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "phone_suffix",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("approved", "approved"),
                            ("paused", "paused"),
                            ("removed", "removed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("consent_required", models.BooleanField(default=True)),
                ("consent_verified", models.BooleanField(default=False)),
                ("source", models.CharField(blank=True, default="", max_length=80)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "max_auto_replies_per_day",
                    models.PositiveSmallIntegerField(default=3),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_whatsapp_pilot_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="whatsapp_pilot_member",
                        to="crm.customer",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "-updated_at"],
                        name="whatsapp_wh_status_dd11cb_idx",
                    ),
                    models.Index(
                        fields=["phone_suffix"], name="whatsapp_wh_phone_s_809175_idx"
                    ),
                ],
            },
        ),
    ]
