# Generated by Django 5.1.15 on 2026-05-01 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saas", "0001_initial"),
        ("whatsapp", "0005_whatsapppilotcohortmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappconsent",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="whatsapp_consents",
                to="saas.organization",
            ),
        ),
        migrations.AddField(
            model_name="whatsappconversation",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="whatsapp_conversations",
                to="saas.branch",
            ),
        ),
        migrations.AddField(
            model_name="whatsappconversation",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="whatsapp_conversations",
                to="saas.organization",
            ),
        ),
        migrations.AddField(
            model_name="whatsapphandofftocall",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="whatsapp_handoffs",
                to="saas.organization",
            ),
        ),
        migrations.AddField(
            model_name="whatsapplifecycleevent",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="whatsapp_lifecycle_events",
                to="saas.organization",
            ),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="whatsapp_messages",
                to="saas.organization",
            ),
        ),
        migrations.AddField(
            model_name="whatsapppilotcohortmember",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="whatsapp_pilot_members",
                to="saas.organization",
            ),
        ),
    ]
