# Generated by Django 5.1.15 on 2026-05-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0006_whatsappconsent_organization_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Phase7ELiveBRealCustomerSendGate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("approved", "approved"),
                            ("executed", "executed"),
                            ("failed", "failed"),
                            ("cancelled", "cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("target_phone", models.CharField(max_length=32)),
                ("target_customer_name", models.CharField(max_length=120)),
                ("template_name", models.CharField(max_length=80)),
                ("template_params", models.JSONField(blank=True, default=dict)),
                (
                    "operator_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "director_signoff_text_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "recorded_signoff_window_start_utc",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "recorded_signoff_window_end_utc",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "meta_message_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                (
                    "next_action",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("customer_notification_sent", models.BooleanField(default=False)),
                ("payment_mutation_made", models.BooleanField(default=False)),
                ("order_mutation_made", models.BooleanField(default=False)),
                ("courier_called", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="p7elb_gate_status_created_idx",
                    ),
                    models.Index(
                        fields=["template_name", "-created_at"],
                        name="p7elb_gate_tpl_created_idx",
                    ),
                ],
            },
        ),
    ]
