# Generated by Django 5.1.15 on 2026-04-26 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CaioAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent", models.CharField(max_length=120)),
                ("issue", models.CharField(max_length=240)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("Critical", "Critical"),
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        default="Medium",
                        max_length=16,
                    ),
                ),
                ("suggestion", models.TextField()),
                ("status", models.CharField(default="Open", max_length=80)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ("sort_order",),
            },
        ),
        migrations.CreateModel(
            name="CeoBriefing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=40)),
                ("headline", models.CharField(max_length=240)),
                ("summary", models.TextField()),
                ("alerts", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="CeoRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_str", models.CharField(max_length=32)),
                ("title", models.CharField(max_length=240)),
                ("reason", models.TextField()),
                ("impact", models.CharField(max_length=120)),
                ("requires", models.CharField(max_length=120)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "briefing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="ai_governance.ceobriefing",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order",),
            },
        ),
    ]
