# Generated by Django 5.1.15 on 2026-04-28 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_governance", "0004_phase3d_sandbox_prompts_budgets"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalDecisionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(blank=True, default="", max_length=16)),
                ("new_status", models.CharField(max_length=16)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("action", models.CharField(max_length=120)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("auto", "auto"),
                            ("auto_with_consent", "auto_with_consent"),
                            ("approval_required", "approval_required"),
                            ("director_override", "director_override"),
                            ("human_escalation", "human_escalation"),
                        ],
                        max_length=24,
                    ),
                ),
                ("approver", models.CharField(default="auto", max_length=24)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                            ("auto_approved", "auto_approved"),
                            ("blocked", "blocked"),
                            ("escalated", "escalated"),
                            ("expired", "expired"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "requested_by_agent",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("target_app", models.CharField(blank=True, default="", max_length=64)),
                (
                    "target_model",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "target_object_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("proposed_payload", models.JSONField(blank=True, default=dict)),
                ("policy_snapshot", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField(blank=True, default="")),
                ("decision_note", models.TextField(blank=True, default="")),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.RenameIndex(
            model_name="agentrun",
            new_name="ai_governan_agent_97e038_idx",
            old_name="ai_governan_agent_5d4f2f_idx",
        ),
        migrations.RenameIndex(
            model_name="agentrun",
            new_name="ai_governan_status_84cce1_idx",
            old_name="ai_governan_status_2cd0b6_idx",
        ),
        migrations.RenameIndex(
            model_name="promptversion",
            new_name="ai_governan_agent_7ecfcc_idx",
            old_name="prompt_ver_agent_idx",
        ),
        migrations.RenameIndex(
            model_name="promptversion",
            new_name="ai_governan_status_26ca4e_idx",
            old_name="prompt_ver_status_idx",
        ),
        migrations.AlterField(
            model_name="agentbudget",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="approvaldecisionlog",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approval_decisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approval_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="approvaldecisionlog",
            name="approval_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decision_logs",
                to="ai_governance.approvalrequest",
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(fields=["action"], name="ai_governan_action_c69933_idx"),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(fields=["status"], name="ai_governan_status_81c062_idx"),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(fields=["mode"], name="ai_governan_mode_576e88_idx"),
        ),
        migrations.AddIndex(
            model_name="approvaldecisionlog",
            index=models.Index(
                fields=["approval_request", "created_at"],
                name="ai_governan_approva_b514db_idx",
            ),
        ),
    ]
