# Generated by Django 5.1.15 on 2026-04-28 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_governance", "0005_phase4c_approval_matrix"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("executed", "executed"),
                            ("failed", "failed"),
                            ("skipped", "skipped"),
                        ],
                        max_length=12,
                    ),
                ),
                ("executed_at", models.DateTimeField()),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_logs",
                        to="ai_governance.approvalrequest",
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["approval_request", "status"],
                        name="ai_governan_approva_ea9f6e_idx",
                    ),
                    models.Index(
                        fields=["action"], name="ai_governan_action_810ee4_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "executed")),
                        fields=("approval_request",),
                        name="uniq_approval_executed_log_per_request",
                    )
                ],
            },
        ),
    ]
