# Generated by Django 5.1.15 on 2026-05-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_governance", "0008_phase9b_add_rto_prevention_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentbudget",
            name="agent",
            field=models.CharField(
                choices=[
                    ("ceo", "ceo"),
                    ("caio", "caio"),
                    ("ads", "ads"),
                    ("rto", "rto"),
                    ("sales_growth", "sales_growth"),
                    ("marketing", "marketing"),
                    ("cfo", "cfo"),
                    ("compliance", "compliance"),
                    ("customer_success", "customer_success"),
                    ("rto_prevention", "rto_prevention"),
                    ("data_analyst", "data_analyst"),
                ],
                max_length=24,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="agentrun",
            name="agent",
            field=models.CharField(
                choices=[
                    ("ceo", "ceo"),
                    ("caio", "caio"),
                    ("ads", "ads"),
                    ("rto", "rto"),
                    ("sales_growth", "sales_growth"),
                    ("marketing", "marketing"),
                    ("cfo", "cfo"),
                    ("compliance", "compliance"),
                    ("customer_success", "customer_success"),
                    ("rto_prevention", "rto_prevention"),
                    ("data_analyst", "data_analyst"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="promptversion",
            name="agent",
            field=models.CharField(
                choices=[
                    ("ceo", "ceo"),
                    ("caio", "caio"),
                    ("ads", "ads"),
                    ("rto", "rto"),
                    ("sales_growth", "sales_growth"),
                    ("marketing", "marketing"),
                    ("cfo", "cfo"),
                    ("compliance", "compliance"),
                    ("customer_success", "customer_success"),
                    ("rto_prevention", "rto_prevention"),
                    ("data_analyst", "data_analyst"),
                ],
                max_length=24,
            ),
        ),
    ]
