# Generated by Django 5.1.15 on 2026-04-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=120)),
                ("role", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("warning", "Warning"),
                            ("paused", "Paused"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("health", models.IntegerField(default=100)),
                ("reward", models.IntegerField(default=0)),
                ("penalty", models.IntegerField(default=0)),
                (
                    "last_action",
                    models.CharField(blank=True, default="", max_length=240),
                ),
                ("critical", models.BooleanField(default=False)),
                ("group", models.CharField(default="Department", max_length=80)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
    ]
