# Generated by Django 5.1.15 on 2026-05-15 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
        ("ai_governance", "0006_phase4d_approval_execution_log"),
        ("crm", "0003_customer_branch_customer_organization_lead_branch_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerSuccessSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                (
                    "lifecycle_stage",
                    models.CharField(
                        choices=[
                            ("fresh_delivery", "fresh_delivery"),
                            ("early_usage", "early_usage"),
                            ("mid_usage", "mid_usage"),
                            ("reorder_window", "reorder_window"),
                            ("late_reorder", "late_reorder"),
                            ("lapsed", "lapsed"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("days_since_delivery", models.IntegerField(default=0)),
                ("in_reorder_window", models.BooleanField(default=False)),
                (
                    "reorder_candidate",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("at_risk", models.BooleanField(db_index=True, default=False)),
                ("risk_reasons", models.JSONField(blank=True, default=list)),
                ("signals", models.JSONField(blank=True, default=dict)),
                (
                    "recommendation_kind",
                    models.CharField(
                        choices=[
                            ("send_usage_reminder", "send_usage_reminder"),
                            ("send_reorder_reminder", "send_reorder_reminder"),
                            ("send_winback_offer", "send_winback_offer"),
                            ("monitor_only", "monitor_only"),
                        ],
                        default="monitor_only",
                        max_length=24,
                    ),
                ),
                ("recommendation_text", models.TextField(blank=True, default="")),
                ("sandbox", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_success_snapshots",
                        to="ai_governance.agentrun",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_success_snapshots",
                        to="crm.customer",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["customer", "-created_at"],
                        name="cs_snap_cust_created_idx",
                    ),
                    models.Index(
                        fields=["lifecycle_stage"], name="cs_snap_lifecycle_idx"
                    ),
                ],
            },
        ),
    ]
