# Generated by Django 5.1.15 on 2026-05-15 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_customer_success_snapshot"),
        ("ai_governance", "0008_phase9b_add_rto_prevention_agent"),
        ("crm", "0003_customer_branch_customer_organization_lead_branch_and_more"),
        ("orders", "0005_discountofferlog_organization_order_branch_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RtoRiskSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("risk_score", models.IntegerField(default=0)),
                (
                    "risk_tier",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                            ("critical", "critical"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                (
                    "lifecycle_stage",
                    models.CharField(
                        choices=[
                            ("pre_dispatch", "pre_dispatch"),
                            ("in_transit", "in_transit"),
                            ("delivery_at_risk", "delivery_at_risk"),
                        ],
                        max_length=24,
                    ),
                ),
                ("days_since_order", models.IntegerField(default=0)),
                ("failed_delivery_attempts", models.IntegerField(default=0)),
                ("risk_reasons", models.JSONField(blank=True, default=list)),
                ("signals", models.JSONField(blank=True, default=dict)),
                (
                    "recommendation_kind",
                    models.CharField(
                        choices=[
                            ("monitor_only", "monitor_only"),
                            (
                                "send_confirmation_reminder",
                                "send_confirmation_reminder",
                            ),
                            (
                                "send_pre_delivery_call_request",
                                "send_pre_delivery_call_request",
                            ),
                            ("escalate_to_team_lead", "escalate_to_team_lead"),
                        ],
                        db_index=True,
                        default="monitor_only",
                        max_length=32,
                    ),
                ),
                ("recommendation_text", models.TextField(blank=True, default="")),
                ("sandbox", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rto_risk_snapshots",
                        to="ai_governance.agentrun",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rto_risk_snapshots",
                        to="crm.customer",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rto_risk_snapshots",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["order", "-created_at"],
                        name="rto_snap_order_created_idx",
                    ),
                    models.Index(fields=["risk_tier"], name="rto_snap_risk_tier_idx"),
                    models.Index(
                        fields=["recommendation_kind"], name="rto_snap_rec_kind_idx"
                    ),
                ],
            },
        ),
    ]
