# Generated by Django 5.1.15 on 2026-05-15 09:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_rto_risk_snapshot"),
        ("ai_governance", "0008_phase9b_add_rto_prevention_agent"),
        ("saas", "0007_phase7d_hotfix_director_signoff_window"),
    ]

    operations = [
        migrations.CreateModel(
            name="CfoFinancialSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_at", models.DateTimeField(db_index=True)),
                (
                    "revenue_24h",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "revenue_7d",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "revenue_30d",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("order_count_24h", models.IntegerField(default=0)),
                ("order_count_7d", models.IntegerField(default=0)),
                ("order_count_30d", models.IntegerField(default=0)),
                ("paid_count", models.IntegerField(default=0)),
                ("partial_count", models.IntegerField(default=0)),
                ("pending_count", models.IntegerField(default=0)),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "partial_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "pending_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "average_order_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("rto_count_30d", models.IntegerField(default=0)),
                (
                    "rto_loss_amount_30d",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("new_customer_count_30d", models.IntegerField(default=0)),
                ("returning_customer_count_30d", models.IntegerField(default=0)),
                ("alerts", models.JSONField(blank=True, default=list)),
                ("alert_text", models.TextField(blank=True, default="")),
                ("sandbox", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cfo_financial_snapshots",
                        to="ai_governance.agentrun",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cfo_financial_snapshots",
                        to="saas.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-snapshot_at",),
                "indexes": [
                    models.Index(fields=["-snapshot_at"], name="cfo_snap_at_idx"),
                    models.Index(
                        fields=["organization", "-snapshot_at"],
                        name="cfo_snap_org_at_idx",
                    ),
                ],
            },
        ),
    ]
