# Generated by Django 5.1.15 on 2026-05-15 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_cfo_financial_snapshot"),
        ("ai_governance", "0009_phase9d_add_data_analyst_agent"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataAnalystSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_at", models.DateTimeField(db_index=True)),
                ("lead_count_30d", models.IntegerField(default=0)),
                ("call_count_30d", models.IntegerField(default=0)),
                ("confirmed_order_count_30d", models.IntegerField(default=0)),
                ("delivered_order_count_30d", models.IntegerField(default=0)),
                ("reorder_count_30d", models.IntegerField(default=0)),
                ("lead_to_call_rate", models.FloatField(default=0.0)),
                ("call_to_confirmed_rate", models.FloatField(default=0.0)),
                ("confirmed_to_delivered_rate", models.FloatField(default=0.0)),
                ("delivered_to_reorder_rate", models.FloatField(default=0.0)),
                ("top_states", models.JSONField(blank=True, default=list)),
                ("day_of_week_counts", models.JSONField(blank=True, default=dict)),
                ("alerts", models.JSONField(blank=True, default=list)),
                ("alert_text", models.TextField(blank=True, default="")),
                ("sandbox", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_analyst_snapshots",
                        to="ai_governance.agentrun",
                    ),
                ),
            ],
            options={
                "ordering": ("-snapshot_at",),
                "indexes": [
                    models.Index(fields=["-snapshot_at"], name="da_snap_at_idx")
                ],
            },
        ),
    ]
