# Generated by Django 5.1.15 on 2026-05-15 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0005_data_analyst_snapshot"),
        ("ai_governance", "0010_phase9e_add_calling_team_leader_agent"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallingTeamLeaderSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_at", models.DateTimeField(db_index=True)),
                ("call_count_24h", models.IntegerField(default=0)),
                ("call_count_7d", models.IntegerField(default=0)),
                ("call_count_30d", models.IntegerField(default=0)),
                ("answered_count_30d", models.IntegerField(default=0)),
                ("connection_rate_30d", models.FloatField(default=0.0)),
                ("avg_duration_seconds_30d", models.FloatField(default=0.0)),
                ("outcome_breakdown", models.JSONField(blank=True, default=dict)),
                ("agent_breakdown", models.JSONField(blank=True, default=list)),
                ("transcript_backlog_count", models.IntegerField(default=0)),
                ("alerts", models.JSONField(blank=True, default=list)),
                ("alert_text", models.TextField(blank=True, default="")),
                ("sandbox", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calling_team_leader_snapshots",
                        to="ai_governance.agentrun",
                    ),
                ),
            ],
            options={
                "ordering": ("-snapshot_at",),
                "indexes": [
                    models.Index(fields=["-snapshot_at"], name="ctl_snap_at_idx")
                ],
            },
        ),
    ]
