# Generated by Django 5.1.15 on 2026-05-15 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0006_calling_team_leader_snapshot"),
        ("ai_governance", "0010_phase9e_add_calling_team_leader_agent"),
    ]

    operations = [
        migrations.CreateModel(
            name="CeoOrchestrationSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_at", models.DateTimeField(db_index=True)),
                ("business_health_score", models.IntegerField(default=0)),
                (
                    "health_tier",
                    models.CharField(
                        choices=[
                            ("critical", "critical"),
                            ("poor", "poor"),
                            ("fair", "fair"),
                            ("good", "good"),
                            ("excellent", "excellent"),
                        ],
                        db_index=True,
                        default="fair",
                        max_length=12,
                    ),
                ),
                ("cross_cutting_alerts", models.JSONField(blank=True, default=list)),
                ("top_3_priorities", models.JSONField(blank=True, default=list)),
                ("agent_status_summary", models.JSONField(blank=True, default=dict)),
                ("briefing_text", models.TextField(blank=True, default="")),
                ("alerts", models.JSONField(blank=True, default=list)),
                ("sandbox", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ceo_orchestration_snapshots",
                        to="ai_governance.agentrun",
                    ),
                ),
                (
                    "calling_team_leader_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ceo_orchestration_snapshots",
                        to="agents.callingteamleadersnapshot",
                    ),
                ),
                (
                    "cfo_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ceo_orchestration_snapshots",
                        to="agents.cfofinancialsnapshot",
                    ),
                ),
                (
                    "customer_success_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ceo_orchestration_snapshots",
                        to="agents.customersuccesssnapshot",
                    ),
                ),
                (
                    "data_analyst_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ceo_orchestration_snapshots",
                        to="agents.dataanalystsnapshot",
                    ),
                ),
                (
                    "rto_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ceo_orchestration_snapshots",
                        to="agents.rtorisksnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ("-snapshot_at",),
                "indexes": [
                    models.Index(fields=["-snapshot_at"], name="ceo_orch_snap_at_idx")
                ],
            },
        ),
    ]
