# Generated by Django 5.1.15 on 2026-05-30 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0004_phase16b_lead_consent_fields"),
        ("data_imports", "0001_initial"),
        ("orders", "0005_discountofferlog_organization_order_branch_and_more"),
        ("saas", "0007_phase7d_hotfix_director_signoff_window"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PilotDryRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "scenario_type",
                    models.CharField(
                        choices=[
                            ("fresh_lead", "Fresh lead"),
                            ("imported_campaign", "Imported campaign"),
                            ("existing_order", "Existing order"),
                            ("payment_logistics", "Payment / logistics"),
                            ("full_lifecycle", "Full lifecycle"),
                        ],
                        db_index=True,
                        default="full_lifecycle",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("passed", "Passed"),
                            ("warning", "Warning"),
                            ("blocked", "Blocked"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("result_summary", models.TextField(blank=True, default="")),
                ("gate_results", models.JSONField(blank=True, default=list)),
                ("blocked_reasons", models.JSONField(blank=True, default=list)),
                ("safety_snapshot", models.JSONField(blank=True, default=dict)),
                ("provider_actions_attempted", models.BooleanField(default=False)),
                ("provider_actions_blocked", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pilot_dry_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="saas.organization",
                    ),
                ),
                (
                    "selected_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="crm.customer",
                    ),
                ),
                (
                    "selected_import_campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="data_imports.importedcallingcampaign",
                    ),
                ),
                (
                    "selected_lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="crm.lead",
                    ),
                ),
                (
                    "selected_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="orders.order",
                    ),
                ),
                (
                    "selected_queue_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="data_imports.importedcallqueueitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PilotDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("reviewed", "Reviewed"),
                            ("approved_for_next_phase", "Approved for next phase"),
                            ("deferred", "Deferred"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="reviewed",
                        max_length=32,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("signoff_checklist", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pilot_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dry_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="pilot.pilotdryrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="pilotdryrun",
            index=models.Index(fields=["-created_at"], name="pilot_dr_created_idx"),
        ),
        migrations.AddIndex(
            model_name="pilotdryrun",
            index=models.Index(fields=["status"], name="pilot_dr_status_idx"),
        ),
        migrations.AddIndex(
            model_name="pilotdryrun",
            index=models.Index(fields=["scenario_type"], name="pilot_dr_scenario_idx"),
        ),
        migrations.AddIndex(
            model_name="pilotdecision",
            index=models.Index(fields=["-created_at"], name="pilot_dec_created_idx"),
        ),
        migrations.AddIndex(
            model_name="pilotdecision",
            index=models.Index(fields=["decision"], name="pilot_dec_decision_idx"),
        ),
    ]
