# Generated by Django 5.1.15 on 2026-06-01 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_imports", "0001_initial"),
        ("orders", "0005_discountofferlog_organization_order_branch_and_more"),
        ("pilot", "0001_initial"),
        ("saas", "0007_phase7d_hotfix_director_signoff_window"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PilotPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "pilot_type",
                    models.CharField(
                        choices=[
                            ("imported_campaign", "Imported campaign"),
                            ("fresh_leads", "Fresh leads"),
                            ("existing_orders", "Existing orders"),
                            ("payment_logistics", "Payment / logistics"),
                            ("full_lifecycle", "Full lifecycle"),
                        ],
                        db_index=True,
                        default="full_lifecycle",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready_for_review", "Ready for review"),
                            ("approved_internal", "Approved (internal)"),
                            ("running_internal", "Running (internal)"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("owner_team", models.CharField(blank=True, default="", max_length=64)),
                (
                    "problem_category",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "product_category",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("objective", models.TextField(blank=True, default="")),
                ("risk_note", models.TextField(blank=True, default="")),
                ("allowed_list_note", models.TextField(blank=True, default="")),
                ("max_contacts", models.IntegerField(default=0)),
                ("planned_start_at", models.DateTimeField(blank=True, null=True)),
                ("planned_end_at", models.DateTimeField(blank=True, null=True)),
                ("safety_acknowledged", models.BooleanField(default=False)),
                ("provider_actions_allowed", models.BooleanField(default=False)),
                ("provider_actions_attempted", models.BooleanField(default=False)),
                ("provider_actions_blocked", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pilot_plans_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="data_imports.importeddataset",
                    ),
                ),
                (
                    "linked_dry_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pilot_plans",
                        to="pilot.pilotdryrun",
                    ),
                ),
                (
                    "linked_import_campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="data_imports.importedcallingcampaign",
                    ),
                ),
                (
                    "linked_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="orders.order",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="saas.organization",
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pilot_plans_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pilot_plans_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PilotPlanEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("ready_for_review", "Marked ready for review"),
                            ("approved_internal", "Approved (internal)"),
                            ("started_internal", "Started (internal)"),
                            ("paused", "Paused"),
                            ("resumed_internal", "Resumed (internal)"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("note_added", "Note added"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("safety_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pilot_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="pilot.pilotplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PilotPlanReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("reviewed", "Reviewed"),
                            ("approved_internal", "Approved (internal)"),
                            ("deferred", "Deferred"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="reviewed",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pilot_plan_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pilot_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="pilot.pilotplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="pilotplan",
            index=models.Index(fields=["-created_at"], name="pilot_pl_created_idx"),
        ),
        migrations.AddIndex(
            model_name="pilotplan",
            index=models.Index(fields=["status"], name="pilot_pl_status_idx"),
        ),
        migrations.AddIndex(
            model_name="pilotplan",
            index=models.Index(fields=["pilot_type"], name="pilot_pl_type_idx"),
        ),
        migrations.AddIndex(
            model_name="pilotplanevent",
            index=models.Index(fields=["-created_at"], name="pilot_pe_created_idx"),
        ),
        migrations.AddIndex(
            model_name="pilotplanevent",
            index=models.Index(fields=["event_type"], name="pilot_pe_type_idx"),
        ),
        migrations.AddIndex(
            model_name="pilotplanreview",
            index=models.Index(fields=["-created_at"], name="pilot_pr_created_idx"),
        ),
        migrations.AddIndex(
            model_name="pilotplanreview",
            index=models.Index(fields=["decision"], name="pilot_pr_decision_idx"),
        ),
    ]
