# Generated by Django 5.1.15 on 2026-06-01 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_imports", "0001_initial"),
        ("orders", "0005_discountofferlog_organization_order_branch_and_more"),
        ("pilot", "0002_phase16g_pilot_control"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PilotTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_role",
                    models.CharField(
                        choices=[
                            ("calling_agent", "Calling"),
                            ("confirmation_team", "Confirmation"),
                            ("warehouse_dispatch", "Dispatch / Warehouse"),
                            ("delivery_rto", "Delivery / RTO"),
                            ("qa_compliance", "QA / Compliance"),
                            ("finance_accounts", "Finance / Accounts"),
                            ("director_admin", "Director / Admin"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To do"),
                            ("in_progress", "In progress"),
                            ("blocked", "Blocked"),
                            ("done", "Done"),
                            ("skipped", "Skipped"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="todo",
                        max_length=16,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                        ],
                        default="normal",
                        max_length=8,
                    ),
                ),
                ("sequence", models.IntegerField(default=0)),
                (
                    "assigned_team_label",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("checklist", models.JSONField(blank=True, default=list)),
                (
                    "blocked_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("provider_actions_allowed", models.BooleanField(default=False)),
                ("provider_actions_attempted", models.BooleanField(default=False)),
                ("provider_actions_blocked", models.BooleanField(default=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pilot_tasks_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pilot_tasks_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_import_campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="data_imports.importedcallingcampaign",
                    ),
                ),
                (
                    "linked_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="orders.order",
                    ),
                ),
                (
                    "linked_queue_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="data_imports.importedcallqueueitem",
                    ),
                ),
                (
                    "pilot_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="pilot.pilotplan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pilot_tasks_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PilotTaskEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("assigned", "Assigned"),
                            ("started", "Started"),
                            ("blocked", "Blocked"),
                            ("unblocked", "Unblocked"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                            ("cancelled", "Cancelled"),
                            ("checklist_updated", "Checklist updated"),
                            ("note_added", "Note added"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="pilot.pilottask",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="pilottask",
            index=models.Index(fields=["-created_at"], name="pilot_tk_created_idx"),
        ),
        migrations.AddIndex(
            model_name="pilottask",
            index=models.Index(fields=["status"], name="pilot_tk_status_idx"),
        ),
        migrations.AddIndex(
            model_name="pilottask",
            index=models.Index(fields=["team_role"], name="pilot_tk_team_idx"),
        ),
        migrations.AddIndex(
            model_name="pilottask",
            index=models.Index(
                fields=["pilot_plan", "team_role"], name="pilot_tk_plan_team_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pilottaskevent",
            index=models.Index(fields=["-created_at"], name="pilot_te_created_idx"),
        ),
        migrations.AddIndex(
            model_name="pilottaskevent",
            index=models.Index(fields=["event_type"], name="pilot_te_type_idx"),
        ),
    ]
