# Generated by Django 5.1.15 on 2026-04-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("customer_name", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=24)),
                ("product", models.CharField(max_length=120)),
                ("quantity", models.IntegerField(default=1)),
                ("amount", models.IntegerField(default=0)),
                ("discount_pct", models.IntegerField(default=0)),
                ("advance_paid", models.BooleanField(default=False)),
                ("advance_amount", models.IntegerField(default=0)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Paid", "Paid"),
                            ("Partial", "Partial"),
                            ("Pending", "Pending"),
                            ("Failed", "Failed"),
                        ],
                        default="Pending",
                        max_length=16,
                    ),
                ),
                ("state", models.CharField(max_length=60)),
                ("city", models.CharField(max_length=80)),
                (
                    "rto_risk",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        default="Low",
                        max_length=8,
                    ),
                ),
                ("rto_score", models.IntegerField(default=0)),
                ("agent", models.CharField(default="", max_length=80)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("New Lead", "New Lead"),
                            ("Interested", "Interested"),
                            ("Payment Link Sent", "Payment Link Sent"),
                            ("Order Punched", "Order Punched"),
                            ("Confirmation Pending", "Confirmation Pending"),
                            ("Confirmed", "Confirmed"),
                            ("Dispatched", "Dispatched"),
                            ("Out for Delivery", "Out for Delivery"),
                            ("Delivered", "Delivered"),
                            ("RTO", "RTO"),
                        ],
                        default="Order Punched",
                        max_length=32,
                    ),
                ),
                ("awb", models.CharField(blank=True, max_length=40, null=True)),
                ("age_hours", models.IntegerField(default=0)),
                (
                    "created_at_label",
                    models.CharField(default="just now", max_length=40),
                ),
                ("hours_waiting", models.IntegerField(default=0)),
                ("address_confidence", models.IntegerField(default=0)),
                ("confirmation_checklist", models.JSONField(blank=True, default=dict)),
                ("risk_reasons", models.JSONField(blank=True, default=list)),
                ("rescue_status", models.CharField(default="", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["stage"], name="orders_orde_stage_cdc59b_idx"),
                    models.Index(
                        fields=["rto_risk"], name="orders_orde_rto_ris_62bbb9_idx"
                    ),
                ],
            },
        ),
    ]
