# Generated by Django 5.1.15 on 2026-04-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="confirmation_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="confirmation_outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("rescue_needed", "Rescue Needed"),
                    ("cancelled", "Cancelled"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="stage",
            field=models.CharField(
                choices=[
                    ("New Lead", "New Lead"),
                    ("Interested", "Interested"),
                    ("Payment Link Sent", "Payment Link Sent"),
                    ("Order Punched", "Order Punched"),
                    ("Confirmation Pending", "Confirmation Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Dispatched", "Dispatched"),
                    ("Out for Delivery", "Out for Delivery"),
                    ("Delivered", "Delivered"),
                    ("RTO", "RTO"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Order Punched",
                max_length=32,
            ),
        ),
    ]
