# Generated by Django 5.1.15 on 2026-04-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_phase5e_discount_offer_log"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="discountofferlog",
            new_name="orders_disc_order_i_e49f63_idx",
            old_name="orders_disc_order_i_dol_idx",
        ),
        migrations.RenameIndex(
            model_name="discountofferlog",
            new_name="orders_disc_status_2545ae_idx",
            old_name="orders_disc_status_dol_idx",
        ),
        migrations.RenameIndex(
            model_name="discountofferlog",
            new_name="orders_disc_stage_73bb3e_idx",
            old_name="orders_disc_stage_dol_idx",
        ),
        migrations.RenameIndex(
            model_name="discountofferlog",
            new_name="orders_disc_source__5b0c4a_idx",
            old_name="orders_disc_source_dol_idx",
        ),
    ]
