# Generated by Django 5.1.15 on 2026-05-01 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0004_rename_orders_disc_order_i_dol_idx_orders_disc_order_i_e49f63_idx_and_more",
        ),
        ("saas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountofferlog",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discount_offers",
                to="saas.organization",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="saas.branch",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="saas.organization",
            ),
        ),
    ]
