# Generated by Django 5.1.15 on 2026-05-18 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("caio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_agent", models.CharField(max_length=80)),
                (
                    "proposal_type",
                    models.CharField(
                        choices=[
                            ("compliance_remediation", "compliance_remediation"),
                            ("script_review", "script_review"),
                            ("knowledge_gap", "knowledge_gap"),
                            ("process_improvement", "process_improvement"),
                            ("agent_coaching", "agent_coaching"),
                        ],
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                            ("implemented", "implemented"),
                            ("cancelled", "cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "impact_scope",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                        ],
                        default="medium",
                        max_length=8,
                    ),
                ),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("proposed_change_text", models.TextField()),
                (
                    "director_decision",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("director_note", models.TextField(blank=True, default="")),
                (
                    "reviewed_by",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("implementation_note", models.TextField(blank=True, default="")),
                ("implemented_at", models.DateTimeField(blank=True, null=True)),
                (
                    "implemented_by",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "caio_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_proposals",
                        to="caio.caioauditsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["status"], name="lp_status_idx"),
                    models.Index(fields=["proposal_type"], name="lp_type_idx"),
                    models.Index(fields=["-created_at"], name="lp_created_at_idx"),
                ],
            },
        ),
    ]
