# Generated by Django 5.1.15 on 2026-04-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("icon", models.CharField(default="activity", max_length=32)),
                ("text", models.CharField(max_length=512)),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("danger", "Danger"),
                        ],
                        default="info",
                        max_length=16,
                    ),
                ),
                (
                    "kind",
                    models.CharField(db_index=True, default="event", max_length=64),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ("-occurred_at",),
                "indexes": [
                    models.Index(
                        fields=["-occurred_at", "kind"],
                        name="audit_audit_occurre_463517_idx",
                    )
                ],
            },
        ),
    ]
