# Generated by Django 5.1.15 on 2026-04-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RewardPenalty",
            fields=[
                (
                    "name",
                    models.CharField(max_length=120, primary_key=True, serialize=False),
                ),
                ("reward", models.IntegerField(default=0)),
                ("penalty", models.IntegerField(default=0)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ("sort_order", "name"),
            },
        ),
    ]
