# Generated by Django 5.1.15 on 2026-04-28 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
        ("orders", "0002_order_confirmation_notes_order_confirmation_outcome_and_more"),
        ("rewards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rewardpenalty",
            name="agent_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="rewardpenalty",
            name="agent_type",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="rewardpenalty",
            name="last_calculated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rewardpenalty",
            name="penalized_orders",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="rewardpenalty",
            name="rewarded_orders",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="RewardPenaltyEvent",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "order_id_snapshot",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("agent_name", models.CharField(max_length=120)),
                ("agent_type", models.CharField(blank=True, default="", max_length=64)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("reward", "Reward"),
                            ("penalty", "Penalty"),
                            ("mixed", "Mixed"),
                        ],
                        default="mixed",
                        max_length=16,
                    ),
                ),
                ("reward_score", models.IntegerField(default=0)),
                ("penalty_score", models.IntegerField(default=0)),
                ("net_score", models.IntegerField(default=0)),
                ("components", models.JSONField(blank=True, default=list)),
                ("missing_data", models.JSONField(blank=True, default=list)),
                ("attribution", models.JSONField(blank=True, default=dict)),
                ("source", models.CharField(default="phase4b_engine", max_length=40)),
                (
                    "triggered_by",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("unique_key", models.CharField(max_length=200, unique=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reward_penalty_events",
                        to="agents.agent",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reward_penalty_events",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ("-calculated_at", "order_id_snapshot", "agent_name"),
                "indexes": [
                    models.Index(
                        fields=["agent_name"], name="rewards_rew_agent_n_ac429b_idx"
                    ),
                    models.Index(
                        fields=["event_type"], name="rewards_rew_event_t_913d0c_idx"
                    ),
                    models.Index(
                        fields=["source"], name="rewards_rew_source_fee5cc_idx"
                    ),
                    models.Index(
                        fields=["order_id_snapshot"],
                        name="rewards_rew_order_i_c4505b_idx",
                    ),
                ],
            },
        ),
    ]
