# Generated by Django 5.1.15 on 2026-04-27 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product Category",
                "verbose_name_plural": "Product Categories",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("default_price_inr", models.PositiveIntegerField(default=3000)),
                (
                    "default_quantity_label",
                    models.CharField(default="30 capsules", max_length=80),
                ),
                (
                    "product_cost_inr",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "default_usage_instructions",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "active_claim_products",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of `Claim.product` keys (strings) covering this product. Display-only join aid — AI generation still goes through the Approved Claim Vault.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.productcategory",
                    ),
                ),
            ],
            options={
                "ordering": ("category__sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="ProductSKU",
            fields=[
                (
                    "id",
                    models.CharField(max_length=48, primary_key=True, serialize=False),
                ),
                ("sku_code", models.CharField(max_length=80, unique=True)),
                ("title", models.CharField(blank=True, default="", max_length=160)),
                (
                    "quantity_label",
                    models.CharField(default="30 capsules", max_length=80),
                ),
                ("mrp_inr", models.PositiveIntegerField(default=0)),
                ("selling_price_inr", models.PositiveIntegerField(default=0)),
                (
                    "product_cost_inr",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("stock_quantity", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skus",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ("product__name", "selling_price_inr"),
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active"], name="catalog_pro_is_acti_14fc6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productsku",
            index=models.Index(
                fields=["product"], name="catalog_pro_product_dc3f47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productsku",
            index=models.Index(
                fields=["is_active"], name="catalog_pro_is_acti_9d3787_idx"
            ),
        ),
    ]
