# Generated by Django 5.1.15 on 2026-05-01 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationIntegrationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("whatsapp_meta", "WhatsApp Meta"),
                            ("razorpay", "Razorpay"),
                            ("payu", "PayU"),
                            ("delhivery", "Delhivery"),
                            ("vapi", "Vapi"),
                            ("openai", "OpenAI"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("configured", "Configured"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("invalid", "Invalid"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("secret_refs", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=False)),
                ("last_validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("not_checked", "Not checked"),
                            ("valid", "Valid"),
                            ("invalid", "Invalid"),
                            ("warning", "Warning"),
                        ],
                        default="not_checked",
                        max_length=16,
                    ),
                ),
                ("validation_message", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_settings",
                        to="saas.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("organization", "provider_type", "display_name"),
                "indexes": [
                    models.Index(
                        fields=["organization", "provider_type"],
                        name="saas_organi_organiz_1df32e_idx",
                    ),
                    models.Index(
                        fields=["status", "validation_status"],
                        name="saas_organi_status_b78b56_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "provider_type", "display_name"),
                        name="saas_integration_unique_org_provider_name",
                    )
                ],
            },
        ),
    ]
