# Generated by Django 5.1.15 on 2026-05-02 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_default_runtime_kill_switch(apps, schema_editor):
    RuntimeKillSwitch = apps.get_model("saas", "RuntimeKillSwitch")
    RuntimeKillSwitch.objects.get_or_create(
        scope="global",
        organization=None,
        provider_type="",
        operation_type="",
        defaults={
            "enabled": True,
            "reason": "Phase 6H default global live execution block.",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("saas", "0002_organizationintegrationsetting"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RuntimeKillSwitch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("organization", "Organization"),
                            ("provider", "Provider"),
                            ("operation", "Operation"),
                        ],
                        db_index=True,
                        default="global",
                        max_length=24,
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(blank=True, default="", max_length=48),
                ),
                (
                    "operation_type",
                    models.CharField(blank=True, default="", max_length=96),
                ),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                ("reason", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_kill_switch_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_kill_switches",
                        to="saas.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("scope", "provider_type", "operation_type"),
                "indexes": [
                    models.Index(
                        fields=["scope", "enabled"], name="saas_runtim_scope_0731ab_idx"
                    ),
                    models.Index(
                        fields=["organization", "scope"],
                        name="saas_runtim_organiz_ba95a0_idx",
                    ),
                    models.Index(
                        fields=["provider_type", "operation_type"],
                        name="saas_runtim_provide_1d4119_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RuntimeLiveExecutionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_type", models.CharField(db_index=True, max_length=96)),
                ("provider_type", models.CharField(db_index=True, max_length=48)),
                (
                    "runtime_source",
                    models.CharField(default="env_config", max_length=32),
                ),
                ("per_org_runtime_enabled", models.BooleanField(default=False)),
                ("dry_run", models.BooleanField(default=True)),
                ("live_execution_requested", models.BooleanField(default=False)),
                ("live_execution_allowed", models.BooleanField(default=False)),
                ("external_call_will_be_made", models.BooleanField(default=False)),
                ("approval_required", models.BooleanField(default=True)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("not_required", "Not required"),
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=24,
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("risk_level", models.CharField(default="high", max_length=16)),
                (
                    "payload_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("safe_payload_summary", models.JSONField(blank=True, default=dict)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "gate_decision",
                    models.CharField(
                        choices=[
                            ("dry_run_allowed", "Dry-run allowed"),
                            ("blocked_by_default", "Blocked by default"),
                            ("blocked_by_kill_switch", "Blocked by kill switch"),
                            ("blocked_missing_approval", "Blocked missing approval"),
                            (
                                "blocked_missing_provider_config",
                                "Blocked missing provider config",
                            ),
                            ("blocked_missing_consent", "Blocked missing consent"),
                            (
                                "blocked_missing_caio_review",
                                "Blocked missing CAIO review",
                            ),
                            (
                                "blocked_missing_claim_vault",
                                "Blocked missing Claim Vault",
                            ),
                            ("blocked_missing_webhook", "Blocked missing webhook"),
                            (
                                "live_ready_but_not_executed",
                                "Live ready but not executed",
                            ),
                        ],
                        db_index=True,
                        default="blocked_by_default",
                        max_length=48,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=160
                    ),
                ),
                ("audit_event_id", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_live_requests_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_live_execution_requests",
                        to="saas.branch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_live_execution_requests",
                        to="saas.organization",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_live_requests_rejected",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_live_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["organization", "operation_type"],
                        name="saas_runtim_organiz_04489e_idx",
                    ),
                    models.Index(
                        fields=["approval_status", "gate_decision"],
                        name="saas_runtim_approva_1a9842_idx",
                    ),
                    models.Index(
                        fields=["-created_at", "operation_type"],
                        name="saas_runtim_created_7a71c8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RuntimeLiveGatePolicySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_type", models.CharField(db_index=True, max_length=96)),
                ("provider_type", models.CharField(db_index=True, max_length=48)),
                ("risk_level", models.CharField(default="high", max_length=16)),
                ("live_allowed_by_default", models.BooleanField(default=False)),
                ("approval_required", models.BooleanField(default=True)),
                ("caio_review_required", models.BooleanField(default=False)),
                ("consent_required", models.BooleanField(default=False)),
                ("claim_vault_required", models.BooleanField(default=False)),
                ("webhook_required", models.BooleanField(default=False)),
                ("idempotency_required", models.BooleanField(default=True)),
                ("kill_switch_can_block", models.BooleanField(default=True)),
                (
                    "policy_version",
                    models.CharField(default="phase6h.v1", max_length=32),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_live_gate_policy_snapshots",
                        to="saas.branch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_live_gate_policy_snapshots",
                        to="saas.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["organization", "operation_type"],
                        name="saas_runtim_organiz_4167d1_idx",
                    ),
                    models.Index(
                        fields=["provider_type", "risk_level"],
                        name="saas_runtim_provide_fc7d5a_idx",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            seed_default_runtime_kill_switch,
            migrations.RunPython.noop,
        ),
    ]
