# Generated by Django 5.1.15 on 2026-05-02 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saas", "0003_runtimekillswitch_runtimeliveexecutionrequest_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RuntimeLiveGateSimulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        db_index=True, default="razorpay.create_order", max_length=96
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(db_index=True, default="razorpay", max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prepared", "Prepared"),
                            ("approval_requested", "Approval requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("blocked", "Blocked"),
                            ("simulated", "Simulated"),
                            ("rolled_back", "Rolled back"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="prepared",
                        max_length=32,
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("not_required", "Not required"),
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="not_required",
                        max_length=24,
                    ),
                ),
                (
                    "runtime_source",
                    models.CharField(default="env_config", max_length=32),
                ),
                ("per_org_runtime_enabled", models.BooleanField(default=False)),
                ("dry_run", models.BooleanField(default=True)),
                ("live_execution_requested", models.BooleanField(default=False)),
                ("live_execution_allowed", models.BooleanField(default=False)),
                ("external_call_will_be_made", models.BooleanField(default=False)),
                ("external_call_was_made", models.BooleanField(default=False)),
                ("provider_call_attempted", models.BooleanField(default=False)),
                ("kill_switch_active", models.BooleanField(default=True)),
                ("risk_level", models.CharField(default="medium", max_length=16)),
                (
                    "payload_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("safe_payload_summary", models.JSONField(blank=True, default=dict)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "gate_decision",
                    models.CharField(
                        choices=[
                            ("dry_run_allowed", "Dry-run allowed"),
                            ("blocked_by_default", "Blocked by default"),
                            ("blocked_by_kill_switch", "Blocked by kill switch"),
                            ("blocked_missing_approval", "Blocked missing approval"),
                            (
                                "blocked_missing_provider_config",
                                "Blocked missing provider config",
                            ),
                            ("blocked_missing_consent", "Blocked missing consent"),
                            (
                                "blocked_missing_caio_review",
                                "Blocked missing CAIO review",
                            ),
                            (
                                "blocked_missing_claim_vault",
                                "Blocked missing Claim Vault",
                            ),
                            ("blocked_missing_webhook", "Blocked missing webhook"),
                            (
                                "live_ready_but_not_executed",
                                "Live ready but not executed",
                            ),
                        ],
                        db_index=True,
                        default="blocked_by_default",
                        max_length=48,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=160
                    ),
                ),
                ("simulation_result", models.JSONField(blank=True, default=dict)),
                ("audit_event_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "prepared_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("approval_requested_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("run_at", models.DateTimeField(blank=True, null=True)),
                ("rolled_back_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval_requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_gate_simulations_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_gate_simulations_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_live_gate_simulations",
                        to="saas.branch",
                    ),
                ),
                (
                    "live_execution_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="simulations",
                        to="saas.runtimeliveexecutionrequest",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_live_gate_simulations",
                        to="saas.organization",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_gate_simulations_prepared",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_gate_simulations_rejected",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rolled_back_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_gate_simulations_rolled_back",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_gate_simulations_run",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["organization", "operation_type"],
                        name="saas_runtim_organiz_784d69_idx",
                    ),
                    models.Index(
                        fields=["status", "approval_status"],
                        name="saas_runtim_status_93b55f_idx",
                    ),
                    models.Index(
                        fields=["-created_at", "status"],
                        name="saas_runtim_created_76b5c2_idx",
                    ),
                ],
            },
        ),
    ]
