# Generated by Django 5.1.15 on 2026-05-02 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saas", "0004_runtimelivegatesimulation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RuntimeProviderTestPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("provider_type", models.CharField(db_index=True, max_length=48)),
                ("operation_type", models.CharField(db_index=True, max_length=96)),
                (
                    "provider_environment",
                    models.CharField(
                        choices=[
                            ("test", "Test"),
                            ("sandbox", "Sandbox"),
                            ("production", "Production"),
                        ],
                        db_index=True,
                        default="test",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("prepared", "Prepared"),
                            ("validated", "Validated"),
                            ("approval_required", "Approval required"),
                            (
                                "approved_for_future_execution",
                                "Approved for future execution",
                            ),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=40,
                    ),
                ),
                (
                    "runtime_source",
                    models.CharField(default="env_config", max_length=32),
                ),
                ("per_org_runtime_enabled", models.BooleanField(default=False)),
                ("dry_run", models.BooleanField(default=True)),
                ("provider_call_allowed", models.BooleanField(default=False)),
                ("external_call_will_be_made", models.BooleanField(default=False)),
                ("external_call_was_made", models.BooleanField(default=False)),
                ("provider_call_attempted", models.BooleanField(default=False)),
                ("real_customer_data_allowed", models.BooleanField(default=False)),
                ("real_money", models.BooleanField(default=False)),
                ("amount_paise", models.PositiveIntegerField(blank=True, null=True)),
                ("currency", models.CharField(default="INR", max_length=8)),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=160
                    ),
                ),
                (
                    "payload_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("safe_payload_summary", models.JSONField(blank=True, default=dict)),
                ("env_readiness", models.JSONField(blank=True, default=dict)),
                ("secret_ref_readiness", models.JSONField(blank=True, default=dict)),
                ("gate_requirements", models.JSONField(blank=True, default=dict)),
                ("approval_requirements", models.JSONField(blank=True, default=dict)),
                ("rollback_plan", models.JSONField(blank=True, default=dict)),
                ("abort_criteria", models.JSONField(blank=True, default=list)),
                ("verification_checklist", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "next_phase",
                    models.CharField(
                        default="phase_6k_single_internal_razorpay_test_mode_execution_gate",
                        max_length=96,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("audit_event_id", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_test_plans_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_test_plans_archived",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_provider_test_plans",
                        to="saas.branch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_provider_test_plans",
                        to="saas.organization",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_test_plans_rejected",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_test_plans_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["organization", "operation_type"],
                        name="saas_runtim_organiz_e29e84_idx",
                    ),
                    models.Index(
                        fields=["status", "provider_environment"],
                        name="saas_runtim_status_afa898_idx",
                    ),
                    models.Index(
                        fields=["-created_at", "status"],
                        name="saas_runtim_created_6a92c3_idx",
                    ),
                ],
            },
        ),
    ]
