# Generated by Django 5.1.15 on 2026-05-03 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saas", "0005_add_runtime_provider_test_plan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RuntimeProviderExecutionAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "execution_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("provider_type", models.CharField(db_index=True, max_length=48)),
                ("operation_type", models.CharField(db_index=True, max_length=96)),
                (
                    "provider_environment",
                    models.CharField(db_index=True, default="test", max_length=24),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prepared", "Prepared"),
                            ("blocked", "Blocked"),
                            ("ready", "Ready"),
                            ("executing", "Executing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("rolled_back", "Rolled back"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="prepared",
                        max_length=24,
                    ),
                ),
                (
                    "runtime_source",
                    models.CharField(default="env_config", max_length=32),
                ),
                ("per_org_runtime_enabled", models.BooleanField(default=False)),
                ("dry_run", models.BooleanField(default=False)),
                ("test_mode", models.BooleanField(default=True)),
                ("real_money", models.BooleanField(default=False)),
                ("real_customer_data_allowed", models.BooleanField(default=False)),
                ("amount_paise", models.PositiveIntegerField(default=100)),
                ("currency", models.CharField(default="INR", max_length=8)),
                ("provider_call_allowed", models.BooleanField(default=False)),
                ("external_call_will_be_made", models.BooleanField(default=False)),
                ("external_call_was_made", models.BooleanField(default=False)),
                ("provider_call_attempted", models.BooleanField(default=False)),
                ("business_mutation_was_made", models.BooleanField(default=False)),
                ("payment_link_created", models.BooleanField(default=False)),
                ("payment_captured", models.BooleanField(default=False)),
                ("customer_notification_sent", models.BooleanField(default=False)),
                (
                    "idempotency_key",
                    models.CharField(db_index=True, max_length=160, unique=True),
                ),
                ("receipt", models.CharField(blank=True, default="", max_length=160)),
                (
                    "request_payload_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("safe_request_summary", models.JSONField(blank=True, default=dict)),
                ("safe_response_summary", models.JSONField(blank=True, default=dict)),
                (
                    "provider_object_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                (
                    "provider_status",
                    models.CharField(blank=True, default="", max_length=48),
                ),
                ("env_readiness", models.JSONField(blank=True, default=dict)),
                (
                    "gate_decision",
                    models.CharField(blank=True, default="", max_length=48),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("rollback_plan", models.JSONField(blank=True, default=dict)),
                (
                    "rollback_status",
                    models.CharField(
                        choices=[
                            ("not_required", "Not required"),
                            ("ready", "Ready"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="not_required",
                        max_length=24,
                    ),
                ),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("rolled_back_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("audit_event_id", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_execution_attempts_archived",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_provider_execution_attempts",
                        to="saas.branch",
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_execution_attempts_executed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_provider_execution_attempts",
                        to="saas.organization",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_attempts",
                        to="saas.runtimeprovidertestplan",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_execution_attempts_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rolled_back_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_execution_attempts_rolled_back",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["plan", "status"], name="saas_runtim_plan_id_a47631_idx"
                    ),
                    models.Index(
                        fields=["organization", "status"],
                        name="saas_runtim_organiz_74a289_idx",
                    ),
                    models.Index(
                        fields=["provider_type", "status"],
                        name="saas_runtim_provide_85372d_idx",
                    ),
                    models.Index(
                        fields=["-created_at", "status"],
                        name="saas_runtim_created_ba0124_idx",
                    ),
                ],
            },
        ),
    ]
