# Generated by Django 5.1.15 on 2026-05-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saas", "0006_add_runtime_provider_execution_attempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="runtimeproviderexecutionattempt",
            name="recorded_signoff_window_end_utc",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="runtimeproviderexecutionattempt",
            name="recorded_signoff_window_start_utc",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="runtimeproviderexecutionattempt",
            name="recorded_signoff_window_valid",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
