# Generated by Django 5.1.15 on 2026-05-28 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0004_phase16b_lead_consent_fields"),
        ("orders", "0005_discountofferlog_organization_order_branch_and_more"),
        ("saas", "0007_phase7d_hotfix_director_signoff_window"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportedDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "source_label",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "problem_category",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "original_filename",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("validating", "Validating"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="ready",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.IntegerField(default=0)),
                ("valid_rows", models.IntegerField(default=0)),
                ("duplicate_rows", models.IntegerField(default=0)),
                ("invalid_rows", models.IntegerField(default=0)),
                ("imported_rows", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="saas.organization",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imported_datasets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportedDataRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.IntegerField(default=0)),
                ("raw_name", models.CharField(blank=True, default="", max_length=160)),
                ("raw_phone", models.CharField(blank=True, default="", max_length=32)),
                (
                    "normalized_phone",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=20
                    ),
                ),
                (
                    "problem_category",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("city", models.CharField(blank=True, default="", max_length=80)),
                ("state", models.CharField(blank=True, default="", max_length=60)),
                ("notes", models.TextField(blank=True, default="")),
                ("product", models.CharField(blank=True, default="", max_length=120)),
                (
                    "source_label",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("old_status", models.CharField(blank=True, default="", max_length=80)),
                (
                    "last_order_date",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("duplicate_in_file", "Duplicate in file"),
                            ("duplicate_existing", "Duplicate of existing"),
                            ("invalid_phone", "Invalid phone"),
                            ("missing_required", "Missing required"),
                            ("skipped", "Skipped"),
                            ("imported", "Imported"),
                        ],
                        db_index=True,
                        default="valid",
                        max_length=24,
                    ),
                ),
                (
                    "validation_message",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="crm.customer",
                    ),
                ),
                (
                    "linked_lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="crm.lead",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="data_imports.importeddataset",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_id", "row_number"],
            },
        ),
        migrations.CreateModel(
            name="ImportedCallingCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "problem_category",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "assigned_team",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("total_contacts", models.IntegerField(default=0)),
                ("pending_count", models.IntegerField(default=0)),
                ("completed_count", models.IntegerField(default=0)),
                ("interested_count", models.IntegerField(default=0)),
                ("not_interested_count", models.IntegerField(default=0)),
                ("callback_count", models.IntegerField(default=0)),
                ("wrong_number_count", models.IntegerField(default=0)),
                ("order_created_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imported_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="saas.organization",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns",
                        to="data_imports.importeddataset",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportedCallQueueItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned"),
                            ("called", "Called"),
                            ("callback", "Callback"),
                            ("interested", "Interested"),
                            ("not_interested", "Not interested"),
                            ("wrong_number", "Wrong number"),
                            ("order_created", "Order created"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "last_outcome",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("call_attempts", models.IntegerField(default=0)),
                ("next_follow_up_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "escalation_flag",
                    models.CharField(blank=True, default="", max_length=24),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imported_queue_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_items",
                        to="data_imports.importedcallingcampaign",
                    ),
                ),
                (
                    "linked_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="orders.order",
                    ),
                ),
                (
                    "data_row",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="queue_items",
                        to="data_imports.importeddatarow",
                    ),
                ),
            ],
            options={
                "ordering": ["campaign_id", "id"],
                "indexes": [
                    models.Index(
                        fields=["campaign", "status"], name="imp_q_camp_status_idx"
                    ),
                    models.Index(fields=["status"], name="imp_q_status_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="importeddataset",
            index=models.Index(fields=["-created_at"], name="imp_ds_created_idx"),
        ),
        migrations.AddIndex(
            model_name="importeddataset",
            index=models.Index(fields=["status"], name="imp_ds_status_idx"),
        ),
        migrations.AddIndex(
            model_name="importeddatarow",
            index=models.Index(
                fields=["dataset", "validation_status"], name="imp_row_ds_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importeddatarow",
            index=models.Index(fields=["normalized_phone"], name="imp_row_phone_idx"),
        ),
        migrations.AddIndex(
            model_name="importedcallingcampaign",
            index=models.Index(fields=["-created_at"], name="imp_camp_created_idx"),
        ),
        migrations.AddIndex(
            model_name="importedcallingcampaign",
            index=models.Index(fields=["status"], name="imp_camp_status_idx"),
        ),
    ]
