# Generated by Django 5.1.15 on 2026-04-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LearningRecording",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("agent", models.CharField(max_length=120)),
                ("duration", models.CharField(max_length=16)),
                ("date", models.CharField(max_length=40)),
                ("stage", models.CharField(max_length=80)),
                ("qa", models.IntegerField(blank=True, null=True)),
                ("compliance", models.CharField(default="Pending", max_length=80)),
                (
                    "outcome",
                    models.CharField(default="Awaiting review", max_length=120),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
    ]
