# Generated by Django 5.1.15 on 2026-05-04 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("saas", "0006_add_runtime_provider_execution_attempt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="McpClientApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("claude", "Claude"),
                            ("chatgpt", "ChatGPT"),
                            ("codex", "Codex"),
                            ("internal", "Internal"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=24,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("read_only", models.BooleanField(default=True)),
                (
                    "auth_mode",
                    models.CharField(
                        choices=[
                            ("bearer_token", "Bearer token"),
                            ("oauth_future", "OAuth (future)"),
                            ("internal_only", "Internal only"),
                        ],
                        default="internal_only",
                        max_length=24,
                    ),
                ),
                ("allowed_origins", models.JSONField(blank=True, default=list)),
                ("allowed_scopes", models.JSONField(blank=True, default=list)),
                ("denied_scopes", models.JSONField(blank=True, default=list)),
                ("rate_limit_per_minute", models.PositiveIntegerField(default=30)),
                (
                    "last_seen_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mcp_client_apps",
                        to="saas.branch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mcp_client_apps",
                        to="saas.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="McpAccessPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                ("read_only", models.BooleanField(default=True)),
                ("allowed_tools", models.JSONField(blank=True, default=list)),
                ("denied_tools", models.JSONField(blank=True, default=list)),
                ("allowed_resources", models.JSONField(blank=True, default=list)),
                ("denied_resources", models.JSONField(blank=True, default=list)),
                ("allowed_prompts", models.JSONField(blank=True, default=list)),
                ("denied_prompts", models.JSONField(blank=True, default=list)),
                ("max_output_chars", models.PositiveIntegerField(default=12000)),
                ("allow_write_tools", models.BooleanField(default=False)),
                ("allow_provider_tools", models.BooleanField(default=False)),
                (
                    "require_human_approval_for_writes",
                    models.BooleanField(default=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mcp_access_policies",
                        to="saas.branch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mcp_access_policies",
                        to="saas.organization",
                    ),
                ),
                (
                    "client_app",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_policies",
                        to="mcp_gateway.mcpclientapp",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="McpPromptDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=128, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("template", models.TextField(blank=True, default="")),
                ("variables_schema", models.JSONField(blank=True, default=dict)),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                ("requires_auth", models.BooleanField(default=True)),
                ("required_scopes", models.JSONField(blank=True, default=list)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="low",
                        max_length=16,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
                "indexes": [
                    models.Index(
                        fields=["enabled", "risk_level"],
                        name="mcp_gateway_enabled_d68731_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="McpResourceDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uri", models.CharField(db_index=True, max_length=200, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "mime_type",
                    models.CharField(default="application/json", max_length=64),
                ),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                ("read_only", models.BooleanField(default=True)),
                ("requires_auth", models.BooleanField(default=True)),
                ("required_scopes", models.JSONField(blank=True, default=list)),
                (
                    "pii_exposure_level",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("masked", "Masked"),
                            ("sensitive_blocked", "Sensitive (blocked)"),
                        ],
                        default="none",
                        max_length=24,
                    ),
                ),
                ("handler_key", models.CharField(db_index=True, max_length=128)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("uri",),
                "indexes": [
                    models.Index(
                        fields=["enabled", "read_only"],
                        name="mcp_gateway_enabled_6ceefd_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="McpToolDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=128, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("saas", "SaaS"),
                            ("audit", "Audit"),
                            ("dashboard", "Dashboard"),
                            ("whatsapp", "WhatsApp"),
                            ("razorpay", "Razorpay"),
                            ("payments", "Payments"),
                            ("crm", "CRM"),
                            ("orders", "Orders"),
                            ("shipments", "Shipments"),
                            ("agents", "Agents"),
                        ],
                        db_index=True,
                        default="system",
                        max_length=24,
                    ),
                ),
                ("handler_key", models.CharField(db_index=True, max_length=128)),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                ("read_only", models.BooleanField(default=True)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="low",
                        max_length=16,
                    ),
                ),
                ("requires_auth", models.BooleanField(default=True)),
                ("requires_org_context", models.BooleanField(default=True)),
                ("requires_human_approval", models.BooleanField(default=False)),
                ("provider_call_allowed", models.BooleanField(default=False)),
                ("business_mutation_allowed", models.BooleanField(default=False)),
                (
                    "pii_exposure_level",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("masked", "Masked"),
                            ("sensitive_blocked", "Sensitive (blocked)"),
                        ],
                        default="none",
                        max_length=24,
                    ),
                ),
                ("input_schema", models.JSONField(blank=True, default=dict)),
                ("output_schema", models.JSONField(blank=True, default=dict)),
                ("required_scopes", models.JSONField(blank=True, default=list)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("category", "name"),
                "indexes": [
                    models.Index(
                        fields=["enabled", "read_only"],
                        name="mcp_gateway_enabled_0a0127_idx",
                    ),
                    models.Index(
                        fields=["provider_call_allowed", "business_mutation_allowed"],
                        name="mcp_gateway_provide_5cf716_idx",
                    ),
                    models.Index(
                        fields=["category", "risk_level"],
                        name="mcp_gateway_categor_c39a5c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="McpToolInvocationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invocation_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("tool_name", models.CharField(db_index=True, max_length=128)),
                (
                    "tool_category",
                    models.CharField(blank=True, default="", max_length=24),
                ),
                (
                    "handler_key",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("allowed", "Allowed"),
                            ("denied", "Denied"),
                            ("blocked", "Blocked"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="allowed",
                        max_length=16,
                    ),
                ),
                (
                    "denied_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "risk_level",
                    models.CharField(blank=True, default="low", max_length=16),
                ),
                ("read_only", models.BooleanField(default=True)),
                ("provider_call_allowed", models.BooleanField(default=False)),
                ("business_mutation_allowed", models.BooleanField(default=False)),
                ("input_hash", models.CharField(blank=True, default="", max_length=64)),
                ("safe_input_summary", models.JSONField(blank=True, default=dict)),
                ("safe_output_summary", models.JSONField(blank=True, default=dict)),
                ("output_truncated", models.BooleanField(default=False)),
                ("raw_secret_exposed", models.BooleanField(default=False)),
                ("full_pii_exposed", models.BooleanField(default=False)),
                (
                    "provider_call_attempted",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "business_mutation_attempted",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "error_summary",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("request_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mcp_invocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mcp_invocations",
                        to="saas.branch",
                    ),
                ),
                (
                    "client_app",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invocations",
                        to="mcp_gateway.mcpclientapp",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mcp_invocations",
                        to="saas.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="mcpclientapp",
            index=models.Index(
                fields=["is_active", "provider"], name="mcp_gateway_is_acti_e22f20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mcpclientapp",
            index=models.Index(
                fields=["organization", "is_active"],
                name="mcp_gateway_organiz_12f913_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mcpaccesspolicy",
            index=models.Index(
                fields=["enabled", "read_only"], name="mcp_gateway_enabled_6c1102_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mcpaccesspolicy",
            index=models.Index(
                fields=["organization", "enabled"],
                name="mcp_gateway_organiz_4a2952_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mcptoolinvocationlog",
            index=models.Index(
                fields=["tool_name", "status"], name="mcp_gateway_tool_na_5dbf97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mcptoolinvocationlog",
            index=models.Index(
                fields=["-created_at", "status"], name="mcp_gateway_created_878fd2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mcptoolinvocationlog",
            index=models.Index(
                fields=["provider_call_attempted", "business_mutation_attempted"],
                name="mcp_gateway_provide_99365b_idx",
            ),
        ),
    ]
