# Generated by Django 5.1.15 on 2026-04-26 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=24)),
                ("state", models.CharField(max_length=60)),
                ("city", models.CharField(max_length=80)),
                ("language", models.CharField(max_length=40)),
                ("source", models.CharField(max_length=60)),
                ("campaign", models.CharField(max_length=120)),
                ("product_interest", models.CharField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("AI Calling Started", "AI Calling Started"),
                            ("Interested", "Interested"),
                            ("Callback Required", "Callback Required"),
                            ("Payment Link Sent", "Payment Link Sent"),
                            ("Order Punched", "Order Punched"),
                            ("Not Interested", "Not Interested"),
                            ("Invalid", "Invalid"),
                        ],
                        default="New",
                        max_length=32,
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[("Hot", "Hot"), ("Warm", "Warm"), ("Cold", "Cold")],
                        default="Warm",
                        max_length=8,
                    ),
                ),
                ("quality_score", models.IntegerField(default=0)),
                ("assignee", models.CharField(blank=True, default="", max_length=80)),
                ("duplicate", models.BooleanField(default=False)),
                (
                    "created_at_label",
                    models.CharField(default="just now", max_length=40),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["status"], name="crm_lead_status_2c1bc7_idx"),
                    models.Index(fields=["state"], name="crm_lead_state_305bf9_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=24)),
                ("state", models.CharField(max_length=60)),
                ("city", models.CharField(max_length=80)),
                ("language", models.CharField(max_length=40)),
                ("product_interest", models.CharField(max_length=80)),
                ("disease_category", models.CharField(default="", max_length=80)),
                ("lifestyle_notes", models.TextField(blank=True, default="")),
                ("objections", models.JSONField(blank=True, default=list)),
                ("ai_summary", models.TextField(blank=True, default="")),
                ("risk_flags", models.JSONField(blank=True, default=list)),
                ("reorder_probability", models.IntegerField(default=0)),
                ("satisfaction", models.IntegerField(default=0)),
                ("consent_call", models.BooleanField(default=True)),
                ("consent_whatsapp", models.BooleanField(default=True)),
                ("consent_marketing", models.BooleanField(default=False)),
                (
                    "lead",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer",
                        to="crm.lead",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
