# Generated by Django 5.1.15 on 2026-05-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_customer_branch_customer_organization_lead_branch_and_more"),
        ("saas", "0007_phase7d_hotfix_director_signoff_window"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="consent_call",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="consent_marketing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="consent_whatsapp",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="disease_category",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="lead",
            name="email",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="lead",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["phone"], name="crm_lead_phone_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["email"], name="crm_lead_email_idx"),
        ),
    ]
