# Generated by Django 5.1.15 on 2026-04-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("order_id", models.CharField(db_index=True, max_length=32)),
                ("customer", models.CharField(max_length=120)),
                ("amount", models.IntegerField(default=0)),
                (
                    "gateway",
                    models.CharField(
                        choices=[("Razorpay", "Razorpay"), ("PayU", "PayU")],
                        default="Razorpay",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Paid", "Paid"),
                            ("Pending", "Pending"),
                            ("Failed", "Failed"),
                            ("Refunded", "Refunded"),
                        ],
                        default="Pending",
                        max_length=16,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Advance", "Advance"), ("Full", "Full")],
                        default="Advance",
                        max_length=16,
                    ),
                ),
                ("time", models.CharField(default="just now", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
