# Generated by Django 5.1.15 on 2026-04-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "event_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("gateway", models.CharField(default="razorpay", max_length=16)),
                ("event_type", models.CharField(max_length=64)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-received_at",),
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="customer_email",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="payment",
            name="customer_phone",
            field=models.CharField(blank=True, default="", max_length=24),
        ),
        migrations.AddField(
            model_name="payment",
            name="gateway_reference_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="payment",
            name="raw_response",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="payment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Paid", "Paid"),
                    ("Pending", "Pending"),
                    ("Failed", "Failed"),
                    ("Refunded", "Refunded"),
                    ("Cancelled", "Cancelled"),
                    ("Expired", "Expired"),
                    ("Partial", "Partial"),
                ],
                default="Pending",
                max_length=16,
            ),
        ),
    ]
