# Generated by Django 5.1.15 on 2026-05-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_payment_branch_payment_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="RazorpayWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                (
                    "source_event_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                ("provider", models.CharField(default="razorpay", max_length=24)),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("test", "Test"),
                            ("live", "Live"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="test",
                        max_length=16,
                    ),
                ),
                ("event_name", models.CharField(db_index=True, max_length=128)),
                (
                    "entity",
                    models.CharField(blank=True, default="event", max_length=64),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "created_at_from_payload",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("signature_present", models.BooleanField(default=False)),
                ("signature_valid", models.BooleanField(db_index=True, default=False)),
                ("replay_window_valid", models.BooleanField(default=False)),
                (
                    "idempotency_status",
                    models.CharField(
                        choices=[
                            ("first_seen", "First seen"),
                            ("duplicate", "Duplicate"),
                            ("missing_event_id", "Missing event id"),
                        ],
                        db_index=True,
                        default="first_seen",
                        max_length=24,
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("blocked", "Blocked"),
                            ("verified", "Verified"),
                            ("stored", "Stored"),
                            ("duplicate", "Duplicate"),
                            ("ignored", "Ignored"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=16,
                    ),
                ),
                (
                    "processing_mode",
                    models.CharField(
                        choices=[
                            ("test_mode_record_only", "Test mode record only"),
                            ("future_mutation_disabled", "Future mutation disabled"),
                        ],
                        default="test_mode_record_only",
                        max_length=32,
                    ),
                ),
                (
                    "provider_order_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "provider_payment_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "provider_refund_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("amount_paise", models.PositiveIntegerField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, default="", max_length=8)),
                (
                    "payment_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "order_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("contains", models.JSONField(blank=True, default=list)),
                (
                    "payload_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("safe_payload_summary", models.JSONField(blank=True, default=dict)),
                ("scrubbed_keys", models.JSONField(blank=True, default=list)),
                (
                    "denied_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "business_mutation_attempted",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "business_mutation_was_made",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("customer_notification_attempted", models.BooleanField(default=False)),
                (
                    "customer_notification_sent",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("raw_secret_exposed", models.BooleanField(default=False)),
                ("full_pii_exposed", models.BooleanField(default=False)),
                ("request_headers_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("audit_event_id", models.PositiveIntegerField(blank=True, null=True)),
                ("duplicate_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-received_at",),
                "indexes": [
                    models.Index(
                        fields=["event_name", "processing_status"],
                        name="payments_ra_event_n_c85ad5_idx",
                    ),
                    models.Index(
                        fields=["-received_at", "processing_status"],
                        name="payments_ra_receive_f50265_idx",
                    ),
                    models.Index(
                        fields=["provider_order_id", "event_name"],
                        name="payments_ra_provide_4a04bc_idx",
                    ),
                    models.Index(
                        fields=[
                            "business_mutation_was_made",
                            "customer_notification_sent",
                        ],
                        name="payments_ra_busines_b42d2d_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("source_event_id__gt", "")),
                        fields=("provider", "source_event_id"),
                        name="razorpay_webhook_unique_source_event_id",
                    )
                ],
            },
        ),
    ]
