# Generated by Django 5.1.15 on 2026-05-04 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_add_razorpay_webhook_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RazorpaySandboxStatusReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_event_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                ("event_name", models.CharField(db_index=True, max_length=128)),
                (
                    "provider_environment",
                    models.CharField(default="test", max_length=16),
                ),
                (
                    "provider_order_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "provider_payment_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "provider_payment_link_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "provider_refund_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("amount_paise", models.PositiveIntegerField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, default="", max_length=8)),
                (
                    "proposed_payment_status",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "proposed_order_effect",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "proposed_review_action",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("pending_manual_review", "Pending manual review"),
                            (
                                "approved_for_future_phase6p",
                                "Approved for future Phase 6P",
                            ),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="proposed",
                        max_length=32,
                    ),
                ),
                ("synthetic_eligible", models.BooleanField(default=False)),
                ("manual_review_required", models.BooleanField(default=True)),
                ("mutation_allowed_in_phase6o", models.BooleanField(default=False)),
                (
                    "business_mutation_was_made",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "customer_notification_sent",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("provider_call_attempted", models.BooleanField(default=False)),
                ("shipment_effect_allowed", models.BooleanField(default=False)),
                ("discount_effect_allowed", models.BooleanField(default=False)),
                ("rollback_required", models.BooleanField(default=True)),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("safety_invariants", models.JSONField(blank=True, default=dict)),
                ("manual_review_checklist", models.JSONField(blank=True, default=list)),
                ("rollback_plan", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "archive_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase6o_review_archives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "razorpay_webhook_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sandbox_status_reviews",
                        to="payments.razorpaywebhookevent",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase6o_review_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase6o_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "event_name"],
                        name="payments_ra_status_f89a82_idx",
                    ),
                    models.Index(
                        fields=["-created_at", "status"],
                        name="payments_ra_created_8d7665_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("razorpay_webhook_event", "proposed_review_action"),
                        name="razorpay_sandbox_review_unique_event_action",
                    )
                ],
            },
        ),
    ]
