# Generated by Django 5.1.15 on 2026-05-04 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_phase6o_razorpay_sandbox_status_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RazorpaySandboxPaidStatusLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_event_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                ("event_name", models.CharField(db_index=True, max_length=128)),
                (
                    "provider_environment",
                    models.CharField(default="test", max_length=16),
                ),
                (
                    "provider_order_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "provider_payment_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "provider_payment_link_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "provider_refund_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("amount_paise", models.PositiveIntegerField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, default="", max_length=8)),
                (
                    "sandbox_payment_status",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "sandbox_order_effect",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "current_state",
                    models.CharField(
                        blank=True, db_index=True, default="initial", max_length=64
                    ),
                ),
                (
                    "previous_state",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("mutation_count", models.PositiveIntegerField(default=0)),
                ("synthetic_eligible", models.BooleanField(default=True)),
                (
                    "business_mutation_was_made",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("real_order_mutation_was_made", models.BooleanField(default=False)),
                ("real_payment_mutation_was_made", models.BooleanField(default=False)),
                (
                    "customer_notification_sent",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("provider_call_attempted", models.BooleanField(default=False)),
                ("rollback_required", models.BooleanField(default=True)),
                ("rolled_back", models.BooleanField(db_index=True, default=False)),
                ("rolled_back_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "razorpay_webhook_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sandbox_paid_status_ledger_rows",
                        to="payments.razorpaywebhookevent",
                    ),
                ),
                (
                    "review",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sandbox_paid_status_ledger",
                        to="payments.razorpaysandboxstatusreview",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RazorpaySandboxPaidStatusMutationAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_event_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                ("event_name", models.CharField(db_index=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prepared", "Prepared"),
                            ("blocked", "Blocked"),
                            ("executed", "Executed"),
                            ("rolled_back", "Rolled back"),
                            ("failed", "Failed"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="prepared",
                        max_length=16,
                    ),
                ),
                (
                    "requested_action",
                    models.CharField(
                        choices=[
                            ("apply_sandbox_status", "Apply sandbox status"),
                            ("rollback_sandbox_status", "Rollback sandbox status"),
                        ],
                        default="apply_sandbox_status",
                        max_length=32,
                    ),
                ),
                (
                    "proposed_payment_status",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "proposed_order_effect",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("before_state", models.JSONField(blank=True, default=dict)),
                ("after_state", models.JSONField(blank=True, default=dict)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("safety_invariants", models.JSONField(blank=True, default=dict)),
                ("confirmation_provided", models.BooleanField(default=False)),
                (
                    "director_signoff_text",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("rolled_back_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "idempotency_key",
                    models.CharField(db_index=True, max_length=160, unique=True),
                ),
                (
                    "business_mutation_was_made",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("real_order_mutation_was_made", models.BooleanField(default=False)),
                ("real_payment_mutation_was_made", models.BooleanField(default=False)),
                ("customer_notification_sent", models.BooleanField(default=False)),
                ("provider_call_attempted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase6p_attempts_archived",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase6p_attempts_executed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ledger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mutation_attempts",
                        to="payments.razorpaysandboxpaidstatusledger",
                    ),
                ),
                (
                    "razorpay_webhook_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sandbox_paid_status_mutation_attempts",
                        to="payments.razorpaywebhookevent",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase6p_attempt_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sandbox_paid_status_mutation_attempts",
                        to="payments.razorpaysandboxstatusreview",
                    ),
                ),
                (
                    "rolled_back_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase6p_attempts_rolled_back",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="razorpaysandboxpaidstatusledger",
            name="last_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_last_attempt_for",
                to="payments.razorpaysandboxpaidstatusmutationattempt",
            ),
        ),
        migrations.AddIndex(
            model_name="razorpaysandboxpaidstatusmutationattempt",
            index=models.Index(
                fields=["status", "event_name"], name="payments_ra_status_0669b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="razorpaysandboxpaidstatusmutationattempt",
            index=models.Index(
                fields=["-created_at", "status"], name="payments_ra_created_9d9ed7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="razorpaysandboxpaidstatusledger",
            index=models.Index(
                fields=["event_name", "current_state"],
                name="payments_ra_event_n_80c0cf_idx",
            ),
        ),
    ]
