# Generated by Django 5.1.15 on 2026-05-06 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_phase6q_payment_order_workflow_gate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RazorpayPaymentDispatchReadinessGate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_event_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                ("event_name", models.CharField(db_index=True, max_length=128)),
                (
                    "provider_environment",
                    models.CharField(default="test", max_length=16),
                ),
                (
                    "provider_order_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "provider_payment_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "provider_payment_link_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("amount_paise", models.PositiveIntegerField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, default="", max_length=8)),
                (
                    "proposed_payment_status",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "proposed_order_status",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "proposed_order_effect",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "proposed_whatsapp_action",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "proposed_courier_action",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "proposed_dispatch_readiness_action",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("blocked", "Blocked"),
                            ("pending_manual_review", "Pending manual review"),
                            (
                                "approved_for_future_phase6s",
                                "Approved for future Phase 6S",
                            ),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("phase6q_gate_approved", models.BooleanField(default=False)),
                ("phase6p_execution_verified", models.BooleanField(default=False)),
                ("phase6p_rollback_verified", models.BooleanField(default=False)),
                ("synthetic_eligible", models.BooleanField(default=False)),
                ("manual_review_required", models.BooleanField(default=True)),
                (
                    "dispatch_readiness_allowed_in_phase6r",
                    models.BooleanField(default=False),
                ),
                (
                    "real_order_mutation_was_made",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "real_payment_mutation_was_made",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("shipment_mutation_was_made", models.BooleanField(default=False)),
                ("shipment_created", models.BooleanField(db_index=True, default=False)),
                (
                    "whatsapp_message_created",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "whatsapp_message_queued",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("customer_notification_sent", models.BooleanField(default=False)),
                ("meta_cloud_call_attempted", models.BooleanField(default=False)),
                ("delhivery_call_attempted", models.BooleanField(default=False)),
                ("razorpay_call_attempted", models.BooleanField(default=False)),
                ("provider_call_attempted", models.BooleanField(default=False)),
                ("rollback_required", models.BooleanField(default=True)),
                (
                    "idempotency_key",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("safety_invariants", models.JSONField(blank=True, default=dict)),
                (
                    "whatsapp_readiness_checklist",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "courier_readiness_checklist",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "dispatch_readiness_checklist",
                    models.JSONField(blank=True, default=list),
                ),
                ("rollback_plan", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "archive_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase6r_readiness_archives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "razorpay_webhook_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_dispatch_readiness_gates",
                        to="payments.razorpaywebhookevent",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase6r_readiness_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase6r_readiness_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_dispatch_readiness_gates",
                        to="payments.razorpaysandboxpaidstatusmutationattempt",
                    ),
                ),
                (
                    "source_ledger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_dispatch_readiness_gates",
                        to="payments.razorpaysandboxpaidstatusledger",
                    ),
                ),
                (
                    "source_review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_dispatch_readiness_gates",
                        to="payments.razorpaysandboxstatusreview",
                    ),
                ),
                (
                    "source_workflow_gate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_dispatch_readiness_gates",
                        to="payments.razorpaypaymentorderworkflowgate",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "event_name"],
                        name="payments_ra_status_c2c07d_idx",
                    ),
                    models.Index(
                        fields=["-created_at", "status"],
                        name="payments_ra_created_8fecdd_idx",
                    ),
                ],
            },
        ),
    ]
