# Generated by Django 5.1.15 on 2026-05-06 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_phase6r_payment_dispatch_readiness"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RazorpayPaymentDispatchPilotPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_event_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                ("event_name", models.CharField(db_index=True, max_length=128)),
                (
                    "provider_environment",
                    models.CharField(default="test", max_length=16),
                ),
                (
                    "provider_order_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "provider_payment_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "provider_payment_link_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("amount_paise", models.PositiveIntegerField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, default="", max_length=8)),
                (
                    "proposed_pilot_scope",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "proposed_payment_status",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "proposed_order_status",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "proposed_order_effect",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "proposed_whatsapp_action",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "proposed_courier_action",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "proposed_dispatch_action",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "pilot_mode",
                    models.CharField(
                        choices=[
                            ("planning_only", "Planning only"),
                            ("internal_staff_only", "Internal staff only"),
                        ],
                        default="planning_only",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("blocked", "Blocked"),
                            ("pending_manual_review", "Pending manual review"),
                            (
                                "approved_for_future_phase6t",
                                "Approved for future Phase 6T",
                            ),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("internal_only", models.BooleanField(default=True)),
                ("max_pilot_orders", models.PositiveIntegerField(default=1)),
                ("max_amount_paise", models.PositiveIntegerField(default=100)),
                (
                    "allowed_customer_scope",
                    models.CharField(
                        blank=True, default="internal_staff_only", max_length=64
                    ),
                ),
                ("allowed_staff_cohort", models.JSONField(blank=True, default=list)),
                ("allowed_event_names", models.JSONField(blank=True, default=list)),
                (
                    "whatsapp_template_candidates",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "courier_precheck_candidates",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "dispatch_precheck_candidates",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "kill_switch_requirements",
                    models.JSONField(blank=True, default=dict),
                ),
                ("approval_requirements", models.JSONField(blank=True, default=dict)),
                ("rollback_plan", models.JSONField(blank=True, default=dict)),
                ("abort_criteria", models.JSONField(blank=True, default=list)),
                ("verification_checklist", models.JSONField(blank=True, default=list)),
                ("manual_review_required", models.BooleanField(default=True)),
                (
                    "pilot_execution_allowed_in_phase6s",
                    models.BooleanField(default=False),
                ),
                ("live_send_allowed_in_phase6s", models.BooleanField(default=False)),
                (
                    "courier_booking_allowed_in_phase6s",
                    models.BooleanField(default=False),
                ),
                (
                    "provider_call_allowed_in_phase6s",
                    models.BooleanField(default=False),
                ),
                (
                    "real_order_mutation_was_made",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "real_payment_mutation_was_made",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("shipment_mutation_was_made", models.BooleanField(default=False)),
                ("shipment_created", models.BooleanField(db_index=True, default=False)),
                ("awb_created", models.BooleanField(db_index=True, default=False)),
                (
                    "whatsapp_message_created",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "whatsapp_message_queued",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("customer_notification_sent", models.BooleanField(default=False)),
                ("meta_cloud_call_attempted", models.BooleanField(default=False)),
                ("delhivery_call_attempted", models.BooleanField(default=False)),
                ("razorpay_call_attempted", models.BooleanField(default=False)),
                ("provider_call_attempted", models.BooleanField(default=False)),
                ("rollback_required", models.BooleanField(default=True)),
                (
                    "idempotency_key",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("safety_invariants", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "archive_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase6s_pilot_plan_archives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "razorpay_webhook_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_dispatch_pilot_plans",
                        to="payments.razorpaywebhookevent",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase6s_pilot_plan_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase6s_pilot_plan_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_dispatch_pilot_plans",
                        to="payments.razorpaysandboxpaidstatusmutationattempt",
                    ),
                ),
                (
                    "source_ledger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_dispatch_pilot_plans",
                        to="payments.razorpaysandboxpaidstatusledger",
                    ),
                ),
                (
                    "source_readiness_gate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_dispatch_pilot_plans",
                        to="payments.razorpaypaymentdispatchreadinessgate",
                    ),
                ),
                (
                    "source_review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_dispatch_pilot_plans",
                        to="payments.razorpaysandboxstatusreview",
                    ),
                ),
                (
                    "source_workflow_gate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_dispatch_pilot_plans",
                        to="payments.razorpaypaymentorderworkflowgate",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "event_name"],
                        name="payments_ra_status_80f43e_idx",
                    ),
                    models.Index(
                        fields=["-created_at", "status"],
                        name="payments_ra_created_b07f90_idx",
                    ),
                ],
            },
        ),
    ]
