# Generated by Django 5.1.15 on 2026-05-06 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_phase6s_payment_dispatch_pilot_plan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RazorpayPhase6FinalAuditLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_event_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                ("event_name", models.CharField(db_index=True, max_length=128)),
                (
                    "provider_environment",
                    models.CharField(default="test", max_length=16),
                ),
                ("amount_paise", models.PositiveIntegerField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, default="", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("blocked", "Blocked"),
                            ("pending_manual_review", "Pending manual review"),
                            (
                                "locked_for_future_controlled_pilot_review",
                                "Locked for future controlled pilot review",
                            ),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=64,
                    ),
                ),
                ("phase6n_verified", models.BooleanField(default=False)),
                ("phase6o_verified", models.BooleanField(default=False)),
                ("phase6p_verified", models.BooleanField(default=False)),
                ("phase6q_verified", models.BooleanField(default=False)),
                ("phase6r_verified", models.BooleanField(default=False)),
                ("phase6s_verified", models.BooleanField(default=False)),
                ("full_chain_verified", models.BooleanField(default=False)),
                ("final_audit_passed", models.BooleanField(default=False)),
                ("director_signoff_required", models.BooleanField(default=True)),
                ("kill_switch_required", models.BooleanField(default=True)),
                ("rollback_required", models.BooleanField(default=True)),
                (
                    "future_execution_allowed_by_phase6t",
                    models.BooleanField(default=False),
                ),
                (
                    "controlled_pilot_execution_allowed_in_phase6t",
                    models.BooleanField(default=False),
                ),
                ("manual_review_required", models.BooleanField(default=True)),
                ("internal_only", models.BooleanField(default=True)),
                ("max_pilot_orders", models.PositiveIntegerField(default=1)),
                ("max_amount_paise", models.PositiveIntegerField(default=100)),
                (
                    "real_order_mutation_was_made",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "real_payment_mutation_was_made",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("shipment_mutation_was_made", models.BooleanField(default=False)),
                ("shipment_created", models.BooleanField(db_index=True, default=False)),
                ("awb_created", models.BooleanField(db_index=True, default=False)),
                (
                    "whatsapp_message_created",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "whatsapp_message_queued",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("customer_notification_sent", models.BooleanField(default=False)),
                ("meta_cloud_call_attempted", models.BooleanField(default=False)),
                ("delhivery_call_attempted", models.BooleanField(default=False)),
                ("razorpay_call_attempted", models.BooleanField(default=False)),
                ("provider_call_attempted", models.BooleanField(default=False)),
                ("env_flag_flip_detected", models.BooleanField(default=False)),
                ("raw_secret_exposed", models.BooleanField(default=False)),
                ("full_pii_exposed", models.BooleanField(default=False)),
                ("phase6n_snapshot", models.JSONField(blank=True, default=dict)),
                ("phase6o_snapshot", models.JSONField(blank=True, default=dict)),
                ("phase6p_snapshot", models.JSONField(blank=True, default=dict)),
                ("phase6q_snapshot", models.JSONField(blank=True, default=dict)),
                ("phase6r_snapshot", models.JSONField(blank=True, default=dict)),
                ("phase6s_snapshot", models.JSONField(blank=True, default=dict)),
                ("final_attestation", models.JSONField(blank=True, default=dict)),
                (
                    "director_signoff_contract",
                    models.JSONField(blank=True, default=dict),
                ),
                ("kill_switch_contract", models.JSONField(blank=True, default=dict)),
                ("rollback_contract", models.JSONField(blank=True, default=dict)),
                ("abort_criteria", models.JSONField(blank=True, default=list)),
                ("operator_checklist", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("safety_invariants", models.JSONField(blank=True, default=dict)),
                (
                    "idempotency_key",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "archive_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase6t_final_audit_archives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase6t_final_audit_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase6_final_audit_locks",
                        to="payments.razorpaysandboxpaidstatusmutationattempt",
                    ),
                ),
                (
                    "source_event_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase6_final_audit_locks",
                        to="payments.razorpaywebhookevent",
                    ),
                ),
                (
                    "source_ledger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase6_final_audit_locks",
                        to="payments.razorpaysandboxpaidstatusledger",
                    ),
                ),
                (
                    "source_pilot_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase6_final_audit_locks",
                        to="payments.razorpaypaymentdispatchpilotplan",
                    ),
                ),
                (
                    "source_readiness_gate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase6_final_audit_locks",
                        to="payments.razorpaypaymentdispatchreadinessgate",
                    ),
                ),
                (
                    "source_review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase6_final_audit_locks",
                        to="payments.razorpaysandboxstatusreview",
                    ),
                ),
                (
                    "source_workflow_gate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase6_final_audit_locks",
                        to="payments.razorpaypaymentorderworkflowgate",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "event_name"],
                        name="payments_ra_status_555dec_idx",
                    ),
                    models.Index(
                        fields=["-created_at", "status"],
                        name="payments_ra_created_81b772_idx",
                    ),
                ],
            },
        ),
    ]
