# Generated by Django 5.1.15 on 2026-05-06 12:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_razorpayphase6finalauditlock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RazorpayControlledPilotExecutionGate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_event_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                ("event_name", models.CharField(db_index=True, max_length=128)),
                (
                    "provider_environment",
                    models.CharField(default="test", max_length=16),
                ),
                ("amount_paise", models.PositiveIntegerField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, default="", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("blocked", "Blocked"),
                            ("pending_manual_review", "Pending manual review"),
                            (
                                "approved_for_future_phase7c_execution_review",
                                "Approved for future Phase 7C execution review",
                            ),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=64,
                    ),
                ),
                ("phase6t_lock_verified", models.BooleanField(default=False)),
                ("phase6s_pilot_plan_verified", models.BooleanField(default=False)),
                ("phase6r_readiness_verified", models.BooleanField(default=False)),
                ("phase6q_workflow_gate_verified", models.BooleanField(default=False)),
                ("phase6p_attempt_verified", models.BooleanField(default=False)),
                ("phase6o_review_verified", models.BooleanField(default=False)),
                ("phase6m_event_verified", models.BooleanField(default=False)),
                ("full_chain_verified", models.BooleanField(default=False)),
                ("dry_run_passed", models.BooleanField(db_index=True, default=False)),
                (
                    "rollback_dry_run_passed",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("manual_review_required", models.BooleanField(default=True)),
                ("internal_only", models.BooleanField(default=True)),
                ("max_pilot_orders", models.PositiveIntegerField(default=1)),
                ("max_amount_paise", models.PositiveIntegerField(default=100)),
                (
                    "controlled_pilot_execution_allowed_in_phase7b",
                    models.BooleanField(default=False),
                ),
                (
                    "live_execution_allowed_in_phase7b",
                    models.BooleanField(default=False),
                ),
                (
                    "provider_call_allowed_in_phase7b",
                    models.BooleanField(default=False),
                ),
                (
                    "business_mutation_allowed_in_phase7b",
                    models.BooleanField(default=False),
                ),
                (
                    "customer_notification_allowed_in_phase7b",
                    models.BooleanField(default=False),
                ),
                (
                    "whatsapp_send_allowed_in_phase7b",
                    models.BooleanField(default=False),
                ),
                (
                    "whatsapp_queue_allowed_in_phase7b",
                    models.BooleanField(default=False),
                ),
                (
                    "courier_booking_allowed_in_phase7b",
                    models.BooleanField(default=False),
                ),
                (
                    "shipment_creation_allowed_in_phase7b",
                    models.BooleanField(default=False),
                ),
                ("awb_creation_allowed_in_phase7b", models.BooleanField(default=False)),
                (
                    "frontend_execution_allowed_in_phase7b",
                    models.BooleanField(default=False),
                ),
                (
                    "api_execution_allowed_in_phase7b",
                    models.BooleanField(default=False),
                ),
                (
                    "real_order_mutation_was_made",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "real_payment_mutation_was_made",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("shipment_mutation_was_made", models.BooleanField(default=False)),
                ("shipment_created", models.BooleanField(db_index=True, default=False)),
                ("awb_created", models.BooleanField(db_index=True, default=False)),
                (
                    "whatsapp_message_created",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "whatsapp_message_queued",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("customer_notification_sent", models.BooleanField(default=False)),
                ("meta_cloud_call_attempted", models.BooleanField(default=False)),
                ("delhivery_call_attempted", models.BooleanField(default=False)),
                ("razorpay_call_attempted", models.BooleanField(default=False)),
                ("provider_call_attempted", models.BooleanField(default=False)),
                ("env_flag_flip_detected", models.BooleanField(default=False)),
                ("raw_secret_exposed", models.BooleanField(default=False)),
                ("full_pii_exposed", models.BooleanField(default=False)),
                (
                    "idempotency_key",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("safety_invariants", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "archive_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7b_controlled_pilot_gate_archives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7b_controlled_pilot_gate_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7b_controlled_pilot_gate_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="controlled_pilot_execution_gates",
                        to="payments.razorpaysandboxpaidstatusmutationattempt",
                    ),
                ),
                (
                    "source_event_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="controlled_pilot_execution_gates",
                        to="payments.razorpaywebhookevent",
                    ),
                ),
                (
                    "source_final_audit_lock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="controlled_pilot_execution_gates",
                        to="payments.razorpayphase6finalauditlock",
                    ),
                ),
                (
                    "source_ledger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="controlled_pilot_execution_gates",
                        to="payments.razorpaysandboxpaidstatusledger",
                    ),
                ),
                (
                    "source_pilot_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="controlled_pilot_execution_gates",
                        to="payments.razorpaypaymentdispatchpilotplan",
                    ),
                ),
                (
                    "source_readiness_gate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="controlled_pilot_execution_gates",
                        to="payments.razorpaypaymentdispatchreadinessgate",
                    ),
                ),
                (
                    "source_review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="controlled_pilot_execution_gates",
                        to="payments.razorpaysandboxstatusreview",
                    ),
                ),
                (
                    "source_workflow_gate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="controlled_pilot_execution_gates",
                        to="payments.razorpaypaymentorderworkflowgate",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RazorpayControlledPilotGateDryRunRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("phase6t_verified", models.BooleanField(default=False)),
                ("phase6s_verified", models.BooleanField(default=False)),
                ("phase6r_verified", models.BooleanField(default=False)),
                ("phase6q_verified", models.BooleanField(default=False)),
                ("phase6p_verified", models.BooleanField(default=False)),
                ("phase6o_verified", models.BooleanField(default=False)),
                ("phase6m_verified", models.BooleanField(default=False)),
                ("chain_pass", models.BooleanField(db_index=True, default=False)),
                (
                    "evaluated_safety_invariants",
                    models.JSONField(blank=True, default=dict),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "idempotency_key",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dry_run_records",
                        to="payments.razorpaycontrolledpilotexecutiongate",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RazorpayControlledPilotGateRollbackDryRunRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "dry_run_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("rehearsal_steps", models.JSONField(blank=True, default=list)),
                ("env_flag_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "evaluated_safety_invariants",
                    models.JSONField(blank=True, default=dict),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "idempotency_key",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rollback_dry_run_records",
                        to="payments.razorpaycontrolledpilotexecutiongate",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="razorpaycontrolledpilotexecutiongate",
            index=models.Index(
                fields=["status", "event_name"], name="payments_ra_status_494d55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="razorpaycontrolledpilotexecutiongate",
            index=models.Index(
                fields=["-created_at", "status"], name="payments_ra_created_7fc8e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="razorpaycontrolledpilotgatedryrunrecord",
            index=models.Index(
                fields=["gate", "-created_at"], name="payments_ra_gate_id_cc01f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="razorpaycontrolledpilotgatedryrunrecord",
            index=models.Index(
                fields=["chain_pass", "-created_at"],
                name="payments_ra_chain_p_871cf1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="razorpaycontrolledpilotgaterollbackdryrunrecord",
            index=models.Index(
                fields=["gate", "-created_at"], name="payments_ra_gate_id_05f99d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="razorpaycontrolledpilotgaterollbackdryrunrecord",
            index=models.Index(
                fields=["dry_run_status", "-created_at"],
                name="payments_ra_dry_run_8e5914_idx",
            ),
        ),
    ]
