# Generated by Django 5.1.15 on 2026-05-07 10:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0011_phase7b_controlled_pilot_gate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RazorpayControlledPilotExecutionAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("blocked", "Blocked"),
                            ("pending_director_signoff", "Pending Director sign-off"),
                            ("approved_for_one_shot_run", "Approved for one-shot run"),
                            ("executed", "Executed"),
                            ("failed", "Failed"),
                            ("rolled_back", "Rolled back"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=64,
                    ),
                ),
                (
                    "provider_environment",
                    models.CharField(default="test", max_length=16),
                ),
                ("amount_paise", models.PositiveIntegerField(default=100)),
                ("currency", models.CharField(default="INR", max_length=8)),
                ("receipt", models.CharField(blank=True, default="", max_length=128)),
                (
                    "idempotency_key",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                ("safe_request_summary", models.JSONField(blank=True, default=dict)),
                ("safe_response_summary", models.JSONField(blank=True, default=dict)),
                (
                    "provider_object_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "provider_status",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "rollback_status",
                    models.CharField(
                        choices=[
                            ("not_required", "Not required"),
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("rolled_back_at", models.DateTimeField(blank=True, null=True)),
                ("rollback_reason", models.TextField(blank=True, default="")),
                ("director_signoff_text", models.TextField(blank=True, default="")),
                ("kill_switch_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "env_flag_snapshot_at_start",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "env_flag_snapshot_at_end",
                    models.JSONField(blank=True, default=dict),
                ),
                ("before_counts", models.JSONField(blank=True, default=dict)),
                ("after_counts", models.JSONField(blank=True, default=dict)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("safety_invariants", models.JSONField(blank=True, default=dict)),
                ("business_mutation_was_made", models.BooleanField(default=False)),
                ("payment_link_created", models.BooleanField(default=False)),
                ("payment_captured", models.BooleanField(default=False)),
                ("payment_refunded", models.BooleanField(default=False)),
                ("customer_notification_sent", models.BooleanField(default=False)),
                (
                    "whatsapp_message_created",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "whatsapp_message_queued",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "whatsapp_lifecycle_event_created",
                    models.BooleanField(default=False),
                ),
                ("meta_cloud_call_attempted", models.BooleanField(default=False)),
                ("delhivery_call_attempted", models.BooleanField(default=False)),
                ("shipment_created", models.BooleanField(db_index=True, default=False)),
                ("awb_created", models.BooleanField(db_index=True, default=False)),
                (
                    "real_order_mutation_was_made",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "real_payment_mutation_was_made",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("customer_mutation_was_made", models.BooleanField(default=False)),
                ("lead_mutation_was_made", models.BooleanField(default=False)),
                (
                    "discount_offer_log_mutation_was_made",
                    models.BooleanField(default=False),
                ),
                ("mcp_tool_called", models.BooleanField(default=False)),
                (
                    "kill_switch_disabled_during_attempt",
                    models.BooleanField(default=False),
                ),
                ("env_flag_flipped_outside_window", models.BooleanField(default=False)),
                ("raw_secret_exposed", models.BooleanField(default=False)),
                ("full_pii_exposed", models.BooleanField(default=False)),
                ("provider_call_attempted", models.BooleanField(default=False)),
                ("razorpay_call_attempted", models.BooleanField(default=False)),
                ("idempotency_lock_acquired", models.BooleanField(default=False)),
                ("rollback_recorded", models.BooleanField(default=False)),
                ("director_signoff_present", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "archive_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7d_execution_archives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7d_execution_executors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7d_execution_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7d_execution_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_event_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7d_execution_attempts",
                        to="payments.razorpaywebhookevent",
                    ),
                ),
                (
                    "source_phase6t_lock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7d_execution_attempts",
                        to="payments.razorpayphase6finalauditlock",
                    ),
                ),
                (
                    "source_phase7b_gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7d_execution_attempts",
                        to="payments.razorpaycontrolledpilotexecutiongate",
                    ),
                ),
                (
                    "source_pilot_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7d_execution_attempts",
                        to="payments.razorpaypaymentdispatchpilotplan",
                    ),
                ),
                (
                    "source_readiness_gate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7d_execution_attempts",
                        to="payments.razorpaypaymentdispatchreadinessgate",
                    ),
                ),
                (
                    "source_sandbox_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7d_execution_attempts",
                        to="payments.razorpaysandboxpaidstatusmutationattempt",
                    ),
                ),
                (
                    "source_sandbox_review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7d_execution_attempts",
                        to="payments.razorpaysandboxstatusreview",
                    ),
                ),
                (
                    "source_workflow_gate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7d_execution_attempts",
                        to="payments.razorpaypaymentorderworkflowgate",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RazorpayControlledPilotExecutionRollback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "rollback_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("rollback_reason", models.TextField(blank=True, default="")),
                (
                    "env_flag_presence_at_rollback",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "evaluated_safety_invariants",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "provider_object_id_recorded",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("recovery_notes", models.TextField(blank=True, default="")),
                (
                    "idempotency_key",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rollback_records",
                        to="payments.razorpaycontrolledpilotexecutionattempt",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="razorpaycontrolledpilotexecutionattempt",
            index=models.Index(
                fields=["status", "-created_at"], name="payments_ra_status_f202bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="razorpaycontrolledpilotexecutionattempt",
            index=models.Index(
                fields=["provider_object_id", "-created_at"],
                name="payments_ra_provide_29c8e5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="razorpaycontrolledpilotexecutionrollback",
            index=models.Index(
                fields=["attempt", "-created_at"], name="payments_ra_attempt_611add_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="razorpaycontrolledpilotexecutionrollback",
            index=models.Index(
                fields=["rollback_status", "-created_at"],
                name="payments_ra_rollbac_ca1526_idx",
            ),
        ),
    ]
