# Generated by Django 5.1.15 on 2026-05-08 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0014_phase7d_hotfix_director_signoff_window"),
        ("saas", "0007_phase7d_hotfix_director_signoff_window"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RazorpayCourierReadinessGate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_manual_review", "Pending manual review"),
                            (
                                "approved_for_future_phase7g_or_courier_execution_review",
                                "Approved for future Phase 7G or courier execution review",
                            ),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=64,
                    ),
                ),
                (
                    "delhivery_mode_at_prepare",
                    models.CharField(default="mock", max_length=16),
                ),
                ("delhivery_env_token_present", models.BooleanField(default=False)),
                ("delhivery_env_base_url_present", models.BooleanField(default=False)),
                (
                    "delhivery_env_pickup_location_present",
                    models.BooleanField(default=False),
                ),
                (
                    "delhivery_env_return_address_present",
                    models.BooleanField(default=False),
                ),
                (
                    "source_phase7d_signoff_window_validation_status",
                    models.CharField(
                        choices=[
                            ("valid_structured_window", "Valid structured window"),
                            (
                                "failed_or_legacy_free_text",
                                "Failed or legacy free text",
                            ),
                            ("not_applicable", "Not applicable"),
                        ],
                        default="not_applicable",
                        max_length=48,
                    ),
                ),
                ("phase7d_hotfix_1_present", models.BooleanField(default=False)),
                ("dry_run_passed", models.BooleanField(db_index=True, default=False)),
                ("dry_run_failed_reasons", models.JSONField(blank=True, default=list)),
                (
                    "rollback_dry_run_passed",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "rollback_dry_run_failed_reasons",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "kill_switch_snapshot_at_each_step",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "env_flag_snapshot_at_each_step",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "safety_invariants_snapshot",
                    models.JSONField(blank=True, default=dict),
                ),
                ("before_counts", models.JSONField(blank=True, default=dict)),
                ("after_counts", models.JSONField(blank=True, default=dict)),
                (
                    "idempotency_key",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "next_action",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("reject_reason", models.TextField(blank=True, default="")),
                ("archive_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7f_courier_gate_archives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7f_courier_gates",
                        to="saas.branch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7f_courier_gates",
                        to="saas.organization",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7f_courier_gate_rejections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7f_courier_gate_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7f_courier_gate_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_phase6t_lock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7f_courier_gates",
                        to="payments.razorpayphase6finalauditlock",
                    ),
                ),
                (
                    "source_phase7b_gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7f_courier_gates",
                        to="payments.razorpaycontrolledpilotexecutiongate",
                    ),
                ),
                (
                    "source_phase7d_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7f_courier_gates",
                        to="payments.razorpaycontrolledpilotexecutionattempt",
                    ),
                ),
                (
                    "source_phase7e_gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7f_courier_gates",
                        to="payments.razorpaywhatsappinternalnotificationgate",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RazorpayCourierReadinessDryRunRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("dry_run", "Dry run"),
                            ("rollback_dry_run", "Rollback dry run"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                (
                    "safety_invariants_snapshot",
                    models.JSONField(blank=True, default=dict),
                ),
                ("before_counts", models.JSONField(blank=True, default=dict)),
                ("after_counts", models.JSONField(blank=True, default=dict)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dry_run_records",
                        to="payments.razorpaycourierreadinessgate",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="razorpaycourierreadinessgate",
            index=models.Index(
                fields=["status", "-created_at"], name="payments_ra_status_c8f82b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="razorpaycourierreadinessgate",
            index=models.Index(
                fields=["source_phase7e_gate", "-created_at"],
                name="payments_ra_source__6fd8a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="razorpaycourierreadinessgate",
            index=models.Index(
                fields=["source_phase7d_attempt", "-created_at"],
                name="payments_ra_source__b42802_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="razorpaycourierreadinessgate",
            index=models.Index(
                fields=["phase7d_hotfix_1_present", "status"],
                name="payments_ra_phase7d_0bd5fd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="razorpaycourierreadinessdryrunrecord",
            index=models.Index(
                fields=["gate", "kind", "-created_at"],
                name="payments_ra_gate_id_1c347d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="razorpaycourierreadinessdryrunrecord",
            index=models.Index(
                fields=["status", "-created_at"], name="payments_ra_status_9b31d3_idx"
            ),
        ),
    ]
