# Generated by Django 5.1.15 on 2026-05-08 10:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0015_phase7f_courier_readiness_gate"),
        ("saas", "0007_phase7d_hotfix_director_signoff_window"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RazorpayCourierExecutionAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_director_signoff", "Pending Director sign-off"),
                            (
                                "approved_for_one_shot_courier_test_or_live_review",
                                "Approved for one-shot courier test/mock review",
                            ),
                            ("executed", "Executed"),
                            ("failed", "Failed"),
                            ("rolled_back_recorded", "Rolled back (record-only)"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=64,
                    ),
                ),
                (
                    "delhivery_mode_at_each_step",
                    models.JSONField(blank=True, default=dict),
                ),
                ("delhivery_env_token_present", models.BooleanField(default=False)),
                ("delhivery_env_base_url_present", models.BooleanField(default=False)),
                (
                    "delhivery_env_pickup_location_present",
                    models.BooleanField(default=False),
                ),
                (
                    "delhivery_env_return_address_present",
                    models.BooleanField(default=False),
                ),
                (
                    "kill_switch_snapshot_at_each_step",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "env_flag_snapshot_at_each_step",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "safety_invariants_snapshot",
                    models.JSONField(blank=True, default=dict),
                ),
                ("before_counts", models.JSONField(blank=True, default=dict)),
                ("after_counts", models.JSONField(blank=True, default=dict)),
                (
                    "synthetic_order_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "synthetic_payload_summary",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "idempotency_key",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                ("idempotency_lock_acquired", models.BooleanField(default=False)),
                (
                    "provider_object_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "provider_status",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("safe_request_summary", models.JSONField(blank=True, default=dict)),
                ("safe_response_summary", models.JSONField(blank=True, default=dict)),
                (
                    "provider_call_attempted",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "delhivery_call_attempted",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("awb_created", models.BooleanField(db_index=True, default=False)),
                ("shipment_created", models.BooleanField(db_index=True, default=False)),
                (
                    "business_mutation_was_made",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "real_order_mutation_was_made",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "real_payment_mutation_was_made",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "real_shipment_mutation_was_made",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "customer_notification_sent",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "recorded_signoff_window_valid",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "recorded_signoff_window_start_utc",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "recorded_signoff_window_end_utc",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("director_signoff_text", models.TextField(blank=True, default="")),
                ("director_signoff_present", models.BooleanField(default=False)),
                (
                    "operator_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "confirm_one_shot_courier_execution",
                    models.BooleanField(default=False),
                ),
                (
                    "mode_acknowledgement",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "rollback_record_only_acknowledged",
                    models.BooleanField(default=False),
                ),
                (
                    "rollback_status",
                    models.CharField(
                        choices=[
                            ("not_required", "Not required"),
                            ("pending", "Pending"),
                            (
                                "recorded_only_no_provider_cancel",
                                "Recorded only (no provider cancel)",
                            ),
                            (
                                "cancellation_attempted_separately",
                                "Cancellation attempted separately",
                            ),
                        ],
                        default="not_required",
                        max_length=40,
                    ),
                ),
                ("rolled_back_at", models.DateTimeField(blank=True, null=True)),
                ("rollback_reason", models.TextField(blank=True, default="")),
                ("archive_reason", models.TextField(blank=True, default="")),
                ("reject_reason", models.TextField(blank=True, default="")),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "next_action",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("audit_event_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7g_courier_execution_archives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7g_courier_execution_attempts",
                        to="saas.branch",
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7g_courier_execution_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7g_courier_execution_attempts",
                        to="saas.organization",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7g_courier_execution_rejections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7g_courier_execution_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7g_courier_execution_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rolled_back_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7g_courier_execution_rollbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_phase6t_lock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7g_courier_execution_attempts",
                        to="payments.razorpayphase6finalauditlock",
                    ),
                ),
                (
                    "source_phase7b_gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7g_courier_execution_attempts",
                        to="payments.razorpaycontrolledpilotexecutiongate",
                    ),
                ),
                (
                    "source_phase7d_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7g_courier_execution_attempts",
                        to="payments.razorpaycontrolledpilotexecutionattempt",
                    ),
                ),
                (
                    "source_phase7e_gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7g_courier_execution_attempts",
                        to="payments.razorpaywhatsappinternalnotificationgate",
                    ),
                ),
                (
                    "source_phase7f_gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7g_courier_execution_attempts",
                        to="payments.razorpaycourierreadinessgate",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RazorpayCourierExecutionRollback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "rollback_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            (
                                "recorded_only_no_provider_cancel",
                                "Recorded only (no provider cancel)",
                            ),
                            (
                                "cancellation_attempted_separately",
                                "Cancellation attempted separately",
                            ),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=40,
                    ),
                ),
                ("rollback_reason", models.TextField(blank=True, default="")),
                ("cancellation_attempted", models.BooleanField(default=False)),
                (
                    "cancellation_attempted_by_command",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "provider_object_id_recorded",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "env_flag_presence_at_rollback",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "evaluated_safety_invariants",
                    models.JSONField(blank=True, default=dict),
                ),
                ("recovery_notes", models.TextField(blank=True, default="")),
                (
                    "idempotency_key",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rollback_records",
                        to="payments.razorpaycourierexecutionattempt",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="razorpaycourierexecutionattempt",
            index=models.Index(
                fields=["status", "-created_at"], name="payments_ra_status_b6e8f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="razorpaycourierexecutionattempt",
            index=models.Index(
                fields=["source_phase7f_gate", "-created_at"],
                name="payments_ra_source__03a743_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="razorpaycourierexecutionattempt",
            index=models.Index(
                fields=["source_phase7d_attempt", "-created_at"],
                name="payments_ra_source__8e5b7f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="razorpaycourierexecutionattempt",
            index=models.Index(
                fields=["provider_object_id", "-created_at"],
                name="payments_ra_provide_717ae3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="razorpaycourierexecutionrollback",
            index=models.Index(
                fields=["attempt", "-created_at"], name="payments_ra_attempt_f603a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="razorpaycourierexecutionrollback",
            index=models.Index(
                fields=["rollback_status", "-created_at"],
                name="payments_ra_rollbac_652bca_idx",
            ),
        ),
    ]
