# Generated by Django 5.1.15 on 2026-05-11 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0016_phase7g_courier_execution_attempt"),
        ("saas", "0007_phase7d_hotfix_director_signoff_window"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RazorpayCourierExecutionEvidenceLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_manual_review", "Pending manual review"),
                            ("locked", "Locked"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=40,
                    ),
                ),
                (
                    "provider_object_id_snapshot",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "provider_status_snapshot",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "recorded_signoff_window_valid_snapshot",
                    models.BooleanField(blank=True, null=True),
                ),
                ("executed_at_snapshot", models.DateTimeField(blank=True, null=True)),
                (
                    "rolled_back_at_snapshot",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "rollback_status_snapshot",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("shipment_created_snapshot", models.BooleanField(default=False)),
                (
                    "business_mutation_was_made_snapshot",
                    models.BooleanField(default=False),
                ),
                (
                    "customer_notification_sent_snapshot",
                    models.BooleanField(default=False),
                ),
                ("evidence_json", models.JSONField(blank=True, default=dict)),
                (
                    "reviewed_by_username",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_reason", models.TextField(blank=True, default="")),
                ("reject_reason", models.TextField(blank=True, default="")),
                ("archive_reason", models.TextField(blank=True, default="")),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "next_action",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7h_evidence_locks",
                        to="saas.branch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7h_evidence_locks",
                        to="saas.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7h_evidence_lock_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_phase6t_lock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7h_evidence_locks",
                        to="payments.razorpayphase6finalauditlock",
                    ),
                ),
                (
                    "source_phase7b_gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7h_evidence_locks",
                        to="payments.razorpaycontrolledpilotexecutiongate",
                    ),
                ),
                (
                    "source_phase7d_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7h_evidence_locks",
                        to="payments.razorpaycontrolledpilotexecutionattempt",
                    ),
                ),
                (
                    "source_phase7e_gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7h_evidence_locks",
                        to="payments.razorpaywhatsappinternalnotificationgate",
                    ),
                ),
                (
                    "source_phase7f_gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7h_evidence_locks",
                        to="payments.razorpaycourierreadinessgate",
                    ),
                ),
                (
                    "source_phase7g_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7h_evidence_locks",
                        to="payments.razorpaycourierexecutionattempt",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="payments_ra_status_56dd46_idx",
                    ),
                    models.Index(
                        fields=["source_phase7g_attempt", "-created_at"],
                        name="payments_ra_source__0f536c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RazorpayWhatsAppInternalSendAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_director_signoff", "Pending Director sign-off"),
                            (
                                "approved_for_internal_one_shot_send",
                                "Approved for internal one-shot send",
                            ),
                            ("executed", "Executed"),
                            ("failed", "Failed"),
                            (
                                "rollback_recorded",
                                "Rollback recorded (no provider call)",
                            ),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=48,
                    ),
                ),
                (
                    "template_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "template_language",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "allowed_recipient_last4",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                (
                    "recipient_scope",
                    models.CharField(
                        choices=[
                            (
                                "internal_staff_allow_list",
                                "Internal staff allow-list only",
                            )
                        ],
                        default="internal_staff_allow_list",
                        max_length=40,
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "provider_status",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("safe_request_summary", models.JSONField(blank=True, default=dict)),
                ("safe_response_summary", models.JSONField(blank=True, default=dict)),
                (
                    "recorded_signoff_window_valid",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "recorded_signoff_window_start_utc",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "recorded_signoff_window_end_utc",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "provider_call_attempted",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "meta_cloud_call_attempted",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "whatsapp_message_created",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "whatsapp_message_queued",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "customer_notification_sent",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "business_mutation_was_made",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "real_customer_allowed",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "real_customer_phone_used",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("claim_vault_grounded", models.BooleanField(default=False)),
                (
                    "idempotency_key",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                ("idempotency_lock_acquired", models.BooleanField(default=False)),
                ("director_signoff_text", models.TextField(blank=True, default="")),
                ("director_signoff_present", models.BooleanField(default=False)),
                (
                    "operator_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("confirm_internal_whatsapp_send", models.BooleanField(default=False)),
                ("rollback_reason", models.TextField(blank=True, default="")),
                ("reject_reason", models.TextField(blank=True, default="")),
                ("archive_reason", models.TextField(blank=True, default="")),
                (
                    "env_flag_snapshot_at_each_step",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "kill_switch_snapshot_at_each_step",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "safety_invariants_snapshot",
                    models.JSONField(blank=True, default=dict),
                ),
                ("before_counts", models.JSONField(blank=True, default=dict)),
                ("after_counts", models.JSONField(blank=True, default=dict)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "next_action",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("rolled_back_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("audit_event_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7e_live_internal_send_attempts",
                        to="saas.branch",
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7e_live_internal_send_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7e_live_internal_send_attempts",
                        to="saas.organization",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7e_live_internal_send_rejections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7e_live_internal_send_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7e_live_internal_send_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rolled_back_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7e_live_internal_send_rollbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_phase6t_lock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7e_live_internal_send_attempts",
                        to="payments.razorpayphase6finalauditlock",
                    ),
                ),
                (
                    "source_phase7b_gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7e_live_internal_send_attempts",
                        to="payments.razorpaycontrolledpilotexecutiongate",
                    ),
                ),
                (
                    "source_phase7d_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7e_live_internal_send_attempts",
                        to="payments.razorpaycontrolledpilotexecutionattempt",
                    ),
                ),
                (
                    "source_phase7e_gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7e_live_internal_send_attempts",
                        to="payments.razorpaywhatsappinternalnotificationgate",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="payments_ra_status_056a85_idx",
                    ),
                    models.Index(
                        fields=["source_phase7e_gate", "-created_at"],
                        name="payments_ra_source__fb2883_idx",
                    ),
                    models.Index(
                        fields=["provider_message_id", "-created_at"],
                        name="payments_ra_provide_626ca8_idx",
                    ),
                ],
            },
        ),
    ]
