# Generated by Django 5.1.15 on 2026-05-11 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0017_phase7h_evidence_lock_and_phase7e_live_internal_send"),
        ("saas", "0007_phase7d_hotfix_director_signoff_window"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RazorpayPhase7FinalAuditLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_manual_review", "Pending manual review"),
                            ("locked", "Locked"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=40,
                    ),
                ),
                (
                    "phase7d_attempt_status_snapshot",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "phase7d_provider_object_id_snapshot",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "phase7d_business_mutation_was_made_snapshot",
                    models.BooleanField(default=False),
                ),
                (
                    "phase7d_customer_notification_sent_snapshot",
                    models.BooleanField(default=False),
                ),
                (
                    "phase7e_live_attempt_status_snapshot",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "phase7e_live_provider_message_id_snapshot",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "phase7e_live_provider_status_snapshot",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "phase7e_live_template_name_snapshot",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "phase7e_live_template_language_snapshot",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "phase7e_live_allowed_recipient_last4_snapshot",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                (
                    "phase7e_live_recipient_scope_snapshot",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "phase7e_live_whatsapp_message_created_snapshot",
                    models.BooleanField(default=False),
                ),
                (
                    "phase7e_live_whatsapp_message_queued_snapshot",
                    models.BooleanField(default=False),
                ),
                (
                    "phase7e_live_customer_notification_sent_snapshot",
                    models.BooleanField(default=False),
                ),
                (
                    "phase7e_live_business_mutation_was_made_snapshot",
                    models.BooleanField(default=False),
                ),
                (
                    "phase7e_live_real_customer_phone_used_snapshot",
                    models.BooleanField(default=False),
                ),
                (
                    "phase7e_live_claim_vault_grounded_snapshot",
                    models.BooleanField(default=False),
                ),
                (
                    "phase7e_live_recorded_signoff_window_valid_snapshot",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "phase7g_attempt_status_snapshot",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "phase7g_provider_object_id_snapshot",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "phase7g_provider_status_snapshot",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "phase7g_rollback_status_snapshot",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("phase7g_awb_created_snapshot", models.BooleanField(default=False)),
                (
                    "phase7g_shipment_created_snapshot",
                    models.BooleanField(default=False),
                ),
                (
                    "phase7g_business_mutation_was_made_snapshot",
                    models.BooleanField(default=False),
                ),
                (
                    "phase7g_customer_notification_sent_snapshot",
                    models.BooleanField(default=False),
                ),
                (
                    "phase7g_recorded_signoff_window_valid_snapshot",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "phase7h_evidence_lock_status_snapshot",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "phase7h_provider_object_id_snapshot",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "phase7h_shipment_created_snapshot",
                    models.BooleanField(default=False),
                ),
                (
                    "phase7h_business_mutation_was_made_snapshot",
                    models.BooleanField(default=False),
                ),
                (
                    "phase7h_customer_notification_sent_snapshot",
                    models.BooleanField(default=False),
                ),
                ("evidence_json", models.JSONField(blank=True, default=dict)),
                (
                    "reviewed_by_username",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_reason", models.TextField(blank=True, default="")),
                ("reject_reason", models.TextField(blank=True, default="")),
                ("archive_reason", models.TextField(blank=True, default="")),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "next_action",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7i_final_audit_locks",
                        to="saas.branch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7i_final_audit_locks",
                        to="saas.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase7i_final_audit_lock_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_phase6t_lock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7i_final_audit_locks",
                        to="payments.razorpayphase6finalauditlock",
                    ),
                ),
                (
                    "source_phase7d_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7i_final_audit_locks",
                        to="payments.razorpaycontrolledpilotexecutionattempt",
                    ),
                ),
                (
                    "source_phase7e_live_send_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7i_final_audit_locks",
                        to="payments.razorpaywhatsappinternalsendattempt",
                    ),
                ),
                (
                    "source_phase7g_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7i_final_audit_locks",
                        to="payments.razorpaycourierexecutionattempt",
                    ),
                ),
                (
                    "source_phase7h_evidence_lock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase7i_final_audit_locks",
                        to="payments.razorpaycourierexecutionevidencelock",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="payments_ra_status_6803fb_idx",
                    ),
                    models.Index(
                        fields=["source_phase7h_evidence_lock", "-created_at"],
                        name="payments_ra_source__7e057a_idx",
                    ),
                    models.Index(
                        fields=["source_phase7g_attempt", "-created_at"],
                        name="payments_ra_source__ccd848_idx",
                    ),
                ],
            },
        ),
    ]
