# Generated by Django 5.1.15 on 2026-05-11 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0018_phase7i_final_audit_lock"),
        ("saas", "0007_phase7d_hotfix_director_signoff_window"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RazorpayPaymentOrderMutationSandboxGate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_manual_review", "Pending manual review"),
                            ("dry_run_passed", "Dry-run passed"),
                            (
                                "approved_for_future_phase8b_review",
                                "Approved for future Phase 8B review",
                            ),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=40,
                    ),
                ),
                ("sandbox_only", models.BooleanField(default=True)),
                ("real_business_mutation_allowed", models.BooleanField(default=False)),
                ("real_order_mutation_allowed", models.BooleanField(default=False)),
                ("real_payment_mutation_allowed", models.BooleanField(default=False)),
                ("customer_notification_allowed", models.BooleanField(default=False)),
                ("whatsapp_allowed", models.BooleanField(default=False)),
                ("courier_allowed", models.BooleanField(default=False)),
                ("synthetic_order_required", models.BooleanField(default=True)),
                ("manual_review_required", models.BooleanField(default=True)),
                (
                    "claim_vault_not_required_for_payment_status",
                    models.BooleanField(default=True),
                ),
                (
                    "reviewed_by_username",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_reason", models.TextField(blank=True, default="")),
                ("reject_reason", models.TextField(blank=True, default="")),
                ("archive_reason", models.TextField(blank=True, default="")),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "next_action",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("evidence_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase8a_payment_order_mutation_sandbox_gates",
                        to="saas.branch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase8a_payment_order_mutation_sandbox_gates",
                        to="saas.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase8a_payment_order_mutation_sandbox_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_phase7d_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase8a_payment_order_mutation_sandbox_gates",
                        to="payments.razorpaycontrolledpilotexecutionattempt",
                    ),
                ),
                (
                    "source_phase7i_lock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase8a_payment_order_mutation_sandbox_gates",
                        to="payments.razorpayphase7finalauditlock",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RazorpayPaymentOrderMutationDryRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proposed_source_payment_reference",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "proposed_target_order_reference",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "proposed_target_order_is_synthetic",
                    models.BooleanField(default=True),
                ),
                (
                    "proposed_old_order_status",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "proposed_new_order_status",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "proposed_old_payment_status",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "proposed_new_payment_status",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("would_mutate_order", models.BooleanField(default=False)),
                ("would_mutate_payment", models.BooleanField(default=False)),
                (
                    "would_send_customer_notification",
                    models.BooleanField(default=False),
                ),
                ("would_send_whatsapp", models.BooleanField(default=False)),
                ("would_call_courier", models.BooleanField(default=False)),
                ("before_counts", models.JSONField(blank=True, default=dict)),
                ("after_counts", models.JSONField(blank=True, default=dict)),
                ("count_deltas", models.JSONField(blank=True, default=dict)),
                ("passed", models.BooleanField(db_index=True, default=False)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("rollback_reason", models.TextField(blank=True, default="")),
                ("rolled_back_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "source_phase7d_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase8a_payment_order_mutation_dry_runs",
                        to="payments.razorpaycontrolledpilotexecutionattempt",
                    ),
                ),
                (
                    "source_phase7i_lock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase8a_payment_order_mutation_dry_runs",
                        to="payments.razorpayphase7finalauditlock",
                    ),
                ),
                (
                    "gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dry_runs",
                        to="payments.razorpaypaymentordermutationsandboxgate",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="razorpaypaymentordermutationsandboxgate",
            index=models.Index(
                fields=["status", "-created_at"], name="payments_ra_status_650f78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="razorpaypaymentordermutationsandboxgate",
            index=models.Index(
                fields=["source_phase7i_lock", "-created_at"],
                name="payments_ra_source__a1360e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="razorpaypaymentordermutationdryrun",
            index=models.Index(
                fields=["gate", "-created_at"], name="payments_ra_gate_id_22be2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="razorpaypaymentordermutationdryrun",
            index=models.Index(
                fields=["passed", "-created_at"], name="payments_ra_passed_610133_idx"
            ),
        ),
    ]
