# Generated by Django 5.1.15 on 2026-05-12 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0020_phase8b_payment_order_mutation_review_gate"),
        ("saas", "0007_phase7d_hotfix_director_signoff_window"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RazorpayPaymentOrderControlledMutationGate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_manual_review", "Pending manual review"),
                            ("dry_run_passed", "Dry-run passed"),
                            (
                                "approved_for_one_shot_controlled_mutation",
                                "Approved for one-shot controlled mutation",
                            ),
                            ("executed", "Executed"),
                            ("rolled_back", "Rolled back"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=64,
                    ),
                ),
                ("controlled_mutation_only", models.BooleanField(default=True)),
                ("real_customer_allowed", models.BooleanField(default=False)),
                ("customer_notification_allowed", models.BooleanField(default=False)),
                ("whatsapp_allowed", models.BooleanField(default=False)),
                ("courier_allowed", models.BooleanField(default=False)),
                ("provider_call_allowed", models.BooleanField(default=False)),
                ("shipment_creation_allowed", models.BooleanField(default=False)),
                ("payment_capture_allowed", models.BooleanField(default=False)),
                ("refund_allowed", models.BooleanField(default=False)),
                ("rollback_required", models.BooleanField(default=True)),
                ("director_signoff_required", models.BooleanField(default=True)),
                ("structured_utc_window_required", models.BooleanField(default=True)),
                (
                    "source_payment_reference_snapshot",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "target_order_reference_snapshot",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "target_payment_reference_snapshot",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "proposed_old_order_status",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "proposed_new_order_status",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "proposed_old_payment_status",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "proposed_new_payment_status",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("dry_run_passed", models.BooleanField(default=False)),
                ("before_counts", models.JSONField(blank=True, default=dict)),
                ("after_counts", models.JSONField(blank=True, default=dict)),
                ("count_deltas", models.JSONField(blank=True, default=dict)),
                (
                    "reviewed_by_username",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_reason", models.TextField(blank=True, default="")),
                ("reject_reason", models.TextField(blank=True, default="")),
                ("archive_reason", models.TextField(blank=True, default="")),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "next_action",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("evidence_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase8c_controlled_mutation_gates",
                        to="saas.branch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase8c_controlled_mutation_gates",
                        to="saas.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase8c_controlled_mutation_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_phase7d_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase8c_controlled_mutation_gates",
                        to="payments.razorpaycontrolledpilotexecutionattempt",
                    ),
                ),
                (
                    "source_phase7i_lock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase8c_controlled_mutation_gates",
                        to="payments.razorpayphase7finalauditlock",
                    ),
                ),
                (
                    "source_phase8a_gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase8c_controlled_mutation_gates",
                        to="payments.razorpaypaymentordermutationsandboxgate",
                    ),
                ),
                (
                    "source_phase8b_gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase8c_controlled_mutation_gates",
                        to="payments.razorpaypaymentordermutationreviewgate",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RazorpayPaymentOrderControlledMutationAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_order_id",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "target_payment_id",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "target_order_reference",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "target_payment_reference",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "payment_reference_snapshot",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_director_signoff", "Pending Director sign-off"),
                            (
                                "approved_for_one_shot_mutation",
                                "Approved for one-shot mutation",
                            ),
                            ("executed", "Executed"),
                            ("rolled_back", "Rolled back"),
                            ("failed", "Failed"),
                            ("blocked", "Blocked"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=40,
                    ),
                ),
                (
                    "old_order_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "new_order_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "old_payment_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "new_payment_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("order_mutation_was_made", models.BooleanField(default=False)),
                ("payment_mutation_was_made", models.BooleanField(default=False)),
                ("business_mutation_was_made", models.BooleanField(default=False)),
                ("customer_notification_sent", models.BooleanField(default=False)),
                ("whatsapp_sent", models.BooleanField(default=False)),
                ("courier_called", models.BooleanField(default=False)),
                ("provider_call_attempted", models.BooleanField(default=False)),
                ("shipment_created", models.BooleanField(default=False)),
                ("before_counts", models.JSONField(blank=True, default=dict)),
                ("after_counts", models.JSONField(blank=True, default=dict)),
                ("count_deltas", models.JSONField(blank=True, default=dict)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "director_signoff_text_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "recorded_signoff_window_start_utc",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "recorded_signoff_window_end_utc",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("recorded_signoff_window_valid", models.BooleanField(default=False)),
                (
                    "operator_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_phase8b_gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase8c_controlled_mutation_attempts",
                        to="payments.razorpaypaymentordermutationreviewgate",
                    ),
                ),
                (
                    "gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="payments.razorpaypaymentordercontrolledmutationgate",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RazorpayPaymentOrderControlledMutationRollback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("rollback_recorded", "Rollback recorded"),
                            ("rollback_failed", "Rollback failed"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "restored_order_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "restored_payment_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("rollback_was_made", models.BooleanField(default=False)),
                ("customer_notification_sent", models.BooleanField(default=False)),
                ("whatsapp_sent", models.BooleanField(default=False)),
                ("courier_called", models.BooleanField(default=False)),
                ("provider_call_attempted", models.BooleanField(default=False)),
                ("before_counts", models.JSONField(blank=True, default=dict)),
                ("after_counts", models.JSONField(blank=True, default=dict)),
                ("count_deltas", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField(blank=True, default="")),
                ("rolled_back_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rollbacks",
                        to="payments.razorpaypaymentordercontrolledmutationattempt",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="razorpaypaymentordercontrolledmutationgate",
            index=models.Index(
                fields=["status", "-created_at"], name="payments_ra_status_76d737_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="razorpaypaymentordercontrolledmutationgate",
            index=models.Index(
                fields=["source_phase8b_gate", "-created_at"],
                name="payments_ra_source__5330e2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="razorpaypaymentordercontrolledmutationattempt",
            index=models.Index(
                fields=["gate", "-created_at"], name="payments_ra_gate_id_acef65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="razorpaypaymentordercontrolledmutationattempt",
            index=models.Index(
                fields=["status", "-created_at"], name="payments_ra_status_1ce54b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="razorpaypaymentordercontrolledmutationattempt",
            index=models.Index(
                fields=["target_order_id", "target_payment_id"],
                name="payments_ra_target__9fe267_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="razorpaypaymentordercontrolledmutationrollback",
            index=models.Index(
                fields=["attempt", "-created_at"], name="payments_ra_attempt_a5e2a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="razorpaypaymentordercontrolledmutationrollback",
            index=models.Index(
                fields=["status", "-created_at"], name="payments_ra_status_d1741c_idx"
            ),
        ),
    ]
