# Generated by Django 5.1.15 on 2026-05-12 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0021_phase8c_controlled_payment_order_mutation"),
        ("saas", "0007_phase7d_hotfix_director_signoff_window"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RazorpayPaymentOrderControlledMutationEvidenceLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_manual_review", "Pending manual review"),
                            ("locked", "Locked"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "phase8c_gate_status_snapshot",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "phase8c_attempt_status_snapshot",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "phase8c_attempt_executed_at_snapshot",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "recorded_signoff_window_valid_snapshot",
                    models.BooleanField(default=False),
                ),
                (
                    "target_order_id_snapshot",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "target_payment_id_snapshot",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "target_order_reference_snapshot",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "target_payment_reference_snapshot",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "old_order_status_snapshot",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "executed_order_status_snapshot",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "final_order_status_snapshot",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "old_payment_status_snapshot",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "executed_payment_status_snapshot",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "final_payment_status_snapshot",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "order_mutation_was_made_snapshot",
                    models.BooleanField(default=False),
                ),
                (
                    "payment_mutation_was_made_snapshot",
                    models.BooleanField(default=False),
                ),
                (
                    "business_mutation_was_made_snapshot",
                    models.BooleanField(default=False),
                ),
                ("rollback_completed_snapshot", models.BooleanField(default=False)),
                ("final_db_restored_snapshot", models.BooleanField(default=False)),
                ("phase8d_calls_razorpay_snapshot", models.BooleanField(default=False)),
                (
                    "phase8d_calls_meta_cloud_snapshot",
                    models.BooleanField(default=False),
                ),
                (
                    "phase8d_calls_delhivery_snapshot",
                    models.BooleanField(default=False),
                ),
                ("phase8d_sends_whatsapp_snapshot", models.BooleanField(default=False)),
                (
                    "phase8d_sends_customer_notification_snapshot",
                    models.BooleanField(default=False),
                ),
                (
                    "phase8d_creates_shipment_snapshot",
                    models.BooleanField(default=False),
                ),
                (
                    "phase8d_captures_payment_snapshot",
                    models.BooleanField(default=False),
                ),
                (
                    "phase8d_refunds_payment_snapshot",
                    models.BooleanField(default=False),
                ),
                ("before_counts_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "after_execute_counts_snapshot",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "after_rollback_counts_snapshot",
                    models.JSONField(blank=True, default=dict),
                ),
                ("count_deltas_snapshot", models.JSONField(blank=True, default=dict)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "next_action",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("evidence_json", models.JSONField(blank=True, default=dict)),
                (
                    "reviewed_by_username",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_reason", models.TextField(blank=True, default="")),
                ("reject_reason", models.TextField(blank=True, default="")),
                ("archive_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase8d_controlled_mutation_evidence_locks",
                        to="saas.branch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase8d_controlled_mutation_evidence_locks",
                        to="saas.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase8d_controlled_mutation_evidence_lock_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_phase7d_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase8d_evidence_locks",
                        to="payments.razorpaycontrolledpilotexecutionattempt",
                    ),
                ),
                (
                    "source_phase7i_lock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase8d_evidence_locks",
                        to="payments.razorpayphase7finalauditlock",
                    ),
                ),
                (
                    "source_phase8a_gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase8d_evidence_locks",
                        to="payments.razorpaypaymentordermutationsandboxgate",
                    ),
                ),
                (
                    "source_phase8b_gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase8d_evidence_locks",
                        to="payments.razorpaypaymentordermutationreviewgate",
                    ),
                ),
                (
                    "source_phase8c_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase8d_evidence_locks",
                        to="payments.razorpaypaymentordercontrolledmutationattempt",
                    ),
                ),
                (
                    "source_phase8c_gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase8d_evidence_locks",
                        to="payments.razorpaypaymentordercontrolledmutationgate",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="payments_ra_status_cffa3e_idx",
                    ),
                    models.Index(
                        fields=["source_phase8c_gate", "-created_at"],
                        name="payments_ra_source__8b1cb6_idx",
                    ),
                    models.Index(
                        fields=["source_phase8c_attempt", "-created_at"],
                        name="payments_ra_source__412499_idx",
                    ),
                ],
            },
        ),
    ]
