# Generated by Django 5.1.15 on 2026-05-13 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0022_phase8d_controlled_mutation_evidence_lock"),
        ("saas", "0007_phase7d_hotfix_director_signoff_window"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RazorpayRealCustomerPaymentOrderMutationCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(db_index=True, max_length=32)),
                ("payment_id", models.CharField(db_index=True, max_length=32)),
                (
                    "order_customer_name_masked",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "order_phone_last4",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                (
                    "payment_gateway",
                    models.CharField(blank=True, default="", max_length=24),
                ),
                (
                    "payment_reference",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "order_current_payment_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "payment_current_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("order_amount", models.IntegerField(default=0)),
                ("payment_amount", models.IntegerField(default=0)),
                ("is_real_customer_candidate", models.BooleanField(default=True)),
                (
                    "candidate_validation_passed",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "candidate_validation_blockers",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "candidate_validation_warnings",
                    models.JSONField(blank=True, default=list),
                ),
                ("consent_required", models.BooleanField(default=True)),
                ("customer_notification_allowed", models.BooleanField(default=False)),
                ("whatsapp_allowed", models.BooleanField(default=False)),
                ("courier_allowed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RazorpayRealCustomerPaymentOrderMutationPilotGate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_manual_review", "Pending manual review"),
                            ("dry_run_passed", "Dry-run passed"),
                            (
                                "approved_for_future_phase8f_real_customer_controlled_mutation",
                                "Approved for future Phase 8F real customer controlled mutation",
                            ),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=80,
                    ),
                ),
                ("real_customer_pilot_only", models.BooleanField(default=True)),
                ("real_mutation_allowed", models.BooleanField(default=False)),
                ("real_order_mutation_allowed", models.BooleanField(default=False)),
                ("real_payment_mutation_allowed", models.BooleanField(default=False)),
                ("customer_notification_allowed", models.BooleanField(default=False)),
                ("whatsapp_allowed", models.BooleanField(default=False)),
                ("courier_allowed", models.BooleanField(default=False)),
                ("provider_call_allowed", models.BooleanField(default=False)),
                ("phase8f_required", models.BooleanField(default=True)),
                ("manual_review_required", models.BooleanField(default=True)),
                ("director_signoff_required", models.BooleanField(default=True)),
                ("rollback_required", models.BooleanField(default=True)),
                (
                    "candidate_order_id_snapshot",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "candidate_payment_id_snapshot",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "candidate_order_current_status_snapshot",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "candidate_payment_current_status_snapshot",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "proposed_order_new_status_snapshot",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "proposed_payment_new_status_snapshot",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("dry_run_passed", models.BooleanField(default=False)),
                ("before_counts", models.JSONField(blank=True, default=dict)),
                ("after_counts", models.JSONField(blank=True, default=dict)),
                ("count_deltas", models.JSONField(blank=True, default=dict)),
                ("evidence_json", models.JSONField(blank=True, default=dict)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "next_action",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "reviewed_by_username",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_reason", models.TextField(blank=True, default="")),
                ("reject_reason", models.TextField(blank=True, default="")),
                ("archive_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase8e_real_customer_pilot_gates",
                        to="saas.branch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase8e_real_customer_pilot_gates",
                        to="saas.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase8e_real_customer_pilot_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_phase7i_lock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase8e_pilot_gates",
                        to="payments.razorpayphase7finalauditlock",
                    ),
                ),
                (
                    "source_phase8a_gate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase8e_pilot_gates",
                        to="payments.razorpaypaymentordermutationsandboxgate",
                    ),
                ),
                (
                    "source_phase8b_gate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase8e_pilot_gates",
                        to="payments.razorpaypaymentordermutationreviewgate",
                    ),
                ),
                (
                    "source_phase8c_gate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase8e_pilot_gates",
                        to="payments.razorpaypaymentordercontrolledmutationgate",
                    ),
                ),
                (
                    "source_phase8d_lock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase8e_pilot_gates",
                        to="payments.razorpaypaymentordercontrolledmutationevidencelock",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RazorpayRealCustomerPaymentOrderMutationPilotDryRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_order_id",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "target_payment_id",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "old_order_payment_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "new_order_payment_status_candidate",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "old_payment_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "new_payment_status_candidate",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("would_mutate_order", models.BooleanField(default=False)),
                ("would_mutate_payment", models.BooleanField(default=False)),
                (
                    "would_send_customer_notification",
                    models.BooleanField(default=False),
                ),
                ("would_send_whatsapp", models.BooleanField(default=False)),
                ("would_call_courier", models.BooleanField(default=False)),
                ("would_create_shipment", models.BooleanField(default=False)),
                ("would_call_provider", models.BooleanField(default=False)),
                ("before_counts", models.JSONField(blank=True, default=dict)),
                ("after_counts", models.JSONField(blank=True, default=dict)),
                ("count_deltas", models.JSONField(blank=True, default=dict)),
                ("passed", models.BooleanField(db_index=True, default=False)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dry_runs",
                        to="payments.razorpayrealcustomerpaymentordermutationcandidate",
                    ),
                ),
                (
                    "gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dry_runs",
                        to="payments.razorpayrealcustomerpaymentordermutationpilotgate",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="razorpayrealcustomerpaymentordermutationcandidate",
            name="gate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidates",
                to="payments.razorpayrealcustomerpaymentordermutationpilotgate",
            ),
        ),
        migrations.AddIndex(
            model_name="razorpayrealcustomerpaymentordermutationpilotgate",
            index=models.Index(
                fields=["status", "-created_at"], name="payments_ra_status_f4f899_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="razorpayrealcustomerpaymentordermutationpilotgate",
            index=models.Index(
                fields=["source_phase8d_lock", "-created_at"],
                name="payments_ra_source__57f6dd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="razorpayrealcustomerpaymentordermutationpilotdryrun",
            index=models.Index(
                fields=["gate", "-created_at"], name="payments_ra_gate_id_5db0cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="razorpayrealcustomerpaymentordermutationpilotdryrun",
            index=models.Index(
                fields=["candidate", "-created_at"],
                name="payments_ra_candida_3b80c0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="razorpayrealcustomerpaymentordermutationpilotdryrun",
            index=models.Index(
                fields=["passed", "-created_at"], name="payments_ra_passed_160576_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="razorpayrealcustomerpaymentordermutationcandidate",
            index=models.Index(
                fields=["gate", "-created_at"], name="payments_ra_gate_id_3158d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="razorpayrealcustomerpaymentordermutationcandidate",
            index=models.Index(
                fields=["order_id", "payment_id"], name="payments_ra_order_i_a2fc66_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="razorpayrealcustomerpaymentordermutationcandidate",
            constraint=models.UniqueConstraint(
                fields=("gate", "order_id", "payment_id"),
                name="phase8e_pilot_gate_unique_candidate_order_payment",
            ),
        ),
    ]
