# Generated by Django 5.1.15 on 2026-05-13 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0024_phase8f_real_customer_controlled_mutation"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="razorpayrealcustomerpaymentordercontrolledmutationattempt",
            new_name="p8f_atmpt_gate_created_idx",
            old_name="payments_ra_gate_id_c59e88_idx",
        ),
        migrations.RenameIndex(
            model_name="razorpayrealcustomerpaymentordercontrolledmutationattempt",
            new_name="p8f_atmpt_status_created_idx",
            old_name="payments_ra_status_414c3d_idx",
        ),
        migrations.RenameIndex(
            model_name="razorpayrealcustomerpaymentordercontrolledmutationattempt",
            new_name="p8f_atmpt_target_pair_idx",
            old_name="payments_ra_target__c918bc_idx",
        ),
        migrations.RenameIndex(
            model_name="razorpayrealcustomerpaymentordercontrolledmutationgate",
            new_name="p8f_gate_status_created_idx",
            old_name="payments_ra_status_1dfcd3_idx",
        ),
        migrations.RenameIndex(
            model_name="razorpayrealcustomerpaymentordercontrolledmutationgate",
            new_name="p8f_gate_src8e_created_idx",
            old_name="payments_ra_source__d15080_idx",
        ),
        migrations.RenameIndex(
            model_name="razorpayrealcustomerpaymentordercontrolledmutationgate",
            new_name="p8f_gate_target_pair_idx",
            old_name="payments_ra_selecte_56c873_idx",
        ),
        migrations.RenameIndex(
            model_name="razorpayrealcustomerpaymentordercontrolledmutationrollback",
            new_name="p8f_rb_attempt_created_idx",
            old_name="payments_ra_attempt_7c48e9_idx",
        ),
        migrations.RenameIndex(
            model_name="razorpayrealcustomerpaymentordercontrolledmutationrollback",
            new_name="p8f_rb_status_created_idx",
            old_name="payments_ra_status_0ddbba_idx",
        ),
    ]
