# Generated by Django 5.1.15 on 2026-05-16 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0025_phase8f_hotfix_rename_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Phase10CPaymentLinkRefreshGate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("test", "test"), ("live", "live")],
                        db_index=True,
                        default="test",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("approved", "approved"),
                            ("executed", "executed"),
                            ("rolled_back", "rolled_back"),
                            ("cancelled", "cancelled"),
                            ("failed", "failed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                (
                    "operator_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("operator_note", models.TextField(blank=True, default="")),
                ("intent", models.TextField(blank=True, default="")),
                ("director_signoff", models.TextField(blank=True, default="")),
                (
                    "recorded_signoff_window_start_utc",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "recorded_signoff_window_end_utc",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("recorded_signoff_window_valid", models.BooleanField(default=False)),
                ("previous_payment_url", models.TextField(blank=True, default="")),
                ("new_payment_url", models.TextField(blank=True, default="")),
                (
                    "razorpay_link_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("razorpay_short_url", models.TextField(blank=True, default="")),
                ("force_replace", models.BooleanField(default=False)),
                ("prepared_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("rolled_back_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("sandbox", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase10c_link_refresh_gates",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["payment", "-created_at"],
                        name="p10c_gate_pay_created_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="p10c_gate_status_created_idx",
                    ),
                    models.Index(
                        fields=["mode", "-created_at"],
                        name="p10c_gate_mode_created_idx",
                    ),
                ],
            },
        ),
    ]
