# Generated by Django 5.1.15 on 2026-06-02 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("saas", "0007_phase7d_hotfix_director_signoff_window"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AiCopilotSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suggestion_type",
                    models.CharField(
                        choices=[
                            ("lead_summary", "Lead / customer summary"),
                            ("call_priority", "Call priority recommendation"),
                            ("call_script", "Suggested call script"),
                            ("objection_handling", "Objection handling"),
                            ("compliance_risk", "QA / compliance risk review"),
                            ("pilot_recommendation", "Pilot recommendation"),
                            ("task_recommendation", "Task recommendation"),
                            ("director_briefing", "Director briefing recommendation"),
                            ("whatsapp_draft", "WhatsApp follow-up draft"),
                            ("payment_followup_draft", "Payment follow-up draft"),
                            ("rto_rescue_draft", "RTO rescue draft"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("customer", "Customer"),
                            ("order", "Order"),
                            ("imported_queue_item", "Imported call-queue item"),
                            ("pilot_plan", "Pilot plan"),
                            ("pilot_task", "Pilot task"),
                            ("manual", "Manual / none"),
                        ],
                        db_index=True,
                        default="manual",
                        max_length=24,
                    ),
                ),
                ("source_id", models.CharField(blank=True, default="", max_length=64)),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField(blank=True, default="")),
                ("recommendation", models.TextField(blank=True, default="")),
                ("risk_flags", models.JSONField(blank=True, default=list)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("confidence_score", models.FloatField(default=0.0)),
                (
                    "ai_mode",
                    models.CharField(
                        choices=[
                            ("mock", "Mock (deterministic)"),
                            ("sandbox", "Sandbox (deterministic)"),
                            ("live_gated", "Live-gated (not invoked)"),
                            ("unavailable", "Unavailable"),
                        ],
                        db_index=True,
                        default="mock",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending review"),
                            ("approved", "Approved (internal)"),
                            ("rejected", "Rejected"),
                            ("applied_internal", "Applied (internal only)"),
                        ],
                        db_index=True,
                        default="pending_review",
                        max_length=20,
                    ),
                ),
                ("reviewer_note", models.TextField(blank=True, default="")),
                ("provider_call_made", models.BooleanField(default=False)),
                ("external_action_allowed", models.BooleanField(default=False)),
                ("external_action_taken", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_copilot_suggestions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="saas.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_copilot_suggestions_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AiCopilotReviewEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("generated", "Generated"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("commented", "Commented"),
                            ("applied_internal", "Applied (internal only)"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suggestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="ai_copilot.aicopilotsuggestion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="aicopilotsuggestion",
            index=models.Index(fields=["-created_at"], name="ai_cop_sug_created_idx"),
        ),
        migrations.AddIndex(
            model_name="aicopilotsuggestion",
            index=models.Index(fields=["status"], name="ai_cop_sug_status_idx"),
        ),
        migrations.AddIndex(
            model_name="aicopilotsuggestion",
            index=models.Index(fields=["suggestion_type"], name="ai_cop_sug_type_idx"),
        ),
        migrations.AddIndex(
            model_name="aicopilotsuggestion",
            index=models.Index(fields=["source_type"], name="ai_cop_sug_source_idx"),
        ),
        migrations.AddIndex(
            model_name="aicopilotreviewevent",
            index=models.Index(fields=["-created_at"], name="ai_cop_evt_created_idx"),
        ),
        migrations.AddIndex(
            model_name="aicopilotreviewevent",
            index=models.Index(fields=["action"], name="ai_cop_evt_action_idx"),
        ),
    ]
