# Generated by Django 5.1.15 on 2026-06-02 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_copilot", "0001_phase16i_ai_copilot"),
        ("saas", "0007_phase7d_hotfix_director_signoff_window"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AiApprovedAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            (
                                "create_calling_followup_task",
                                "Create calling follow-up task",
                            ),
                            (
                                "create_qa_review_task",
                                "Create QA / compliance review task",
                            ),
                            ("create_pilot_task", "Create pilot task"),
                            ("create_customer_note", "Create customer note"),
                            ("create_order_note", "Create order note"),
                            ("create_callback_item", "Create callback reminder item"),
                            ("create_rto_review_task", "Create RTO review task"),
                            (
                                "create_payment_followup_task",
                                "Create payment follow-up task",
                            ),
                            (
                                "create_dispatch_review_task",
                                "Create dispatch readiness review task",
                            ),
                            (
                                "create_director_review_item",
                                "Create Director review item",
                            ),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("customer", "Customer"),
                            ("order", "Order"),
                            ("imported_queue_item", "Imported call-queue item"),
                            ("pilot_plan", "Pilot plan"),
                            ("pilot_task", "Pilot task"),
                            ("manual", "Manual / none"),
                        ],
                        db_index=True,
                        default="manual",
                        max_length=24,
                    ),
                ),
                ("source_id", models.CharField(blank=True, default="", max_length=64)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "assigned_team",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_internal_action", "Pending internal action"),
                            ("applied_internal", "Applied (internal only)"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending_internal_action",
                        max_length=24,
                    ),
                ),
                ("provider_action_attempted", models.BooleanField(default=False)),
                ("provider_action_taken", models.BooleanField(default=False)),
                ("external_action_allowed", models.BooleanField(default=False)),
                ("external_action_taken", models.BooleanField(default=False)),
                ("safety_snapshot", models.JSONField(blank=True, default=dict)),
                ("result_payload", models.JSONField(blank=True, default=dict)),
                (
                    "failure_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_actions_applied",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_actions_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_actions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="saas.organization",
                    ),
                ),
                (
                    "source_suggestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approved_actions",
                        to="ai_copilot.aicopilotsuggestion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AiApprovedActionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("applied_internal", "Applied (internal only)"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                            ("note_added", "Note added"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="ai_copilot.aiapprovedaction",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="aiapprovedaction",
            index=models.Index(fields=["-created_at"], name="ai_act_created_idx"),
        ),
        migrations.AddIndex(
            model_name="aiapprovedaction",
            index=models.Index(fields=["status"], name="ai_act_status_idx"),
        ),
        migrations.AddIndex(
            model_name="aiapprovedaction",
            index=models.Index(fields=["action_type"], name="ai_act_type_idx"),
        ),
        migrations.AddIndex(
            model_name="aiapprovedaction",
            index=models.Index(fields=["source_type"], name="ai_act_source_idx"),
        ),
        migrations.AddIndex(
            model_name="aiapprovedactionevent",
            index=models.Index(fields=["-created_at"], name="ai_act_evt_created_idx"),
        ),
        migrations.AddIndex(
            model_name="aiapprovedactionevent",
            index=models.Index(fields=["event_type"], name="ai_act_evt_type_idx"),
        ),
    ]
