# Generated by Django 5.1.15 on 2026-06-04 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_copilot", "0002_phase16j_ai_action_queue"),
        ("saas", "0007_phase7d_hotfix_director_signoff_window"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AiActionWorkEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("claimed", "Claimed"),
                            ("started", "Started"),
                            ("blocked", "Blocked"),
                            ("unblocked", "Unblocked"),
                            ("completed_internal", "Completed (internal only)"),
                            ("reassigned", "Reassigned"),
                            ("note_added", "Note added"),
                            ("director_review_requested", "Director review requested"),
                        ],
                        db_index=True,
                        max_length=28,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="aiapprovedaction",
            name="assignee_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_actions_assigned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aiapprovedaction",
            name="blocker_reason",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="aiapprovedaction",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aiapprovedaction",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_actions_completed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aiapprovedaction",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Unassigned"),
                    ("calling", "Calling"),
                    ("confirmation", "Confirmation"),
                    ("qa_compliance", "QA / Compliance"),
                    ("finance_accounts", "Finance / Accounts"),
                    ("dispatch_warehouse", "Dispatch / Warehouse"),
                    ("delivery_rto", "Delivery / RTO"),
                    ("director_office", "Director Office"),
                    ("data_ops", "Data Ops"),
                    ("ai_governance", "AI Governance"),
                ],
                db_index=True,
                default="",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="aiapprovedaction",
            name="due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aiapprovedaction",
            name="last_activity_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aiapprovedaction",
            name="work_status",
            field=models.CharField(
                choices=[
                    ("unassigned", "Unassigned"),
                    ("assigned", "Assigned"),
                    ("in_progress", "In progress"),
                    ("blocked", "Blocked"),
                    ("completed_internal", "Completed (internal only)"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="unassigned",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="aiapprovedaction",
            index=models.Index(fields=["work_status"], name="ai_act_workstatus_idx"),
        ),
        migrations.AddIndex(
            model_name="aiapprovedaction",
            index=models.Index(fields=["department"], name="ai_act_dept_idx"),
        ),
        migrations.AddField(
            model_name="aiactionworkevent",
            name="action",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_events",
                to="ai_copilot.aiapprovedaction",
            ),
        ),
        migrations.AddField(
            model_name="aiactionworkevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="aiactionworkevent",
            index=models.Index(fields=["-created_at"], name="ai_act_work_created_idx"),
        ),
        migrations.AddIndex(
            model_name="aiactionworkevent",
            index=models.Index(fields=["event_type"], name="ai_act_work_type_idx"),
        ),
    ]
