# Generated by Django 5.1.15 on 2026-06-04 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_copilot", "0003_phase16k_action_workboard"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AiWorkboardDepartmentMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("", "Unassigned"),
                            ("calling", "Calling"),
                            ("confirmation", "Confirmation"),
                            ("qa_compliance", "QA / Compliance"),
                            ("finance_accounts", "Finance / Accounts"),
                            ("dispatch_warehouse", "Dispatch / Warehouse"),
                            ("delivery_rto", "Delivery / RTO"),
                            ("director_office", "Director Office"),
                            ("data_ops", "Data Ops"),
                            ("ai_governance", "AI Governance"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("can_claim", models.BooleanField(default=True)),
                ("can_work", models.BooleanField(default=True)),
                ("can_complete", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_workboard_memberships_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_workboard_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user"], name="ai_wb_member_user_idx"),
                    models.Index(fields=["department"], name="ai_wb_member_dept_idx"),
                    models.Index(fields=["is_active"], name="ai_wb_member_active_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("user", "department"),
                        name="ai_wb_member_unique_active_user_dept",
                    )
                ],
            },
        ),
    ]
