# Generated by Django 5.1.15 on 2026-06-08 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_copilot", "0004_phase16l_workboard_department_member"),
        ("saas", "0007_phase7d_hotfix_director_signoff_window"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AiDirectorBriefingSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("window_days", models.IntegerField(default=7)),
                ("briefing_payload", models.JSONField(blank=True, default=dict)),
                ("executive_summary", models.JSONField(blank=True, default=list)),
                ("attention_items", models.JSONField(blank=True, default=dict)),
                ("recommendations", models.JSONField(blank=True, default=list)),
                ("blocked_live_actions", models.JSONField(blank=True, default=list)),
                ("safety_snapshot", models.JSONField(blank=True, default=dict)),
                ("ai_mode", models.CharField(default="mock", max_length=12)),
                ("readonly", models.BooleanField(default=True)),
                ("internal_only", models.BooleanField(default=True)),
                ("provider_call_made", models.BooleanField(default=False)),
                ("external_action_taken", models.BooleanField(default=False)),
                ("live_autonomous_locked", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("acknowledged", "Acknowledged"),
                            ("needs_follow_up", "Needs follow-up"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=20,
                    ),
                ),
                ("director_note", models.TextField(blank=True, default="")),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_briefing_snapshots_acknowledged",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_briefing_snapshots_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="saas.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AiDirectorBriefingSnapshotEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("acknowledged", "Acknowledged"),
                            ("marked_needs_follow_up", "Marked needs follow-up"),
                            ("archived", "Archived"),
                            ("note_added", "Note added"),
                            ("viewed", "Viewed"),
                        ],
                        db_index=True,
                        max_length=28,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="ai_copilot.aidirectorbriefingsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="aidirectorbriefingsnapshot",
            index=models.Index(fields=["status"], name="ai_brf_snap_status_idx"),
        ),
        migrations.AddIndex(
            model_name="aidirectorbriefingsnapshot",
            index=models.Index(fields=["-created_at"], name="ai_brf_snap_created_idx"),
        ),
        migrations.AddIndex(
            model_name="aidirectorbriefingsnapshot",
            index=models.Index(fields=["acknowledged_at"], name="ai_brf_snap_ack_idx"),
        ),
        migrations.AddIndex(
            model_name="aidirectorbriefingsnapshot",
            index=models.Index(fields=["created_by"], name="ai_brf_snap_creator_idx"),
        ),
        migrations.AddIndex(
            model_name="aidirectorbriefingsnapshotevent",
            index=models.Index(fields=["-created_at"], name="ai_brf_snap_evt_crt_idx"),
        ),
        migrations.AddIndex(
            model_name="aidirectorbriefingsnapshotevent",
            index=models.Index(fields=["event_type"], name="ai_brf_snap_evt_type_idx"),
        ),
    ]
