# Generated by Django 5.1.15 on 2026-05-16 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_governance", "0010_phase9e_add_calling_team_leader_agent"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaioAuditSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_at", models.DateTimeField(db_index=True)),
                ("window_days", models.IntegerField(default=30)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("green", "green"),
                            ("amber", "amber"),
                            ("red", "red"),
                        ],
                        db_index=True,
                        default="green",
                        max_length=8,
                    ),
                ),
                ("compliance_risk_call_count", models.IntegerField(default=0)),
                (
                    "compliance_risk_agent_labels",
                    models.JSONField(blank=True, default=list),
                ),
                ("transcript_backlog_count", models.IntegerField(default=0)),
                (
                    "call_quality_trend",
                    models.CharField(
                        choices=[
                            ("up", "up"),
                            ("flat", "flat"),
                            ("down", "down"),
                            ("no_data", "no_data"),
                        ],
                        default="no_data",
                        max_length=10,
                    ),
                ),
                ("agent_data_gaps", models.IntegerField(default=0)),
                ("agent_data_gap_names", models.JSONField(blank=True, default=list)),
                ("agent_anomaly_flags", models.JSONField(blank=True, default=dict)),
                (
                    "weak_learning_indicators",
                    models.JSONField(blank=True, default=list),
                ),
                ("ceo_audit_notes", models.JSONField(blank=True, default=list)),
                ("recommendation_text", models.TextField(blank=True, default="")),
                ("audited_agents", models.JSONField(blank=True, default=list)),
                ("sandbox", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="caio_audit_snapshots",
                        to="ai_governance.agentrun",
                    ),
                ),
            ],
            options={
                "ordering": ("-snapshot_at",),
                "indexes": [
                    models.Index(fields=["-snapshot_at"], name="caio_snap_at_idx"),
                    models.Index(fields=["severity"], name="caio_snap_severity_idx"),
                ],
            },
        ),
    ]
