# Generated by Django 5.1.15 on 2026-04-26 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActiveCall",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("customer", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=24)),
                ("agent", models.CharField(max_length=80)),
                ("language", models.CharField(max_length=40)),
                ("duration", models.CharField(default="0:00", max_length=16)),
                ("stage", models.CharField(max_length=80)),
                ("sentiment", models.CharField(max_length=24)),
                ("script_compliance", models.IntegerField(default=100)),
                ("detected_objections", models.JSONField(blank=True, default=list)),
                ("approved_claims_used", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("lead_id", models.CharField(db_index=True, max_length=32)),
                ("customer", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=24)),
                ("agent", models.CharField(max_length=80)),
                ("language", models.CharField(max_length=40)),
                ("duration", models.CharField(default="0:00", max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Live", "Live"),
                            ("Queued", "Queued"),
                            ("Completed", "Completed"),
                            ("Missed", "Missed"),
                        ],
                        default="Queued",
                        max_length=12,
                    ),
                ),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("Positive", "Positive"),
                            ("Neutral", "Neutral"),
                            ("Hesitant", "Hesitant"),
                            ("Annoyed", "Annoyed"),
                        ],
                        default="Neutral",
                        max_length=12,
                    ),
                ),
                ("script_compliance", models.IntegerField(default=100)),
                ("payment_link_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="CallTranscriptLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("who", models.CharField(max_length=40)),
                ("text", models.TextField()),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript_lines",
                        to="calls.activecall",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
    ]
