# Generated by Django 5.1.15 on 2026-05-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0003_call_branch_call_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="transcript_ingested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="call",
            name="transcript_line_count",
            field=models.IntegerField(default=0),
        ),
    ]
