# Generated by Django 5.1.15 on 2026-05-16 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0004_phase11a_transcript_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallQualityScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scored_at", models.DateTimeField()),
                (
                    "scoring_version",
                    models.CharField(default="deterministic_v1", max_length=40),
                ),
                ("line_count", models.IntegerField(default=0)),
                (
                    "agent_label",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "duration_raw",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("connection_score", models.IntegerField(default=0)),
                ("product_knowledge_score", models.IntegerField(default=0)),
                ("compliance_score", models.IntegerField(default=0)),
                ("objection_handling_score", models.IntegerField(default=0)),
                ("tonality_score", models.IntegerField(default=0)),
                ("composite_score", models.IntegerField(default=0)),
                ("flags", models.JSONField(blank=True, default=list)),
                ("raw_signals", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "call",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_score",
                        to="calls.call",
                    ),
                ),
            ],
            options={
                "ordering": ("-scored_at",),
                "indexes": [
                    models.Index(fields=["scored_at"], name="p11b_score_scored_at_idx"),
                    models.Index(
                        fields=["composite_score"], name="p11b_score_composite_idx"
                    ),
                    models.Index(
                        fields=["agent_label"], name="p11b_score_agent_label_idx"
                    ),
                ],
            },
        ),
    ]
