# Generated by Django 5.1.15 on 2026-05-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0005_phase11b_call_quality_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiCallCampaignGate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("approved", "approved"),
                            ("executing", "executing"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                            ("cancelled", "cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                (
                    "ai_assistant_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("stage_filter", models.JSONField(blank=True, default=list)),
                ("max_leads", models.IntegerField(default=20)),
                ("leads_selected", models.JSONField(blank=True, default=list)),
                ("leads_attempted", models.JSONField(blank=True, default=list)),
                ("calls_attempted", models.IntegerField(default=0)),
                ("calls_dispatched", models.IntegerField(default=0)),
                ("calls_skipped", models.IntegerField(default=0)),
                (
                    "operator_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("operator_note", models.TextField(blank=True, default="")),
                ("intent", models.TextField(blank=True, default="")),
                ("director_signoff", models.TextField(blank=True, default="")),
                (
                    "recorded_signoff_window_start_utc",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "recorded_signoff_window_end_utc",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("recorded_signoff_window_valid", models.BooleanField(default=False)),
                ("prepared_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("sandbox", models.BooleanField(default=False)),
                (
                    "vapi_mode_at_execute",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["status"], name="aicc_status_idx"),
                    models.Index(fields=["-prepared_at"], name="aicc_prepared_at_idx"),
                ],
            },
        ),
    ]
