# Generated by Django 5.1.15 on 2026-05-18 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0006_phase12a_ai_call_campaign_gate"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallOutcomeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lead_id", models.CharField(blank=True, default="", max_length=32)),
                (
                    "current_lead_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "detected_outcome",
                    models.CharField(
                        choices=[
                            ("connected_converted", "connected_converted"),
                            ("connected_callback", "connected_callback"),
                            ("connected_not_interested", "connected_not_interested"),
                            ("connected_unclear", "connected_unclear"),
                            ("not_connected", "not_connected"),
                            ("no_transcript", "no_transcript"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "suggested_lead_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("high", "high"),
                            ("medium", "medium"),
                            ("low", "low"),
                        ],
                        default="low",
                        max_length=8,
                    ),
                ),
                ("evidence", models.JSONField(blank=True, default=dict)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("approved", "approved"),
                            ("skipped", "skipped"),
                            ("applied", "applied"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applied_by",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("classified_at", models.DateTimeField()),
                (
                    "scoring_version",
                    models.CharField(default="deterministic_v1", max_length=40),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "call",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcome_record",
                        to="calls.call",
                    ),
                ),
                (
                    "campaign_gate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outcome_records",
                        to="calls.aicallcampaigngate",
                    ),
                ),
            ],
            options={
                "ordering": ("-classified_at",),
                "indexes": [
                    models.Index(
                        fields=["review_status"], name="cor_review_status_idx"
                    ),
                    models.Index(
                        fields=["detected_outcome"], name="cor_detected_outcome_idx"
                    ),
                    models.Index(
                        fields=["-classified_at"], name="cor_classified_at_idx"
                    ),
                ],
            },
        ),
    ]
