# Generated by Django 5.1.15 on 2026-05-18 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0007_phase12b_call_outcome_record"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostCallFollowUpQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lead_id", models.CharField(blank=True, default="", max_length=32)),
                (
                    "lead_phone_last4",
                    models.CharField(blank=True, default="", max_length=4),
                ),
                (
                    "follow_up_type",
                    models.CharField(
                        choices=[
                            ("payment_reminder", "payment_reminder"),
                            ("callback_confirmation", "callback_confirmation"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("needs_customer_setup", "needs_customer_setup"),
                            ("gate_prepared", "gate_prepared"),
                            ("dispatched", "dispatched"),
                            ("skipped", "skipped"),
                            ("gate_prep_failed", "gate_prep_failed"),
                            ("sandbox_skipped", "sandbox_skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("phase7e_gate_id", models.IntegerField(blank=True, null=True)),
                ("customer_found", models.BooleanField(default=False)),
                ("operator_note", models.TextField(blank=True, default="")),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dispatched_by",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "call_outcome",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_up",
                        to="calls.calloutcomerecord",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["status"], name="pcfu_status_idx"),
                    models.Index(
                        fields=["follow_up_type"], name="pcfu_followup_type_idx"
                    ),
                    models.Index(fields=["-created_at"], name="pcfu_created_at_idx"),
                ],
            },
        ),
    ]
