# Generated by Django 5.1.15 on 2026-04-26 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "awb",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("order_id", models.CharField(db_index=True, max_length=32)),
                ("customer", models.CharField(max_length=120)),
                ("state", models.CharField(max_length=60)),
                ("city", models.CharField(max_length=80)),
                ("status", models.CharField(default="Manifested", max_length=80)),
                ("eta", models.CharField(default="", max_length=40)),
                ("courier", models.CharField(default="Delhivery", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="WorkflowStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("step", models.CharField(max_length=80)),
                ("at", models.CharField(blank=True, default="", max_length=40)),
                ("done", models.BooleanField(default=False)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline",
                        to="shipments.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
    ]
