# Generated by Django 5.1.15 on 2026-04-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RescueAttempt",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("order_id", models.CharField(db_index=True, max_length=32)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("AI Call", "AI Call"),
                            ("Human Call", "Human Call"),
                            ("WhatsApp", "WhatsApp"),
                            ("SMS", "SMS"),
                        ],
                        default="AI Call",
                        max_length=24,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Rescue Call Done", "Rescue Call Done"),
                            ("Convinced", "Convinced"),
                            ("Returning", "Returning"),
                            ("No Response", "No Response"),
                        ],
                        default="Pending",
                        max_length=24,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-attempted_at",),
            },
        ),
    ]
