# Generated by Django 5.1.15 on 2026-05-01 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saas", "0001_initial"),
        ("shipments", "0003_shipment_delhivery_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipments",
                to="saas.branch",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipments",
                to="saas.organization",
            ),
        ),
    ]
