# Generated by Django 5.1.15 on 2026-05-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0004_shipment_branch_shipment_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="Phase7GLiveRealCustomerDispatchGate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("approved", "approved"),
                            ("executed", "executed"),
                            ("failed", "failed"),
                            ("cancelled", "cancelled"),
                            ("rollback_recorded", "rollback_recorded"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("target_order_id", models.CharField(db_index=True, max_length=32)),
                (
                    "operator_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "director_signoff_text_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "recorded_signoff_window_start_utc",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "recorded_signoff_window_end_utc",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("awb_number", models.CharField(blank=True, default="", max_length=64)),
                (
                    "delhivery_shipment_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "cancellation_attempted_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("cancellation_result", models.JSONField(blank=True, default=dict)),
                ("blockers", models.JSONField(blank=True, default=list)),
                (
                    "next_action",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("payment_mutation_made", models.BooleanField(default=False)),
                ("order_payment_status_changed", models.BooleanField(default=False)),
                ("whatsapp_sent", models.BooleanField(default=False)),
                ("razorpay_called", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="p7gl_gate_status_created_idx",
                    ),
                    models.Index(
                        fields=["target_order_id", "-created_at"],
                        name="p7gl_gate_order_created_idx",
                    ),
                ],
            },
        ),
    ]
