# Generated by Django 5.1.15 on 2026-04-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DashboardMetric",
            fields=[
                (
                    "key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("value", models.IntegerField(default=0)),
                ("delta_pct", models.FloatField(blank=True, null=True)),
                ("completed", models.IntegerField(blank=True, null=True)),
                ("pending", models.IntegerField(blank=True, null=True)),
                ("alerts", models.IntegerField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ("sort_order", "key"),
            },
        ),
    ]
