# Generated by Django 5.1.15 on 2026-04-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "product",
                    models.CharField(max_length=120, primary_key=True, serialize=False),
                ),
                ("approved", models.JSONField(blank=True, default=list)),
                ("disallowed", models.JSONField(blank=True, default=list)),
                ("doctor", models.CharField(default="Pending review", max_length=120)),
                (
                    "compliance",
                    models.CharField(default="Pending review", max_length=120),
                ),
                ("version", models.CharField(default="v1.0", max_length=24)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("product",),
            },
        ),
    ]
