# Generated by Django 5.1.15 on 2026-05-28 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("saas", "0007_phase7d_hotfix_director_signoff_window"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectorBriefingReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                (
                    "decision_status",
                    models.CharField(
                        choices=[
                            ("reviewed", "Reviewed"),
                            ("needs_action", "Needs action"),
                            ("deferred", "Deferred"),
                        ],
                        db_index=True,
                        default="reviewed",
                        max_length=20,
                    ),
                ),
                ("snapshot_ref", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="saas.organization",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="director_briefing_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="dbr_created_idx"),
                    models.Index(fields=["decision_status"], name="dbr_decision_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TeamRoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operational_role",
                    models.CharField(
                        choices=[
                            ("director_admin", "Director / Admin"),
                            ("calling_agent", "Calling Agent"),
                            ("confirmation_team", "Confirmation Team"),
                            ("warehouse_dispatch", "Warehouse / Dispatch"),
                            ("delivery_rto", "Delivery / RTO Team"),
                            ("qa_compliance", "QA / Compliance"),
                            ("finance_accounts", "Finance / Accounts"),
                            ("read_only_viewer", "Read-only Viewer"),
                        ],
                        db_index=True,
                        default="read_only_viewer",
                        max_length=40,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_role_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="saas.organization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_role_assignment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["operational_role", "user_id"],
                "indexes": [
                    models.Index(fields=["operational_role"], name="tra_role_idx"),
                    models.Index(fields=["is_active"], name="tra_active_idx"),
                ],
            },
        ),
    ]
